### ISSUE TITLE
Synonym request for specimen collection process 

### ISSUE THREAD

**Issue by celineaubert** [obi-ontology/obi#1002]
Please can "sampling" and "sample collection be added as synonyms for sample collection process ( http://purl.obolibrary.org/obo/OBI_0000659)

**Comment by pbuttigieg** [comment]
Please also ping @ramonawalls on the BCO tracker as there's overlap here.

**Comment by zhengj2007** [comment]
Discussed on Mar 11, 2019 OBI call.

We are happy to add these as synonym of term: material sampling process (http://purl.obolibrary.org/obo/OBI_0000744) which is the subClass of "Specimen collection process". 

Does it work for you?

**Comment by celineaubert** [comment]
Yes it would work. Thanks!

**Comment by rctauber** [comment]
@zhengj2007 can you confirm that #1008 resolves this issue? Thanks!

**Comment by zhengj2007** [comment]
@rctauber I don't know why I made two pull requests. It seems the issue is not solved. Shall I make edit and create a new pull request? Thanks!

**Comment by zhengj2007** [comment]
Complete
