### ISSUE TITLE
Generate definitions for instances with duplicate (or missing) definitions

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#1004]
Many instances of organization (such as eBioscience) share the definition:
> A supplier of flow cytometry analyzers

We can auto-generate a definition based on the label of the instance and its asserted type, e.g.:
> A particular organization that is named eBioscience.

Based on the fact that eBioscience has the two type axioms:
* organization
* 'has role' some 'manufacturer role'

We could potentially include the anonymous type axiom, as well:
> A particular organization named eBioscience that has role manufacturer role.

... or something along those lines. The implementation would be a SPARQL query, which is pretty straightforward. I would appreciate feedback on which version of the definition would be better.

**Comment by bpeters42** [comment]
I would only use the asserted parent class.
