### ISSUE TITLE
NTR: disease specific study design

### ISSUE THREAD

**Issue by sjbost** [obi-ontology/obi#1009]
The Ontology for Biobanking (OBIB) community is requesting that disease specific study design be added to OBI with the following definition: A study design for which material and information is collected from subjects that have already developed a particular disease.

**Comment by sjbost** [comment]
1. editor preferred term: disease specific study design
2. alternative terms: disease-specific study design
3. textual definition: A study design for which material and information is collected from subjects that have already developed a particular disease.
4. definition source: MIABIS contributors
5. logical definition: subclass of 'study design'
6. example of usage: A study of the symptoms experienced by patients who have been diagnosed by multiple sclerosis employs a disease specific study design
7. term editor: MIABIS

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2019-06-10. We agreed that this term is ready to add to OBI. It would be good to add this to the [study-designs.tsv](https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/study-designs.tsv) template. @sjbost will give that a try.

Minor fix: "diagnosed by multiple sclerosis" -> "diagnosed with multiple sclerosis"

**Comment by sjbost** [comment]
Fixed by #1035
