### ISSUE TITLE
NTR: birth cohort study design

### ISSUE THREAD

**Issue by sjbost** [obi-ontology/obi#1010]
The Ontology for Biobanking (OBIB) community is requesting that birth cohort study design be added to OBI with the following definition: A cohort study design for which the subjects are followed from the time of birth usually including information about gestation and follow up.

**Comment by sjbost** [comment]
1. editor preferred term: birth cohort study design
2. alternative terms: none
3. textual definition: A cohort study design for which the subjects are followed from the time of birth usually including information about gestation and follow up.
4. definition source: MIABIS contributors
5. logical definition: subclass of 'study design'
6. example of usage: The LucKi Birth Cohort Study was designed and started in 2006 to follow children from birth into adulthood on a wide range of determinants, disorders, and diseases.
7. term editor: MIABIS

**Comment by jamesaoverton** [comment]
Discussed on the OBI 2019-06-10 developer call. Ready to add to OBI.

**Comment by sjbost** [comment]
Fixed by #1035
