### ISSUE TITLE
"has unit" object property

### ISSUE THREAD

**Issue by ddooley** [obi-ontology/obi#1011]
Currently we have "has measurement unit label", but as indicated on monday's call this is tied too specifically to "measurement" role, so we discussed a more general "has unit" object property.  I presume people would be weary of renaming "has measurement unit label" to "has unit"?

The idea of removing "label" suffix is driven by the fact that it is the unit entity that is being referenced, not a particular label - e.g. "g", "gram"@en, "gramme"@fr.  (Unit entities may be defined further in the future, e.g. compound units via "has denominator" or "has numerator" etc, but referencing the unit doesn't depend on this work.)

Now there are four other ontologies listed in OLS that have "has unit", incl. SIO, which defines it as "has unit is a relation between a quantity and the unit it is a multiple of." However I presume OBI would lay claim to its own term id as part of its fundamental roster of entities for describing data.

Thoughts?

**Comment by cstoeckert** [comment]
My recollection of why we said 'measurement unit label' instead of simply 'measurement unit' was to distinguish the symbols in data that denote units from the units themselves such as meters and grams which exist as material entities in reality. Thus the definition: "A measurement unit label is as a label that is part of a scalar measurement datum and denotes a unit of measure."

**Comment by ddooley** [comment]
Folks may want to skip this, but in another twist, looking up definition of "kilogram" I just learned that fundamental SI definitions are undergoing a change after May 20, 2019. Kilogram definition won't involve a direct reference to "material entity", but instead 

"The International Committee for Weights and Measures (CIPM) approved a proposed redefinition of SI base units in November 2018 that defines the kilogram by defining the Planck constant to be exactly 6.62607015×10−34 kg⋅m2⋅s−1. This approach effectively defines the kilogram in terms of the second and the metre, and will take effect in 2019."

Derivative units would indirectly be affected this way too. Oy!  This approach of referencing constants is being rolled out for all SI units.

**Comment by ddooley** [comment]
Aside from the CIPM statement that removes reference to units as "material entities in reality", the second argument is that "g", "gram", "gramme" are all labels but what we want to reference is the underlying unit; the label variations can be handled by rdfs:label language variants, synonyms, etc.

**Comment by ddooley** [comment]
Idea may surface again in core, but will close for now.
