### ISSUE TITLE
OBI home PURL broken?

### ISSUE THREAD

**Issue by mcourtot** [obi-ontology/obi#1012]
http://purl.obofoundry.org/obo/obi/

which I get to from the [OBI wikipedia page ](https://en.wikipedia.org/wiki/Ontology_for_Biomedical_Investigations) reference 1, returns a 404

**Comment by jamesaoverton** [comment]
It should be <http://obi-ontology.org>. I don't know where they got that from. There are two problems with it:

1. We've never used "purl.obofoundry.org" only "purl.obolibrary.org".
2. <http://purl.obolibrary.org/obo/obi/*> is used as a prefix catch-all to our old SVN repository, to handle old development links. It never went to our home page.
