### ISSUE TITLE
NTR: FFPE specimen

### ISSUE THREAD

**Issue by sjbost** [obi-ontology/obi#1019]
1. editor preferred term: FFPE specimen
2. alternative terms: formalin-fixed paraffin-embeded specimen
3. textual definition: A specimen that has been fixed in formalin and embedded in paraffin.
4. definition source: https://www.biochain.com/general/what-is-ffpe-tissue/
5. logical definition: subclass of paraffin specimen
6. example of usage: An FFPE specimen used in oncology
7. term editor: MIABIS

**Comment by turbomam** [comment]
put acronym in alternative term, not in primary label

**Comment by turbomam** [comment]
saved as http://purl.obolibrary.org/obo/OBI_1200000

**Comment by rctauber** [comment]
Hi @turbomam - can you confirm that #1024 resolves this?

**Comment by turbomam** [comment]
Did you want me to pull and check in Protege?  I have some kind of
conflict. Maybe I should do a fresh clone into a different directory?

$ git pull
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 78 (delta 40), reused 52 (delta 25), pack-reused 0
Unpacking objects: 100% (78/78), done.
From https://github.com/obi-ontology/obi
   4aaf524..5a31ca9  master        -> origin/master
   779bcec..0ba0c05  swabspecimen2 -> origin/swabspecimen2
Your configuration specifies to merge with the ref
'refs/heads/mam_ffpe_20190528

                                                                    '
from the remote, but no such ref was fetched.

**Comment by rctauber** [comment]
It's been merged into master. I just wanted to check in and see if this issue was resolved. Thanks!

**Comment by sjbost** [comment]
This link (http://purl.obolibrary.org/obo/OBI_1200000) isn't work for me. Am I using the wrong one?

**Comment by jamesaoverton** [comment]
The new term has been added to the development version of OBI (the `master` branch) but that ID will not resolve until a new release of OBI has been made and the various term browsers such as Ontobee have a chance to update.

We plan to start a new OBI release this week.

**Comment by sjbost** [comment]
Ah, got it. Thanks!

**Comment by sjbost** [comment]
Fixed by #1030
