### ISSUE TITLE
NTR: medication dose

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1020]
NTR: medication dose

definition: a dose that measures the quantity of a medication material administered to an organism

parent: dose (OBI_0000984)

**Comment by jamesaoverton** [comment]
Discussed on OBI call 2019-06-10.

This makes sense as a child of 'dose', but like #1021 it would be more useful to have as a value specification going forward.

'medication material' and 'medication role' are both in OBIB

**Comment by johnwjudkins** [comment]
My proposed definition for this term as a value specification:

label: medication dose value specification
definition: a scalar value specification that specifies the value of the quantity of a material entity administered to an organism as a treatment

(alternatively, a scalar value specification that specifies the value of the quantity of a medication material administered to an organism)

BTW this and 'medication timepoint' are intended to be about already-administered treatments rather than prescribed treatments.

**Comment by beckyjackson** [comment]
It may make sense to subclass this to specify the measurements (g, ml, etc...)

Action item: @johnwjudkins to create PR for this
