### ISSUE TITLE
NTR: medication timepoint

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1021]
NTR: medication timepoint

Definition: a time measurement datum that specifies the point in time that a human participant under investigation self-administers a medication material

Parent: time measurement datum

**Comment by mbrochhausen** [comment]
I might be wrong, but I think you are not really looking at a time measurement datum here (definition: A scalar measurement datum that is the result of measuring a temporal interval.) What you seem to be looking for seems to be more the identifier of a specific time point (think Star Trek star dates). These aren't measurements. The are names we stick on specific periods of time (notable the name of one time slice can be different in the Central time zone and in the Eastern time zone). Just food for thought.

**Comment by ddooley** [comment]
A number of OBI folks are leaning towards adding (see https://github.com/obi-ontology/obi/issues/981)

    instantaneous time value specification
        'has specified value' some (xsd:dateTime or xsd:dateTimeStamp)"

So then above defn. could be: 

    an instantaneous time value specification that specifies the point in time that a human participant under investigation self-administers a medication material

**Comment by johnwjudkins** [comment]
Thank you both for your suggestions. I agree the term is an identifier/specifier of a time point rather than a measurement. @ddooley , that definition works for me (even if we just call it a value spec w/o the phrase "instantaneous time").

**Comment by ddooley** [comment]
About whether it is a measurement or not - consider that all such recorded times (not predictions or simulations though) are achieved by noting the digits provided by an analog or digital clock device. Whatever it spits out is a measurement, regardless of the underlying scheme the numbers present, in the same way as measuring "20g" mass. Experimentally one may later discover an error occurred with the clock apparatus just like any other device. It suffers the vagaries of measurement.

**Comment by ddooley** [comment]
I should add that I think the primary semantic defn. for "medication timepoint" should be a value specification as above.  Its just that one can then additionally layer on whether it is a measurement, recommendation, estimate etc. if needed.

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2019-06-17.

This should go in the [`value-specification.tsv`](https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/value-specifications.tsv).

I think that this term is fine, but there are still decisions to make about #981.

**Comment by beckyjackson** [comment]
This is a term for a record of something that is *already completed*, as in the medication has already been administered.

Action item: @johnwjudkins to create PR
