### ISSUE TITLE
NTR: bacteriological assay

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1022]
(Re: today's call)
NTR: bacteriological assay
Definition: an organism identification assay that has as parts biochemical reactions having material derived from the specimen as input. The discovery of which products result from these reactions contribute to achieving the objective of determining which species of bacteria are present in the specimen.

This definition is meant to distinguish this type of assay from a PCR assay, ELISA, microscopy assay, TaqMan, etc. The biochemical reactions that make up parts of the assay are called "biochemical tests"; examples are the oxidase, motility, and TSI tests.

**Comment by jamesaoverton** [comment]
Discussed on OBI 2019-06-17 call.

Because this is an assay, it would go in the [`assay.tsv`](https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/assays.tsv) template file.

The general discussion on the call was about being more general than identifying the species -- it could identify the genus, for example. Since the goal is to exclude identifying the taxon by microscopy, the label should be more specific, such as "classification of bacteria by biochemical assay". Unfortunately we don't have a "biochemical assay".

Parent term: organism identification assay

**Comment by jamesaoverton** [comment]
We also noticed that 'organism identification assay' is specifically about identifying the species, which is more specific than what we want to do here. Any thoughts @cstoeckert @zhengj2007 ?

**Comment by cstoeckert** [comment]
I agree that species is more specific than desired. I think we should broaden the textual definition for both 'organism identification assay' and 'organism identification objective'. I propose replacing 'species' with 'taxonomic classification' as in "An assay that identifies the taxonomic classification of an organism in a specimen."

**Comment by johnwjudkins** [comment]
Discussed today (2019-06-24). It appears neither "assay" nor "bacteriology" are appropriate to label this term. "Bacteriology" is too vague; my group wants this term disjoint from ELISA, TaqMan, etc. Also, the term I'm requesting does not represent an assay but a collection of assays.

This term may be better categorized as an "investigation" in that the group of tests are planned, have results that are documented, and result in a conclusion. ("Study design execution", which is part of an investigation, could also be appropriate.)

**Comment by johnwjudkins** [comment]
After more reading and discussion, I think we can still define this term as an assay.

Label: differential medium assay

Definition:
an organism identification assay that uses a differential medium to achieve its objective

Differential media to which I refer are described here:
[https://www.uwyo.edu/molb2210_lab/info/biochemical_tests.htm](https://www.uwyo.edu/molb2210_lab/info/biochemical_tests.htm)

OMP's 'differential test phenotype' term and its children also refer to differential media.

**Comment by cstoeckert** [comment]
Discussed on OBI July 8, 2019 call. Agreement that new proposed term and definition are good and better that bacteriological assay. Also, would be good to have differential medium as a term to refer to in a logical definition.

**Comment by johnwjudkins** [comment]
I've created a pull request to add to assays.tsv
