### ISSUE TITLE
NTR: genealogical record

### ISSUE THREAD

**Issue by sjbost** [obi-ontology/obi#1023]
1. editor preferred term: genealogical record
2. alternative terms: none
3. textual definition: A document about the family relationships of persons related as members of a domestic group linked through descent from a common ancestor, marriage, or adoption. 
4. definition source: Adaptation of 'family relationship' in eagle-i resource ontology
5. logical definition: subclass of 'document;' is about some family relationship
6. example of usage: A family tree is a type of genealogical record.
7. term editor: MIABIS

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2019-06-10. This looks good. It should be added to [`obi-edit.owl`](https://github.com/obi-ontology/obi/blob/master/src/ontology/obi-edit.owl).

For the logical definition, the best we can do with the current OBI is just "subclass of 'document'". It would be nice to add an "subclass of 'is about' some X" eventually. We don't have a term for 'family relationship' in OBI. Eagle-i has that. OMRSE has 'family', and not much else. PCO has 'family' and 'biological family'. We haven't imported from any of these before. We won't bother right now.

**Comment by sjbost** [comment]
Fixed by #1035
