### ISSUE TITLE
NTRs: national registry and national biomedical registry

### ISSUE THREAD

**Issue by sjbost** [obi-ontology/obi#1031]
**national registry**
1. editor preferred term: national registry
2. alternative terms: none
3. textual definition: An information content entity that contains information about a nationwide cohort of individuals.
4. definition source: MIABIS contributors
5. logical definition: subclass of information content entity
6. example of usage: The Social Security Administration's Death Master File is a national registry in the United States.
7. term editor: MIABIS

**national biomedical registry**
1. editor preferred term: national biomedical registry
2. alternative terms: none
3. textual definition: A national registry that contains information about individuals that was accumulated for a biomedical purpose, such as diagnoses, treatments, or outcomes.
4. definition source: MIABIS contributors
5. logical definition: subclass of national registry
6. example of usage: The Care Register for Health Care, maintained by the Finnish National Institute for Health and Welfare, is a national biomedical registry.
7. term editor: MIABIS

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2019-06-10. I asked why these are not 'centrally registered identifier registry' and @cstoeckert replied that these are much more general: they include all sorts of information about the history of a patient or sample.

In our context, a cohort is defined relative to a study. We prefer the word "group": i.e. "a nationwide group of individuals".

Nobody objected to adding both terms. They should go `obi-edit.owl`.

**Comment by sjbost** [comment]
Fixed by #1035
