### ISSUE TITLE
Typo in "training objective"?

### ISSUE THREAD

**Issue by Mttbnchtt** [obi-ontology/obi#1032]
The 'example of usage' of 'training objective' is "A training objective is fulfilled by e.f. a bioconductor tutorial which instructs the user in the use of a package". Should it be "A training objective is fulfilled by e.g. a bioconductor tutorial which instructs the user in the use of a package" ("e.g." instead of "e.f.")?

**Comment by bpeters42** [comment]
Thanks for catching these - we should fix immediately.
