### ISSUE TITLE
NTR: ribosomal RNA depleted RNA extract

### ISSUE THREAD

**Issue by rachhuntley** [obi-ontology/obi#1036]
Hello,

I'd like to request a new term 'ribosomal RNA depleted RNA extract' 

Is_a RNA extract (http://purl.obolibrary.org/obo/OBI_0000880)

Definition: An RNA extract that is the output of an extraction process in which total RNA has been depleted of ribosomal RNA.

Synonym: rRNA depleted RNA extract.

Thanks,
Rachael Huntley.

**Comment by cstoeckert** [comment]
Discussed on OBI call Jul 8, 2019. Agree that this should go in OBI. Suggested additional synonym is: ribosomal depleted RNA extract.

**Comment by rachhuntley** [comment]
Great, thank you.

**Comment by DanBerrios** [comment]
Discussed on call 08/19/19:

Consider See also process of ribosomal RNA depletion.  Otherwise

**Comment by jamesaoverton** [comment]
Fixed by #1054. Thanks @DanBerrios
