### ISSUE TITLE
Some recommendations for OBI github/website/obo page to enhance usability

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1046]
A few assorted recommendations

## Create a link from the GitHub repo to http://obi-ontology.org/

Many people will end up at the GitHub repo which is optimized for developers, the README dives straight in with editing details (in the odk we put this in src/ontology and have the top level README be more general interest). It's customary to have a bit more background in the README, also link to main site. And currently there are no links to the main obi site.

You can also configure GH to show the link to the website prominently at the top. I don't have permission to do this but it should look like this:

![image](https://user-images.githubusercontent.com/50745/62394626-9da71880-b522-11e9-9a78-24bbde3d0c58.png)

## Show examples of use on OBI site

The website http://obi-ontology.org/ is really good but I recommend having a bit more about how OBI can be used before diving into what an ontology is. Links to any examples would be really helpful. May be hard as many OBI usages may be internal e.g. mapping internal schemas etc.

There are great examples in
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0154556

 - IEDB
 - EuPathDb
 - ISA

There are 11 listed here: https://fairsharing.org/bsg-s000070/

Don't underestimate the confusion of the average user coming to an ontology site. Having simple examples of how an ontology is used on the ground can really help.

I would hyperlink the example terms.

Consider a link to OLS as it's more biologist-friendly

## Curate examples in obi.md on OBO site

OBO has a usages field. See for example https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/cl.md or https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/envo.md

We don't yet show this but it's really useful to have this metadata curated for (re)review. This info can be uploaded to fairsharing too, but obo foundry needs are for more granular curation of usages.

## Update other info on obo site

https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/obi.md

 - Frontmatter links to old Brinkman paper
 - no publications field curated in yaml section
 - no documentation on what the obi_core product is
 - no link to an obo artefact. I know most obi people want to ignore obo format but unfortunately it's in common use in the bioinformatics world

**Comment by bpeters42** [comment]
I agree with pretty much all of the proposals. The one thing I am wondering is if some of these should not be part of @rvita OBO registry wide review of ontology metadata. I believe some things like publication are already on her to-do list (but maybe that was primary citation).

**Comment by cmungall** [comment]
Yes, I think Randi was doing publications, but ontologies should be eager
to be proactive and get their publications up there themselves!

>

**Comment by beckyjackson** [comment]
> Create a link from the GitHub repo to http://obi-ontology.org/

I can't add the link to the GitHub, but I made a PR to update the README: #1047

> Show examples of use on OBI site

@ddooley has been working on updating the documentation: https://github.com/obi-ontology/obi-ontology.org/pull/2

> Curate examples in obi.md on OBO site
> Frontmatter links to old Brinkman paper
> no documentation on what the obi_core product is

I've created a PR to update the OBO Foundry md: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/967.
It includes TURBO and ECO as users, but perhaps there are others we can include? If @rvita isn't taking care of `publications`, I can add that in as well.

> no link to an obo artefact. I know most obi people want to ignore obo format but unfortunately it's in common use in the bioinformatics world

We don't currently have an OBO release. I will work on stripping some axioms out and generating an OBO release so that we can add this to the OBO Foundry md.

**Comment by jamesaoverton** [comment]
Thanks @beckyjackson. I added that link to the GtiHub repo and merged the registry update. Please make a PR for the OBO-format artifact when it's ready.

**Comment by turbomam** [comment]
@beckyjackson has addressed all of the suggestions.  The OBO format file will be posted as is.  If anyone downloads it and experiences problems, we can look into additional;l validation.

**Comment by beckyjackson** [comment]
We now have an OBO product available - http://purl.obolibrary.org/obo/obi.obo (will work as soon as purl is updated, see https://github.com/OBOFoundry/purl.obolibrary.org/pull/563)

The only thing we have left from the recommendations is the documentation updates, which are in progress.

**Comment by DanBerrios** [comment]
James will fork this issue into a new one for the doc updates.

**Comment by jamesaoverton** [comment]
Closing in favour of #1052
