### ISSUE TITLE
unsatisfiable class OBI:comment on investigation

### ISSUE THREAD

**Issue by kaiiam** [obi-ontology/obi#1050]
Greetings OBI team, while building an application ontology which imports form a variety of OBO ontologies, I've run across the following [issue (see it in PMO here)](https://github.com/hurwitzlab/planet-microbe-ontology/issues/1) with the class OBI[:comment on investigation](http://purl.obolibrary.org/obo/OBI_0001898) which when reasoned upon with ELK 0.4.3 becomes inferred as owl:Nothing. 

![image](https://user-images.githubusercontent.com/12255688/63249541-fb996700-c269-11e9-8b14-92c29825dde8.png)

@cmungall pointed out that this issue stems from the combination of a continuant and a process with an AND in the axiom.

**Comment by DanBerrios** [comment]
Discussed on OBI Dev call 08/19/2019.  Assigned to Jie

**Comment by bpeters42** [comment]
The logical definition should probably be changed to: 
'textual entity' and ('is about' some (investigation or ('part of' some investigation' or 'participates in' some 'investigation'))

Will comment on the disjoints separately.

**Comment by zhengj2007** [comment]
The term was added for NIAID BRC standards with description: "Any additional information about the initial specimen collection event, the sample preparation process, or any other aspect of the project worth noting." 

The logical definition proposed by @bpeters42 looks good and fits what NIAID BRC needs. Will update the logical axioms in the OBI.

**Comment by cmungall** [comment]
curious as to how this passed robot checks.

**Comment by jamesaoverton** [comment]
@cmungall Not ROBOT's fault. We haven't been asserting BFO disjoints when building OBI. PMO is getting "continuant DisjointWith 'part of' some occurrent" from somewhere else. I made a separate OBI issue for this #1051.
