### ISSUE TITLE
NTRs: mutagenesis terms

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#1058]
These are NTRs for the continuation of the ECO-OBI collaboration.

**site-directed mutagenesis**
---
**subClassOf**: 'induced mutation'
**Definition**: An induced mutation in which a specific base change is programmed into the sequence of a synthetic primer. (https://www.ncbi.nlm.nih.gov/books/NBK21945/)

**random mutagenesis**
---
**subClassOf**: 'induced mutation'
**Definition**: An induced mutation that produces a completely random mutation, either by introducing the organism to mutagens, or through a process such as error-prone PCR. (person:RCJ / PMID:15153637)

**Comment by beckyjackson** [comment]
**random mutagenesis** updated definition: An induced mutation that produces a random mutation, either by introducing the organism to mutagens, or through a process such as error-prone PCR.

Discussed on OBI call 10/7/2019. Will move forward with creating a PR to add these terms.

**Comment by beckyjackson** [comment]
**site-directed mutagenesis**: "Hypoxia-inducible factor-1 (HIF-1), a heterodimeric transcription factor, is activated when cells are exposed to hypoxia... Specific interactions between three amino acids (Ser22, Ala25, Arg30) of the HIF-1alpha subunit and DNA bases were identified. In order to further investigate the role of these amino acids, we generated four mutants of the HIF-1alpha subunit using site-directed mutagenesis." (PMID:12393189)

**random mutagenesis**: "CRP is one of the global regulatory proteins that can regulate the transcription of over 400 genes in E. coli... Amino acid mutations were introduced to CRP by either error‐prone PCR or DNA shuffling... Five CRP mutants (MT1–MT5) were selected from the error‐prone PCR libraries with enhanced osmotolerance." (PMID:22179860)

**Comment by jamesaoverton** [comment]
Closed by #1060
