### ISSUE TITLE
NTRs: reconstitution assays

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#1059]
These are NTRs for the continuation of the ECO-OBI collaboration.

reconstitution assay
---
**subClassOf**: assay [?]
**Definition**: An assay in which a cellular process is replicated from the bottom-up using isolated components in order to observe how the components work together. (https://jcs.biologists.org/content/132/4/jcs227488)
**Example of usage**: "In an attempt to define the mechanism of insulin-regulated glucose transporter 4 (Glut4) translocation, we have developed an in vitro reconstitution assay... insulin-induced Glut4 translocation can be reconstituted in vitro to a limited extent by using isolated membranes." (PMID:10611313)

**Additional axioms**:
* realizes some (concretizes some ('in vitro design'
 and 'molecular interaction study design'))
* has_specified_output some ('is about' some 'cellular process')

in vitro transcription reconstitution assay
---
(alternatively, could be called just 'transcription reconstitution assay')
**subClassOf**: reconstitution assay
**Definition**: A reconstitution assay in which RNA synthesis is investigated using RNA polymerase II transcription systems replicated in vitro from their base components. (PMID:9237163)
**Example of usage**: 
An in vitro reconstituted mouse transcription system helped identify an NF-Y interacting promoter as essential for high-level expression from the R2 promoter. (PMID:11502214)

**Additional axioms**:
* has_specified_output some ('is about' some 'transcription, RNA-templated')

**Comment by beckyjackson** [comment]
To be added:
* example of usages
* What is the data generated from these assays?

**Comment by beckyjackson** [comment]
Examples and additional axioms added above.

**Comment by jamesaoverton** [comment]
Closed by #1060
