### ISSUE TITLE
terms from MIRO

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#106]
Met them at the IDO Meeting. This is an extraction of their ontology below "method" File attached.

Reported by: alanruttenberg

Original Ticket: "obi/obi-terms/106":https://sourceforge.net/p/obi/obi-terms/106

**Comment by turbomam** [comment]
Most recent version of MIRO edited with OBO-edit and loaded into OntoBee in 2014.
MIRO PURLs don't resolve as of 18. December 2017
Are there terms that are still worth importing?  Not a priority right now.
