### ISSUE TITLE
Issue with 'trial statistician role' axiom

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#1067]
'trial statistician role' (`OBI:0000234`) has the axiom:
```
'has part' some 
    (realizes some 
        (concretizes some 'clinical study design')) 
 and ('realized in' only investigation)
```

'realizes' has a domain of 'process' which means that 'trial statistician role' has part some process. Since this is a role (a continuant), it cannot have a process (occurrent) part.

**Comment by beckyjackson** [comment]
I think you could say:
```
'realized in' only 
  (investigation and
    ('has part' some 
      (realizes some 
        (concretizes some 'clinical study design'))))
```

To say that the 'trial statistician role' is realized in an investigation that has a part where a 'clinical study design' is executed. I could be incorrect, though.

**Comment by bpeters42** [comment]
This looks good to me

**Comment by DanBerrios** [comment]
Discussed on call 11/4/19.

**Comment by beckyjackson** [comment]
This is fixed in the new release.
