### ISSUE TITLE
NTR: Illumina NovaSeq 6000 Sequencing Platform 

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1069]
Project: ENCODE 

Illumina's high throughput sequencing instrument, the NovaSeq 6000 was released in 2017 and is most likely the successor of Illumina's HiSeq models. The NovaSeq leverages cost effectiveness with their highest output yet (up to 6 Tb of data). 

NTR: "Illumina NovaSeq 6000"

- Alternative terms: NovaSeq 6000
- Textual definition: A DNA sequencer which is manufactured by the Illumina corporation, with two flow cells and an output of up to 6000 Gb (32-40 B reads per run). The sequencer utilizes synthesis technology and patterned flow cells to optimize throughput and even spacing of sequencing clusters. 
- Definition source for the textual definition: http://www.illumina.com/systems/sequencing-platforms/novaseq.html
- Logical definition (or parent term):
- Example of usage: Lei, Y., Zhang, J., Cao, L., Zhao, R., Feng, J., & Li, B. (2018). Draft genome sequence of _Xenophilus_ sp. E41 isolated from an activated sludge reactor treating wastewater with high cephalexin concentration. Journal of Global Antimicrobial Resistance (2018), PMID: 30316965
- Term editor: Bonita Lam

**Comment by DanBerrios** [comment]
Example of usage: "Genomic DNA of Xenophilus sp. E41 was extracted and sequenced using an Illumina NovaSeq 6000 system."
Logical definition: subclass of DNA Sequencer, is_manufactured_by value Illumina
