### ISSUE TITLE
Collected ENCODE and RNAseq issues

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1082]
Here are some RNAseq related issues from ENCODE people like @jahilton , @bonitalam , @carrieadavis  , @siiraa , venkat . They are in varying stages of completeness.

- #877 
- #872
- #864
- #863
- #852 
- #851 
- #850 
- #849
- #848
- #847
- #831 
- #665
- #650 

I think there was also some talk about the potential of combinatorial/highly pre-composed terms like `polyA-selected single cell RNAseq`. See #995 and #930

**Comment by ddooley** [comment]
We will close old (650, 665 etc.) items barring further feedback.

**Comment by turbomam** [comment]
How important are these issues now?
