### ISSUE TITLE
NTR: Oxford Nanopore Sequencing Platforms

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1086]
Project: ENCODE

Oxford Nanopore has developed a number of small affordable sequencing instruments that allow labs to sequence their own samples without sending them to sequencing centers that run much larger and pricier sequencers. We would like to some NTRs for their platforms. 

NTR: "Oxford Nanopore MinION"

- Alternative terms: MinION
- Textual definition: A portable DNA sequencer which is manufactured by the Oxford Nanopore Technologies corporation, that uses consumable flow cells producing up to 30 Gb of DNA sequence data per flow cell. The sequencer produces real-time results and utilizes nanopore technology with up to 512 nanopore channels in the sensor array. 
- Definition source for the textual definition: https://nanoporetech.com/products/minion
- Logical definition (or parent term): subclass of DNA Sequencer, is_manufactured_by value Oxford Nanopore Technologies 
- Example of usage: Zascavage, R. R., Hall, C. L., Thorson, K., Mahmoud, M., Sedlazeck, F. J., & Planz, J. V. (2019). Approaches to Whole Mitochondrial Genome Sequencing on the Oxford Nanopore MinION. Current Protocols in Human Genetics, PMID: 31743587
- Term editor: Bonita Lam

NTR: "Oxford Nanopore GridION Mk1"

- Alternative terms: Oxford Nanopore GridIONx5, GridION Mk1
- Textual definition: A DNA sequencer that is manufactured by the Oxford Nanopore Technologies corporation, that can run and analyze up to five individual flow cells producing up to 150 Gb of data per run. The sequencer produces real-time results and utilizes nanopore technology with the option of running the flow cells concurrently or individually. 
- Definition source for the textual definition: https://nanoporetech.com/products/gridion
- Logical definition (or parent term): subclass of DNA Sequencer, is_manufactured_by value Oxford Nanopore Technologies 
- Example of usage: Ge, H., Lin, K., Wu, S., Wang, Y., Zhang, Z., Wang, Z., Zhang, Y., Huang, Z., Zhou, C., Lin, Q., Wu, J., Liu, L., Hu, J., Huang, Z., & Zheng, L. (2019) De novo assembly of a chromosome-level reference genome of red-spotted grouper (_Epinephelus akaara_) using Nanopore sequencing and Hi-C. Molecular Ecology Resources, PMID: 31325912
- Term editor: Bonita Lam

NTR: "Oxford Nanopore PromethION"

- Alternative terms: PromethION
- Textual definition: A DNA sequencer that is manufactured by the Oxford Nanopore Technologies corporation, capable of running up to 48 flow cells and producing up to 7.6 Tb of data per run. The sequencer produces real-time results and utilizes Nanopore technology, with each flow cell allowing up to 3,000 nanopores to be sequencing simultaneously. 
- Definition source for the textual definition: https://nanoporetech.com/products/promethion
- Logical definition (or parent term): subclass of DNA Sequencer, is_manufactured_by value Oxford Nanopore Technologies 
- Example of usage: De Coster, W., De Rijk, P., De Roeck, A., De Pooter, T., D'Hert, S., Strazisar, M., Sleegers, K., & Van Broeckhoven C. (2019) Structural variants identified by Oxford Nanopore PromethION sequencing of the human genome. Genome Research, PMID: 31186302
- Term editor: Bonita Lam

**Comment by DanBerrios** [comment]
@bonitalam These mostly look correct, Bonita.  For Examples of usage, we generally put in natural language uses of the term/concept, not references to (in this case, equipment) usage in practice.   So I will find some examples of natural language and replace.    
Do we need a separate concept for "nanopore" or "nanopore technology"?  I think so.... Would this suffice? http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C62343

**Comment by bonitalam** [comment]
@DanBerrios thank you for letting me know about examples of usage, I will keep that in mind for future requests. 

I think your suggestion for a separate concept to capture "nanopore" is correct, and the NCI term looks to describe it adequately.

**Comment by DanBerrios** [comment]
EFO now has all these ONT concepts...would suggest straight import: 

http://www.ebi.ac.uk/efo/EFO_0008633
http://www.ebi.ac.uk/efo/EFO_0008632
http://www.ebi.ac.uk/efo/EFO_0008634

**Comment by jamesaoverton** [comment]
OBI doesn't import from EFO, for two main reasons:

1. EFO is not an OBO ontology
2. EFO imports from OBI, which would mean circular imports, which causes various problems

2 is more important than 1. We could revise this policy/practise but we need to mitigate the problems from 2.

In the past, we have often defined new OBI terms and given EFO credit as the definition source.

**Comment by DanBerrios** [comment]
@jamesaoverton @bonitalam Will it meet users' needs to just have them in EFO? If so, then we don't need to do anything for this issue...

**Comment by bonitalam** [comment]
@DanBerrios for us, we only use OBI to annotate our assays/platforms. We would like to avoid using EFO terms to start doing this and confusing our users with multiple ontologies.

**Comment by jamesaoverton** [comment]
It's fine to add them to OBI. We now have a [devices.tsv](https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/devices.tsv) template.

**Comment by jamesaoverton** [comment]
Adding these in #1196 with the following IDs:

OBI:0002750 Oxford Nanopore MinION
OBI:0002751 Oxford Nanopore GridION Mk1
OBI:0002752 Oxford Nanopore PromethION
