### ISSUE TITLE
NTR: biological variation design

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1089]
Name | Value
-- | --
Label | biological variation design
Definition | A study design type investigates differences caused by intrinsic characteristics of an organism(s) or biological system; epidemiological reasons (history of biosources); manipulation, treatment or modification of an organism(s).
Parent | OBI_0500000 study design
Definition source | EFO_0004667 biological variation design

The term is needed by VEuPathDB database. However, I think the term is very general and not clear how it is different from other OBI study designs or could be parent of some of existing OBI study designs. Would like to have inputs from other OBIers.

**Comment by ddooley** [comment]
Need example of this study type.  Dan: example: Serum assay result variance in a population.  Characterization of population.
Definition needs grammatical cleanup.
VectorBase using this as general class to place studies.
Chris: possibly an organizing class.  Will get clarification on use.

**Comment by ddooley** [comment]
Dan found this example: https://discovery.dundee.ac.uk/en/publications/european-biological-variation-study-eubivas-within-and-between-su

**Comment by zhengj2007** [comment]
More information of Karyotype on wikipedia: https://en.wikipedia.org/wiki/Karyotype

**Comment by cstoeckert** [comment]
No longer needed.
