### ISSUE TITLE
NTR: population based design

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1090]
Name | Value
-- | --
Label | population based design
Definition | A study design that study is done at the population level or among the population groups, generally to find the cause, incidence or spread of the disease or to see the response to the treatment, nutrition or environment.
Parent | OBI_0500000 study design
Definition source | EFO_0001430 population based design
Logic axiom | is_about some 'population of organisms'

**Comment by ddooley** [comment]
Vector Base using term - want OBI version.  
Dan notes: observational study involving gathering information from entire population. Individual level data is not involved.  
Chris will take to in-house epis for comment.

**Comment by cstoeckert** [comment]
See https://link.springer.com/referenceworkentry/10.1007%2F978-1-4419-1005-9_45
"The important issue is the selection of the individuals that are included into the study – they should be representative of all individuals in the a priori defined specific population."
- should 'aim to be representative' as it's not always possible to be ensure generalizability

**Comment by cstoeckert** [comment]
Discussed on OBI June 22, 2020. Call will improve definition as indicated above and add.

**Comment by cstoeckert** [comment]
https://github.com/obi-ontology/obi/pull/1242

**Comment by cstoeckert** [comment]
PR has been merged
