### ISSUE TITLE
NTRs: document related publication

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1091]
Name | Value
-- | --
Label | published document
Definition | A document that is published such as in a journal.
Parent | IAO_0000310 document
Definition source | EFO_0001796 published

Name | Value
-- | --
Label | document  in preparation for publicaton
Definition | A document that is in preparation for submission to be published.
Parent | IAO_0000310 document
Definition source | EFO_0001795 in preparation

**Comment by zhengj2007** [comment]
Discussed on Jan 27, 2020 OBI call.

We may add terms as 'publication status'. The approach proposed here is for easily defined logically when need by adding associated processes. 

Dan and Bjoern will post comments on it.

**Comment by DanBerrios** [comment]
EFO has publication status: published, submitted, in preparation.  

OBI has imported IAO concepts, of document->publication (IAO:0000310)  and document-> report -> journal article (IAO:0000013).   This doesn't make sense...a journal article is always a publication and should be a subclass of publication.  So...what do we do about that?

Either way we try to handle this, we don't provide a coordination (relation) linking instances that are the same document as it goes through these stages.  Do we want to try to model that?

**Comment by zhengj2007** [comment]
Is 'published document' same as IAO:0000311 publication (http://purl.obolibrary.org/obo/IAO_0000311)?

Current IAO:0000311 publication definition is: "A document that has been accepted by a publisher". 

I think the definition may need to be improved and the term should be defined using equivalent axioms, such as:
- definition: A document that is output of a publishing process. 
- equivalent axiom: document and is_specified_output_of some 'publishing process'

In this case, we can infer different kinds of document under publication, such as IAO:0000013 journal article.

It also needs to add term 'publishing process', 'publisher role' (the role will be realized during publishing process).

The 'publishing process' has various sub-process, like review, accept, etc. By defining these sub-processes, it will be easy to define document publication status, such as at preparation, submission, review, accepted, etc.

**Comment by zhengj2007** [comment]
Discussed on the call on May 4, 2020. 

Dan: proposed to relabel to "draft documentation"

Chris: prefer to add the general process: publishing process. 

James: suggest to look at PROV (https://www.w3.org/TR/prov-o/) and use the PROV terms if they are available.

**Comment by turbomam** [comment]
@zhengj2007 @johnwjudkins @cstoeckert and I investigated PROV-O and then compared notes. We don't see how to use their terms, in a light-weight way, to talk about the lifecycle of a document (draft, preprint, "published"). PROV-O seems to be more concerned with the reliability of a document, like a newspaper article. For example, how can author 1 substantiate claims in article 1? Have any other authors made claims based on article 1? Etc. 

We can discuss more at an upcoming OBI call.

**Comment by DanBerrios** [comment]
OBI Dev Discussion: Not a set of fixed paths between these classes.  These 2 classes are approved by the group

**Comment by zhengj2007** [comment]
Proposed definition for 'publishing process':
Definition: A planned process of making information, such as literature, music, and software etc., available to the public for sale or for free.
Definition source: https://en.wikipedia.org/wiki/Publishing

'published document': 
Definition: A document that is published such as in a journal.
Equivalent axiom: document and is_specified_output_of some 'publishing process'
(not require a publisher)

Note: IAO: publication: "A document that has been accepted by a publisher".
Shall we assign 'IAO: publication' as a subclass of 'published document' or improve its definition and assign 'published document' as its alternative term or verse vice.

Shall add the terms in IAO?

**Comment by johnwjudkins** [comment]
Discussed 2020-10-05. Jie will bring up with IAO.

**Comment by zhengj2007** [comment]
Added in IAO
