### ISSUE TITLE
NTR: individual organism specimen

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1092]
Name | Value
-- | --
Label | individual organism specimen
Definition | A specimen composed of an individual organism to be studied in an investigation.
Definition source | EFO_0000542 individual
Parent | OBI_0100051 specimen
Logic axiom | has_component (RO_0002180) exactly 1 organism (OBI_0100026)

**Comment by ddooley** [comment]
Discussed in call - sounds good, we'll add.

**Comment by zhengj2007** [comment]
Term is in latest OBI release.
