### ISSUE TITLE
NTR: Giemsa stain assay

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1093]
Name | Value
-- | --
Label | Giemsa stain assay
Definition | An assay that uses a Giemsa stain to characterize cells. Examples of usge:  cytogenetics; the histopathological diagnosis of malaria and other parasites; differentiate nuclear and cytoplasmic morphology of the various blood cells like platelets, RBCs, WBCs
Definition source | https://microbeonline.com/giemsa-stain-principle-procedure-and-results/
Parent | OBI_0000070 assay

Notes: do we need to add Giemsa stain as a reagent in OBI?

**Comment by cstoeckert** [comment]
Discussed on Dec. 16, 2019. Need to add Giemsa stain. Put in assay template. A type of imaging assay (possibly microscopy assay).

**Comment by zhengj2007** [comment]
Discussed on Jan 27, 2020.

Need to add device, microscopy, and has_part process imaging assay.

**Comment by zhengj2007** [comment]
Added following information in assay template: assays.tsv

Name | Value
-- | --
label | Giemsa stain assay
definition | An assay that uses a Giemsa stain to characterize cells. 
example of usage | Cytogenetics; the histopathological diagnosis of malaria and other parasites; differentiate   nuclear and cytoplasmic morphology of the various blood cells like platelets, RBCs, WBCs 
term editor| Jie Zheng\|Chris Stoeckert 
ontology term requester | VEuPathDB 
term tracker item | https://github.com/obi-ontology/obi/issues/1093 
logical type | subclass 
parent class | assay 
detection technique | imaging assay 
evaluant | cell 
device  | microscope
