### ISSUE TITLE
NTR: number of generations

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1094]
Name | Value
-- | --
Label | number of generations
Definition | A data item of the number of steps in the line of descent from a common ancestor.
Definition source | EFO_0000507 generation, NCIT_C88214 generation
Parent | IAO_0000027 data item
Logic axiom | is about' only 'multicellular organism' (CARO_0000012)

**Comment by cstoeckert** [comment]
Discussed on Dec. 16, 2019 call. Should check with PCO. Put multicellular component in the label.

**Comment by zhengj2007** [comment]
Do you mean the label like: "number of generations of multicellular organism"?

**Comment by ddooley** [comment]
Yes on longer label - discussed in call.

**Comment by zhengj2007** [comment]
Term has been added in PCO and available in the latest PCO release.
