### ISSUE TITLE
NTR: duration time of insecticide exposure

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1096]
Name | Value
-- | --
Label | duration time of insecticide exposure
Definition | A time measurement datum that measures a temporal interval of insecticide exposure.
Parent | IAO_0000416 time measurement datum

The term is needed by VEuPathDB database.

**Comment by cstoeckert** [comment]
DIscussed on Dec. 16, 2019 call. Should we have an intermediate class about exposure duration? There is work going on for an Exposure Ontology also Environmental Conditions Treatments and Exposures to look out for. OK to add now but may want to coordinate these terms with other efforts. 
Is this a time duration or measurement or value specification. Clarify the label. Include comment abut other efforts.

**Comment by zhengj2007** [comment]
It seems that the term fit the scope of Environmental conditions, treatments and exposures ontology (ECTO) better. If agree, I think we should contact ECTO developers rather than add the term in OBI. 

Besides, it needs to clarify it is a measurement datum or a value specification.

**Comment by zhengj2007** [comment]
Discussed on Jan 27, 2020. Will contact ECTO developers.

**Comment by zhengj2007** [comment]
Submitted the term to ECTO:
https://github.com/EnvironmentOntology/environmental-exposure-ontology/issues/72

**Comment by zhengj2007** [comment]
Discussed on OBI call May 4, 2020. OBI will not take the term.
