### ISSUE TITLE
NTRs: karyotype related

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1097]
Name | Value
-- | --
Label | karyotype information
Definition | A genetic characteristics information that is about the number and appearance of chromosomes in the nucleus of an eukaryotic cell.
Definition source | EFO_0004426 karyotype
Parent | OBI_0001404 genetic characteristics information

Name | Value
-- | --
Label | partial karyotype information
Definition | A karyotype information that is about the structural variation of just one chromosome in a diploid eukaryotic cell, not the whole genome.
Parent | karyotype information

The terms are needed by VEuPathDB database.

**Comment by zhengj2007** [comment]
Discussed on Jan 27, 2020.

Proposed to also add 'full karyotype information' as the subClassOf 'karyotype information'.

Proposed to change 'partial karyotype information' definition as:
A karyotype information that is about the structural variation of partial genome rather than whole genome.
Add logical axiom: part_of 'full karyotype information'.

**Comment by DanBerrios** [comment]
Jie: I believe the EFO concept "karyotype" is the exact same thing as your proposed "karyotype information".  What do you see as the difference?  @zhengj2007

**Comment by zhengj2007** [comment]
Discussed on OBI call May 4th, 2020.
EFO "karyotype" is quality.
We'd like to define "karyotype" as information that associated with assay output.
The definition need to be improved.
Chris will work with VectorBase people to improve the definition.

**Comment by ddooley** [comment]
More information of Karyotype on wikipedia: https://en.wikipedia.org/wiki/Karyotype . Note 6 different characteristics they mention.

**Comment by cstoeckert** [comment]
Discussed on June 22, 2020 call. VectorBase is good with proposed updated definition for partial karyotype information.

**Comment by zhengj2007** [comment]
Terms were added and available in latest release
