### ISSUE TITLE
NTR: MPRA (massively parallel reporter assay)

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1101]
The ENCODE project has new MPRA experiments, and we would like to request for a term to be made.

editor preferred term: MPRA
alternate terms: massively parallel reporter assay
textual definition: An assay in which multiplexing the construction and interrogation of larger libraries of reporter constructs allows measurement of the transcriptional regulatory activities of thousands to hundreds of thousands of DNA sequences. 
definition source for the textual definition: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4364389/
logical definition: reporter assay —> MPRA

Thank you!

**Comment by ddooley** [comment]
Suggest longer name for label: "massively parallel reporter assay"
alternate term: MPRA
parent: "reporter gene assay"

**Comment by ddooley** [comment]
Made a new pull request for this.
