### ISSUE TITLE
NTR: PRO-cap

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1102]
There is a new assay called PRO-cap which is a variant of PRO-Seq. Instead of identifying the location of active RNA polymerases (PRO-Seq), PRO-cap is used to map the location of transcription start sites (TSSs). 

There is an existing EFO term for PRO-cap. https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0008868

editor preferred term: PRO-cap
alternate terms: 
textual definition: Precision nuclear run-on and sequencing to identify the location of transcription start sites (TSSs)
definition source for the textual definition: https://www.nature.com/articles/nprot.2016.086
logical definition: PRO-seq —> PRO-cap assay 

Thank you!

**Comment by ddooley** [comment]
As an assay it needs to fit in our assay template.  And we just need to verify definition fits and has parent PRO-seq.

**Comment by DanBerrios** [comment]
Parent: RNA-seq assay, not PRO-seq

Otherwise it can be added to the assay template.

**Comment by DanBerrios** [comment]
@jamesaoverton These concepts are already in EFO, and according to James, we don't import concepts from EFO.  Do they need to duplicated in OBI? Or will having them in EFO meet users' needs?

**Comment by jamesaoverton** [comment]
Adding this with ID OBI:0002753
