### ISSUE TITLE
The phrase "processual entity" in the definition for OBI: planned process

### ISSUE THREAD

**Issue by CDowland** [obi-ontology/obi#1103]
The definition for OBI: planned process reads as follows: "A processual entity that realizes a plan which is the concretization of a plan specification." It would be more straightforward to replace "processual entity" with "process" in the definition, since planned process is a child of process, and there is no class called "processual entity" (there used to be one in BFO, but not anymore).

**Comment by bpeters42** [comment]
Agree. I hadn't realized processual entity was discontinued.

**Comment by ddooley** [comment]
revised and made pull request.

**Comment by jamesaoverton** [comment]
There are problems with the fix. Since IAO imports OBI:0000011, changing the definition in OBI without updating IAO led us to having two different definitions, and failed out test suite. I'll have to give more thought to this.

**Comment by zhengj2007** [comment]
Hi @jamesaoverton, when do you plan to update the definition in OBI? 

I am asked to make a new release for IAO. Do you think that I update the term definition in the IAO first is a solution? Thanks!

**Comment by jamesaoverton** [comment]
Yes. If you can fix it in IAO life will be much simpler for OBI. That would be great.

**Comment by zhengj2007** [comment]
OK. I will do it in the new release.

**Comment by CDowland** [comment]
I hope nobody minds me asking, but what is the source of this problem? In other words, when you changed the definition in OBI, how was OBI getting the old definition via IAO? If I were to guess, I would guess that you are planning to have OBI import IAO, and the version with which you were working is set up to do so. Would that be correct, or is there some other source of the problem? I'm just asking in order to gain a better understanding of the sort of problems that can arise and how to resolve them.

**Comment by jamesaoverton** [comment]
Yes, OBI imports all of IAO. See this line near the top of `src/ontology/obi-edit.owl`:

```
<owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/2017-03-24/iao.owl"/>
```

We also run [`robot report`](http://robot.obolibrary.org/report) to check OBI for common mistakes. One common mistake that ROBOT catches is multiple definitions (with the same language). Note that multiple definitions are perfectly fine as far as RDF and OWL are concerned, but we OBO developers have decided that we want to ensure that terms have exactly on English definitions. So we consider this a "mistake".

We could ignore the multiple definitions, and `obi.owl` would work fine with almost all tools. But it's better to fix the problem in IAO.

**Comment by CDowland** [comment]
Thank you! I appreciate your response. I had been looking at the current version (via the IRI on Ontobee) and did not see any imports there, but such an import was the only reason I could think of for this problem.

**Comment by jamesaoverton** [comment]
The editing version of OBI imports BFO classes, RO core relations, and IAO in full, as well as subsets of a number of other OBO ontologies. What you see on Ontobee is a release version of OBI, with all those imports merged into a single standalone file.

**Comment by CDowland** [comment]
That was helpful. Thanks again!

**Comment by bpeters42** [comment]
To summarize status: Jie will create new version of IAO; currently waiting for final version of OMO.

**Comment by zhengj2007** [comment]
The definition has been updated as suggested in the latest IAO release:
http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/OBI_0000011
