### ISSUE TITLE
NTR: pooled clone sequencing

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1106]
Many assays use the output of pooled clone sequencing as controls or input themselves, however these assays do not describe the pooled clone sequencing step. We have some groups that would like to submit their pooled clone sequencing data separately and link these experiments to downstream assays (e.g. STARR-seq). 

There is an existing EFO term for pooled clone sequencing: https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003741

editor preferred term: pooled clone sequencing
alternate terms: 
textual definition: An assay in which DNA is the input molecule derived from pooled clones (for example BACs and Fosmids) is sequenced using high throughput technology.
definition source for the textual definition: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4049660/
logical definition: DNA sequencing assay —> pooled clone sequencing

Thank you for your help!

**Comment by DanBerrios** [comment]
One issue I see @bonitalam is the name of the concept doesn't specify high-throughput sequencing (NGS), but the proposed definition does.  Is this time understood to always require NGS?

**Comment by bonitalam** [comment]
@DanBerrios I see what you mean. You can remove "using high throughput technology." PCE doesn't necessarily need to be done with NGS, although I think that is primarily how it is done now.

**Comment by DanBerrios** [comment]
So this is the situation where we want to import EFO term but with an altered definition.   

editor preferred term: pooled clone sequencing
alternate terms:
textual definition: An assay in which DNA is the input molecule derived from pooled clones (for example BACs and Fosmids) is sequenced.
definition source for the textual definition: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4049660/
logical definition: DNA sequencing assay —> pooled clone sequencing

**Comment by jamesaoverton** [comment]
Please just add the terms to OBI in the usual way. Assays go in the [assays.tsv](https://github.com/obi-ontology/obi/tree/master/src/ontology/templates/assays.tsv) template. There's also a [sequence-analysis.tsv](https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/sequence-analysis.tsv) template for non-assay sequencing terms. You can mention EFO as the definition source or in an editor note, as appropriate.
