### ISSUE TITLE
OBI vs scicrunch for identifiers for sequencers

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1107]
E.g. both systems have IDs for Illumina HiSeq 2500

 * http://purl.obolibrary.org/obo/OBI_0002002
 * https://scicrunch.org/resources/Any/record/nlx_144509-1/SCR_016383/resolver?q=hiseq&l=hiseq

I am part of a community (Genomics Standards Consortium) that is trying to decide which system to use. Some of the criteria they care about:

 - how easy is it for the community to suggest modifications or submit new machines?
 - how easy is it for curators to find entity of relevance
 - is it linked to vendor info
 - is it possible to add sub-entries for particular versions, e.g the software the machine shipped with

@ramonawalls may have other suggestions

I believe there is a robot template system for sequencers, and changes can be suggested on this tracker, so OBI would seem to fit the community aspect (assuming fast OBI release cycle).

IMO OBI offers a lot of advantages in terms of axioms (isa DNA sequencer, manufactured-by illumina), but these don't really provide advantages to GSC.

OBI has links to PDF spec docs

SCR has links to web pages like https://www.illumina.com/systems/sequencing-platforms/hiseq-2500.html it would seem to be useful to have this in OBI.

Whichever IDs GSC uses, it would seem to be useful for OBI and SCR to coordinate and at least cross-reference one another.

cc @wdduncan

**Comment by cmungall** [comment]
As an aside one thing that could be useful is additional axiomatization that includes additional metadata about read-length, error rates, etc (this wouldn't be useful for GSC but may serve other use cases)

**Comment by jamesaoverton** [comment]
While I would like to see devices in OBI (my personal view), and a template would be convenient, I'm worried that OBI developers can't support a huge number of terms with a lot of churn. Do you have a sense of how many terms GSC would need? Or if we could get support?

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2020-02-03. There's strong support for doing this. James and Becky will start working on a template, and try to move some existing device terms into it.

**Comment by turbomam** [comment]
Discussed on 03 February 2020 call. This is an opportunity for OBI to lead/do the job right. We already have good connections with relevant teams, like ENCODE, GSC (MIXS standards), NMDC.

**Comment by zhengj2007** [comment]
Here is the [device design pattern](http://ontorat.hegroup.org/designtemplates/device/pattern_device.jpg) that OBI current use.

**Comment by ramonawalls** [comment]
Great to see this happening. Please let me know if you need input from GSC on the lists of machines to include.

**Comment by jamesaoverton** [comment]
We discussed this on the 2020-02-24 OBI developer call. We're ready to move ahead with #1114, which puts all devices and organizations into ROBOT templates.

@cmungall and @ramonawalls How would GSC submit device terms? If in batches, then we can supply a stripped-down version of the new devices template for them to fill out. If singly, then we will build a GitHub issue template for them to use. In either case, it would be helpful if the submitter(s) have some familiarity with ontologies in general, and ideally with OBI.

**Comment by ramonawalls** [comment]
I think that @only1chunts and I can work with the GSC group to get a list of terms together and submit them as a batch. 

We are still not sure how OBI's terms will relate to the IDs on SciCrunch. Has anyone from OBI reached out to them to coordinate? We hope to avoid duplicate identifiers.

**Comment by jamesaoverton** [comment]
@beckyjackson and I made the devices sheet and merged it (#1114). Can someone else please take the ball on this?

**Comment by cmungall** [comment]
I think this can be closed

 - @ddooley - do you plan to obsolete terms like http://purl.obolibrary.org/obo/GENEPIO_0100128
 - EFO also has sequencers http://www.ebi.ac.uk/efo/EFO_0008566

**Comment by cmungall** [comment]
I note that OBI has axioms like this:

[is_manufactured_by](https://www.ebi.ac.uk/ols4/ontologies/obi/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000304?lang=en)value[Illumina](https://www.ebi.ac.uk/ols4/ontologies/obi/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000759?lang=en)

This is quite useful for tools that generate submission XML for NCBI!
