### ISSUE TITLE
NTRs: assay terms

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1117]
VEuPathDB (https://veupathdb.org) request 51 assay terms using for data annotation and exploration. Most of the terms are related to insecticide resistance and organism identification. The request terms are prepared using OBI assay template. A total of 11 terms, such as device, objective, planned process (technique), are also needed for defining the assays logically.

The terms can be viewed in the google drive:
https://drive.google.com/file/d/1s4PQHAN2PyU0sbQLRCJAUzIqZ7lNoywH/view?usp=sharing
and downloadable from VEuPathDB GitHub site:
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/blob/master/src/ontology/VectorBase_assay/template/VectorBase_Assays.xlsx

**Comment by cstoeckert** [comment]
Discussed on OBI March 9, 2020 call. Will give people a week to review these terms and if no issues then will add assays to assay template and make a pull request.

**Comment by zhengj2007** [comment]
Discussed on OBI March 16, 2020 call. The OBI developers will review the terms especially the middle level assay terms (row 3 - 6, row 39) including:
  - polymerase chain reaction assay
  - restriction fragment length polymorphism assay
  - DNA fingerprinting assay
  - insecticide resistance assay
  - pathogen detection assay

Besides, the terms that are used to define the assays, like devices, objectives and planned process are also worth to discuss in the OBI call.

The OWL generated using ROBOT template command based on submitted assay terms is available:
https://raw.githubusercontent.com/VEuPathDB-ontology/VEuPathDB-ontology/master/src/ontology/VectorBase_assay/VBassay_merged_all.owl
