### ISSUE TITLE
Change label of OBI object property: supplies

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#1120]
Discussed on OBI March 9, 2020 call in context of ROBOT report.
OBI relation 'supplies' http://purl.obolibrary.org/obo/OBI_0000646 has the same label as RO 'supplies' http://purl.obolibrary.org/obo/RO_0002178
OBI's term is about supplying material entities (as a service) whereas RO's term is about anatomy and is a child of connected. We propose changing OBI's label to reflect this distinction.

**Comment by bpeters42** [comment]
Updated label for OBI relation should be: "provisions". 

Updated definition: A relation between an organisation or person and a material entity, where the organization or person provides or supplies the material entity for others to use. 

New editors note: "Prior definition contained reference to transfer of ownership. Removed that reference to make it more readable. (A relation between an organisation or person and a material entity who owned or has license to the material entity and there was a legal transfer of ownership or licensing of the material entity to the current owner).
