### ISSUE TITLE
Terms for 454 sequencers have the same definition

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#1122]
Discussed on March 9,2020 OBI call based on ROBOT report. Duplicate definitions identified for:
http://purl.obolibrary.org/obo/OBI_0000689 454 Genome Sequence 20
http://purl.obolibrary.org/obo/OBI_0000702 454 Genome Sequencer FLX
The definitions should indicate what's different between these sequencers.

**Comment by ddooley** [comment]
Should be in device template.

**Comment by DanBerrios** [comment]
454 Genome Sequence 20 was the first next gen sequencer on the market in 2005.  The 454 GS FLX was produced starting in 2008, with the ability to sequence 400-600 million base pairs per run with 400-500 base pair read lengths.  (Wikipedia)

**Comment by jamesaoverton** [comment]
@DanBerrios Can you please make a Pul Request for your branch/changes?

**Comment by DanBerrios** [comment]
@jamesaoverton  I think I did that already...
