### ISSUE TITLE
Duplicate definitions for inverse properties

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#1123]
Discussed on March 9, 2020 OBI call. Duplicate definitions were identified in the ROBOT report for:
has_specified_output [OBI:0000299] and is_specified_output_of [OBI:0000312]
has_specified_input [OBI:0000293] and is_specified_input_of [OBI:0000295]
Instead of repeating the definition, should just define as the inverse property as in:
has_specified_input is the inverse property of is_specified_input_of

**Comment by ddooley** [comment]
Done in pull request https://github.com/obi-ontology/obi/pull/1406
