### ISSUE TITLE
'gel electrophoresis system' has same definition as parent

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#1125]
'gel electrophoresis system' [OBI:0001121] has same definition as its parent 'electrophoresis system' [OBI:0001053]

**Comment by ddooley** [comment]
Changes I've made in pull #
- moved "agarose gel electrophoresis system" under gel electrophoresis system.
- removed "electrophoresis system" as alternate term from gel electrophoresis system (it is label of parent class).
- changed "gel electrophoresis system" definition to: "An electrophoresis system in which an electric field is applied to a gel matrix"
- changed "pulsed-field gel electrophoresis system" definition to: "A gel electrophoresis system in which the gel matrix is subjected to an electric field that periodically changes direction."

For gel electrophoresis definition, I'm not sure if we want to add "to differentiate macromolecules (DNA, RNA and proteins) and their fragments, based on their size and charge. " as Wikipedia details?
