### ISSUE TITLE
Add synonym 'DNA barcoding assay' (or change primary label) OBI_0001960

### ISSUE THREAD

**Issue by bpeters42** [obi-ontology/obi#1133]
We have an assay OBI_0001960, "taxonomic diversity assessment by targeted gene survey". It seems a simpler label would be 'DNA barcoding assay'. Which contrasts nicely with 'DNA fingerprinting assay' that was recently created.

**Comment by handemcginty** [comment]
'DNA barcoding assay' seems to be confusing for some developers (and maybe users).  Further discussion is needed for better labeling.

**Comment by cstoeckert** [comment]
What came up on the call was that DNA barcoding is also typically used as the name of methods to distinguish different DNA molecules for sequencing (by ligating oligo barcodes to them) which is a different sense of the term from its application to identify different species of organisms.

**Comment by DanBerrios** [comment]
@bpeters42 Can you voice whether you feel strongly that this synonym needs to be added?  Is this a widely used synonym or shorthand for the assay already?  "DNA Barcoding assay" lacks an objective... 
This reference does suggest it has some equivalence ... 
https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/dna-barcoding

**Comment by bpeters42** [comment]
I don't feel strongly, but I think the concern is misplaced. google "DNA barcoding". All of the hits refer to the identification of species, and none relate to barcoding in the sense of de-multiplexing reads in a sequencing experiment. Yes, the word 'barcoding' is used a lot for the later, but I have *never* seen anyone refer to this as a "barcoding assay"

**Comment by ddooley** [comment]
It seems a final decision is required still here!

**Comment by bpeters42** [comment]
As no one seems to share my side of the argument, I take back the suggestion for the namechange, and we should close.
