### ISSUE TITLE
DNA cleavage, restriction analysis - fix label, definition, placement in hierarchy

### ISSUE THREAD

**Issue by bpeters42** [obi-ontology/obi#1134]
- Make child of "specific enzymatic cleavage"
- Change label to "DNA restriction enzyme digestion"
- Change definition to: "A specific enzymatic cleavage of DNA molecules using endonucleases that cleave DNA molecules at specific sites based on the surrounding nucleotide sequence"

**Comment by ddooley** [comment]
I've made the changes, they're on their way to a pull request.  Only issue was that definition source doesn't exist - it was in the past accidentally overwritten by example of use.

**Comment by ddooley** [comment]
Updates are in obi-edit.owl now
