### ISSUE TITLE
Review REO terms for adoption into OBI

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1135]
OBI has used some Reagent Ontology terms, but REO was never actually registered. We should review the list of terms and consider adopting them into OBI.

Repository: https://github.com/tis-lab/reagent-ontology

OBO-level issue: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1042
Previous OBI issue: #1015

@mbrush says:

> The best file to explore if you want to poke around the ontology itself is the pre-reasoned version here. The central hierarchy rooted at the 'reagent' class is what you will want to explore - but it is built only upon running a reasoned over the ontology to collect all classes with a reagent role in one place. This pre-reasoned version is useful because ReO's baroque axiomatization of classes in the ontology make reasoning in Protégé prohibitively slow (at least with the most common Protege reasoner plugins).

We should try to create a `reagents.tsv` ROBOT template. @beckyjackson Please try running your reverse-template code on REO, when you get a chance.

**Comment by mbrush** [comment]
Adding proper link to the pre-reasoned version of the ontology, recommended as starting point for review: https://github.com/tis-lab/reagent-ontology/blob/master/reo/ontology_files/reo_pre-merged_or_reasoned_files/reo_reasoned_9-6-12.owl

**Comment by zhengj2007** [comment]
Current OBI import two REO terms:
http://purl.obolibrary.org/obo/REO_0000171 molecular label role
http://purl.obolibrary.org/obo/REO_0000280 molecular label

Since REO has been removed from ontobee server, run OntoFox, two REO terms are not imported.

**Comment by zhengj2007** [comment]
Discussed on Mar 30th, 2020 OBI call.  @zhengj2007 will add 'molecular label role' and 'molecular label' in OBI and associate the term with this tracker.
