### ISSUE TITLE
NTR: PLAC-seq 

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1145]
Hello, the ENCODE project would like to request a new assay term to be made for some new experiments we are anticipating.

PLAC-seq (proximity ligation-assisted ChIP-seq)

There is an existing EFO term for PLAC-seq (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009981).

**editor preferred term:** PLAC-seq
**alternate terms:** proximity ligation-assisted ChIP-seq
**textual definition:** PLAC-seq is a chromosome conformation capture-based assay in which proximity ligation is conducted in nuclei prior to chromatin shearing and immunoprecipitation. Immunopreciptation with an antibody that targets a transcription factor or histone modification allows for selection and enrichment of specific genomic regions for investigation of long-range chromosomal interactions. 
**definition source for the textual definition**: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5143423/
**logical definition:** chromosome conformation capture assay (OBI:0002439) —> PLAC-seq

**Comment by bpeters42** [comment]
How about switching the preferred term with the alternate term? Very few people will know what PLAC stands for; we can switch it back later? Otherwise this looks great.

**Comment by bonitalam** [comment]
That's fine with me @bpeters42! I don't mind having proximity ligation-assisted ChIP-seq as the preferred term, and PLAC-seq as the alternate term. Thanks for your help.

**Comment by ddooley** [comment]
Discussed. James will do the NTR.
