### ISSUE TITLE
LOINC-inspired clinical assay template for discussion on Monday 13th

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1153]
@handemcginty and I will be discussing clinical assay modelling on Monday April 13th. I'll specifically be discussing the work @cstoeckert and I have been doing, with lots of good input form the community already.

I'll post a link to the ROBOT template before Monday morning.

**Comment by turbomam** [comment]
Here's our latest clinical assay template:

https://github.com/PennTURBO/loinc_in_obo/blob/master/lobo_template_20200413am.csv

**Comment by turbomam** [comment]
@cstoeckert, @jamesaoverton  and I have been working on these tasks:
- place all of these new assays as subClassesOf a new "assay on specimen from organism" class (in the TURBO ontology for now)
    - these assays can be applied to any specimen form any organism, regardless of research vs clinical objectives
    - how to handle new assays that don't take a specimen as the input, like an X-ray?
    - @cstoeckert and I will still need to create some new specimen types and modify our code to make the connections between anatomical entities and specimens
- compare IRI substrings or pre- and post-reasoned ontologies to detect overlap between existing OBI assays and new assays from this module
    - previous plans to check for owl:equivalentClasses won't work because OBI assays are **defined as** subClasses
    - in any case, detecting equivalentClasses with OBI requires several run time flags.

**Comment by linikujp** [comment]
Please check this https://github.com/CIDO-ontology/cido/issues/7 for COVID-19 related specimen.
And I am working on things with FDA EUA PCR tests and mapping to LOINC. We should work together on this. Thanks!

**Comment by linikujp** [comment]
@turbomam I can't access your csv file. Can you please send to my email: 
linikujp@gmail.com? 
I have put some PCR tests in CIDO already. I want to check if we have any overlaps.

**Comment by cstoeckert** [comment]
We are not generating assays based on LOINC due to licensing concerns. Instead we are generating them based on fields in Penn EHR records for lab tests and results.
