### ISSUE TITLE
Recommended revision for "Health Care Provider Role"

### ISSUE THREAD

**Issue by lizumberfield** [obi-ontology/obi#1154]
It is unclear how the role "health care provider role" (OBI_0000207) is different from an identically labeled role (OMRSE_00000012), other than that OBI's is providing healthcare services _during_ a period of investigation. Considering that a "health care provider role" is not realized in an investigative process, please consider:
(a) redefining the text definition of OBI_0000207 to omit the requirement of being involved in an investigation,
(b) obsoleting OBI_0000207 and importing OMRSE_00000012,
(c) relabeling OBI_0000207 to clearly demonstrate how this class is different from _"Liz, the nurse, who bears a health care provider role"_ regardless of ongoing investigations.

_Note: I am similarly submitting an issue to OMRSE, which recommends consideration of OBI_0000207 (which I percieve as having a better parent structure - "worker role" rather than "human health care role")_

**Comment by mbrochhausen** [comment]
Great catch.

I vote for option a).

Best,
Mathias

**Comment by lizumberfield** [comment]
Thanks, Mathias. I agree. 

I'm thinking something along the lines of: "A worker role that inheres in a material entity [specifically Homo sapiens, population, organization] and is realized in a [health care process](OGMS_0000096)"

-Liz

**Comment by johnwjudkins** [comment]
Discussed on 2020-04-27.
Consensus is on replacing the OBI term in favor of the OMRSE term. (Option b). If so, need to decide where it belongs in the hierarchy (not under 'investigation agent role').

**Comment by lizumberfield** [comment]
Just confirming, "replacing the OBI term in favor of the OMRSE term" seems like option A to me -- not B. Can you clarify?

**Comment by johnwjudkins** [comment]
Sorry - by "replacing", I meant deprecating OBI_0000207 and replacing it with OMRSE_00000012. The other participants in last week's OBI dev call agreed.

**Comment by lizumberfield** [comment]
Great. Thank you for clarifying.

**Comment by ddooley** [comment]
Chris will implement pull request.
