### ISSUE TITLE
Problematic terms in new OBI release (2020-04-09)

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1156]
Hello, in the new OBI release (https://raw.githubusercontent.com/obi-ontology/obi/v2020-04-09/obi.owl) we encountered two terms that caused parsing of the OWL file to fail.

As per the release notes, two REO terms were switched to OBI terms:
- REO:0000171 OBI:0002743 molecular label role
- REO:0000280 OBI:0002744 molecular label

However, they still show up in the OWL file without any URIs: 

    

    <owl:Class rdf:about="REO:0000171">
        <rdfs:subClassOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#ObsoleteClass"/>
        <obo:IAO_0000114 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000122"/>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A reagent role inhering in a molecular entity intended to associate with some molecular target to serve as a proxy for the presence, abundance, or location of this target in a detection of molecular label assay.</obo:IAO_0000115>
        <obo:IAO_0000117 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Group: OBI</obo:IAO_0000117>
        <obo:IAO_0000118 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">molecular tracer role</obo:IAO_0000118>
        <obo:IAO_0000119 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">OBI developer call, 3-12-12</obo:IAO_0000119>
        <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/OBI_0002743"/>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">obsolete molecular label role</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
    

    

    <owl:Class rdf:about="REO:0000280">
        <rdfs:subClassOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#ObsoleteClass"/>
        <obo:IAO_0000114 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000122"/>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A molecular reagent intended to associate with some molecular target to serve as a proxy for the presence, abundance, or location of this target in a detection of molecular label assay</obo:IAO_0000115>
        <obo:IAO_0000117 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Group: OBI</obo:IAO_0000117>
        <obo:IAO_0000118 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">molecular tracer</obo:IAO_0000118>
        <obo:IAO_0000119 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">OBI developer call, 3-12-12</obo:IAO_0000119>
        <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/OBI_0002744"/>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">obsolete molecular label</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>

Also, I think REO_0000171 is still used and referred to in OBI_0000140 instead of the replacement term for it, OBI_0002743.

**Comment by jamesaoverton** [comment]
Thanks for catching these problems.

What tool gave you a parsing error?

**Comment by bonitalam** [comment]
We use rdfGraph to parse initially with our own custom script. The error comes up when we try to retrieve term IDs and term names:

https://github.com/ENCODE-DCC/encoded/blob/dev/src/encoded/commands/generate_ontology.py#L823-L831

**Comment by jamesaoverton** [comment]
@beckyjackson will double check my fix, then I'll make a new OBI release.

This problem slipped past all our QC checks. We'll add a lower-level check for our IRIs.

**Comment by jamesaoverton** [comment]
Version 2020-04-23 is up.

Thanks again for finding this problem!

**Comment by bonitalam** [comment]
No problem! Thank you for the quick fix. :)
