### ISSUE TITLE
Add check for bad IRIs

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1158]
#1156 slipped past all our tests. We need a new check to catch bad IRIs.

**Comment by beckyjackson** [comment]
Can we assume that the RDFXML of the OWL will always come from ROBOT? I can write a simple script to just parse this very quickly.

**Comment by jamesaoverton** [comment]
Maybe start with the first column of `build/terms-report.tsv`, then remove everything known good, and see if there's anything left. Even `sed` would work for that, but Python is also fine.

**Comment by beckyjackson** [comment]
I was thinking we could look at the prefixes in the OWL, and then any term that does not start with a prefix is considered invalid. What do you think of that method, or would you prefer using `build/terms-report.tsv`?

**Comment by jamesaoverton** [comment]
That sounds fine.

**Comment by jamesaoverton** [comment]
The PR is good. Now I think I'd like to add a few more checks.

1. I'd like to check that all OBI IDs are seven digits. There's actually one eight digit IRI that I messed up years ago -- see if you can find it!

2. What's Protege's current default for new terms? It used to be the file's base URI then `#` then a hyphenated string: <http://purl.obolibrary.org/obo/obi.owl#my-label>. Although there are exceptions, let's fail if any string starts with "http://purl.obolibrary.org/obo/" and also includes a "#".

3. Please spend a few minutes researching Protege defaults to see if there are other likely problems.

**Comment by beckyjackson** [comment]
That caught the bad IRI - `http://purl.obolibrary.org/obo/OBI_00001975`

Should we just exclude this one from the 7 digit check, and fail otherwise?

**Comment by jamesaoverton** [comment]
Yes, we have to make that one a special case.

**Comment by beckyjackson** [comment]
OK - the PR is updated!
