### ISSUE TITLE
Passaging process

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1170]
During the last OBI call I chaired, we discussed which ontology would be suited for a term about the passaging or subculturing process (as in virus passaging).  MicrO has not responded https://github.com/carrineblank/MicrO/issues/26, but IDO would be interested if OBI isn't https://github.com/infectious-disease-ontology/infectious-disease-ontology/issues/5. I'm following up to see if there's interest in adding such a term to OBI or if another ontology besides these would be more suitable.

**Comment by jamesaoverton** [comment]
Closed by #1177
