### ISSUE TITLE
Specimen terms request 

### ISSUE THREAD

**Issue by linikujp** [obi-ontology/obi#1176]
Below is a list of verbatims copied from the EUA documents with limited redundant check. Those terms include synonyms, alternative terms and acronyms. Please sort it out with correct hierarchies before adding into CIDO. (Originally requested to CIDO https://github.com/CIDO-ontology/cido/issues/7)--- Per @bpeters42 request, I request the terms to be added into OBI. 

Please note the difference between  swab and specimen took using a swab. Swab is a device/tool, you may need to add a specimen for terms ending with swab.

anterior nasal swab
BAL fluid
BAL specimen
BALs
bronchial aspirates
bronchial washings
bronchial washings (BW)
bronchoalveolar lavage
bronchoalveolar lavages (BAL)/bronchial washings (BW)
lower respiratory specimens
lower respiratory tract aspirates
mid turbinate nasal swabs
midturbinate
mid-turbinate
mid-turbinate nasal swab
nasal
nasal aspirates
nasal swab
nasal wash
nasopharyngeal
nasopharyngeal (NP)
nasopharyngeal and oropharyngeal specimens
nasopharyngeal and oropharyngeal swab and bronchoalveolar lavage (BAL) specimen
nasopharyngeal aspirates
nasopharyngeal aspirates (NA)/nasal washings (NW)
nasopharyngeal awash/aspirate or nasal aspirates as well as sputum specimens
nasopharyngeal swab
nasopharyngeal swabs/wash
nasopharyngeal wash
nasopharyngeal wash/aspirates
NP/OP
oropharyngeal (OP)
oropharyngeal (throat) swab
oropharyngeal swabs/throat swabs
saliva specimens
sputum
throat (oropharyngeal) swab
tracheal aspirates
tracheal secretions
upper respiratory specimens
stool specimen
human serum or plasma (EDTA) specimen

**Comment by linikujp** [comment]
Hi, I compared existing OBI terms and my list. 
1. The major terms that are lacking in OBI are: tracheal aspirate specimen, mid-turbinate nasal swab specimen. 
2. Other major issues will be to differentiate the wash and aspirates.
3. Hierarchical terms such as upper respiratory specimen and lower respiratory specimen.  

Will continue studying those, and submit a final excel sheet for new terms submission.

**Comment by linikujp** [comment]
Dear everyone,

Can you recommend any existing relation linking a specimen to the anatomical part where the spwcimen is supposed to be collected? 

Thanks,
Asiyah

**Comment by cstoeckert** [comment]
For the biobank-specimens template (https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/biobank-specimens.tsv) we are using 'derives from' (see Gross Anatomical Part column).

**Comment by linikujp** [comment]
Appreciate your help,  Christ!

**Comment by linikujp** [comment]
Please see attached.
[OBI_new_term_submission_specimen_1176.xlsx](https://github.com/obi-ontology/obi/files/5048187/OBI_new_term_submission_specimen_1176.xlsx)

**Comment by linikujp** [comment]
@jamesaoverton Please let me know if these terms were added or not.

**Comment by jamesaoverton** [comment]
Discussed on the 2020-8-17 call. These look good at a quick glance -- we need someone to do a closer review and make a PR. We'd prefer UBERON over FMA. @jamesaoverton will do this or delegate it.

**Comment by linikujp** [comment]
Thanks! The FMA terms were used because equivalent UBERON terms were not available.

**Comment by jamesaoverton** [comment]
I assigned Apurva to work on this, and reserved the following IDs using the [OBI Term ID Reservation sheet](https://docs.google.com/spreadsheets/d/1tpDrSiO1DlEqkvZjrDSJrMm7OvH9GletljaR-SDeMTI/edit#gid=224833299)

ID | Label
-- | --
OBI:0002778 | tracheal aspirate specimen
OBI:0002779 | mid-turbinate nasal swab specimen
OBI:0002780 | nasal aspirate specimen
OBI:0002781 | lower respiratory tract aspirate specimen
OBI:0002782 | upper respiratory specimen
OBI:0002783 | lower respiratory tract specimen
OBI:0002784 | anterior nasal swab specimen
OBI:0002785 | aspiration specimen collection

**Comment by jamesaoverton** [comment]
OBI does not import from FMA. We plan to use the following UBERON terms instead of the submitted FMA terms:

submitted | replacement
-- | --
FMA_57459 Middle nasal concha | UBERON:0005921 middle nasal concha
FMA_45662 Lower respiratory tract | UBERON:0001558 lower respiratory tract
FMA_45661 Upper respiratory tract | UBERON:0001557 upper respiratory tract

**Comment by linikujp** [comment]
Thank you, James. UBERON is not species specific, right?
What is the solution for human specific anatomical terms? 
Thanks,
Asiyah

**Comment by jamesaoverton** [comment]
OBI uses UBERON, which has XRefs pointing to all sorts of species-specific anatomy ontologies. I don't want to add an FMA dependency at this point.

We've revised some of the definitions to fit OBI patterns. Please take a look and let us know if there are any problems:

**Comment by linikujp** [comment]
@jamesaoverton I checked. It is fine with me. And thanks for the information about UBERON.

**Comment by jamesaoverton** [comment]
Closed by #1231
