### ISSUE TITLE
OBI:epitope

### ISSUE THREAD

**Issue by PhiBabs935** [obi-ontology/obi#1182]
Some of us from the Infectious Disease Ontology team are working updating IDO's coverage of immune response related terms (among other things). 

We were planning on importing OBI's term for _epitope_ (among some other related OBI terms). But I noticed that in its textual definition it is defined as the bearer of an epitope role, whereas there is no such role in OBI. 

_Epitope_ does have the axiom: _bearer of_ some _disposition to be bound by an adaptive receptor_. Referring to that disposition in the textual definition would sound clunky I guess. But if the role mentioned in the definition is intended to be different from the disposition, there should probably be a term created for it. If it wasn't, there may be an (unintended) conflation of roles and dispositions.

**Comment by cstoeckert** [comment]
Discussed on June 22, 2020 call. Textual definition will be updated to reflect logical definition of disposition.

**Comment by PhiBabs935** [comment]
Great thanks for the update!
