### ISSUE TITLE
Term request: 'platelet-poor plasma preparation' and 'platelet-poor plasma'

### ISSUE THREAD

**Issue by dillerm** [obi-ontology/obi#1186]
**label:** platelet-poor plasma preparation
**definition:** A material component separation process in which (1) whole blood is first centrifuged to separate red blood cells from blood plasma, which forms the supernatant, and (2) the blood plasma is then centrifuged to separate platelets from the plasm.
**editor-preferred term:** platelet-poor plasma preparation process

**label:** platelet-poor plasma
**definition:** A blood plasma specimen that is the output of some platelet-poor plasma preparation and is the portion of plasma that contains fewer than 10,000 platelets per microliter.

**Comment by jamesaoverton** [comment]
Discussed on 2020-08-17. @dillerm to add these terms with minor changes:

**label**: platelet-poor plasma preparation process
**parent**: OBI:0600014 material component separation
**action**: add to `src/ontology/obi-edit.owl`

**label**: platelet-poor plasma specimen
**parent**: OBI:0100016 blood plasma specimen
**action**: add to `src/ontology/obi-edit.owl`
