### ISSUE TITLE
Term request: estimated

### ISSUE THREAD

**Issue by reality** [obi-ontology/obi#1189]
Some discussion here https://github.com/pato-ontology/pato/pull/323 . Will open a pull request shortly!

**Comment by jamesaoverton** [comment]
Thanks for the term request and PR. I agree that OBI is the right place to model estimates and approximations.

In OBI/IAO we have created a number of different 'data item' classes, which are all the outputs of different measurement processes (i.e. assays). However we found that we wanted to reuse these classes for more than just measurements: predictions, simulations, settings, etc. So we changed our modelling to focus on 'value specifications', which are neutral with respect to the process that generated them. Here's a good overview: http://obi-ontology.org/docs/data-intro/. We have more detailed, developer-focused documentation if you prefer.

Does this value specification approach fit your use case for estimations and approximations?

**Comment by jamesaoverton** [comment]
I think I addressed the question, but if not, please reopen.
