### ISSUE TITLE
NTR: CUT&RUN assay

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1192]
Hello, we would like to request a term for some new experiment submissions we would to annotate.

**editor preferred term:** Cleavage Under Targets and Release Using Nuclease
**alternate terms:** CUT&RUN
**textual definition:** An in situ chromatin profiling assay in which antibody-targeted controlled cleavage by micrococcal nuclease releases specific protein-DNA complexes into the the supernatant for sequencing. 
**definition source for the textual definition:** https://elifesciences.org/articles/21856
**logical definition:** DNA sequencing assay (OBI:0000626) —> CUT&RUN 

Thank you for your help!

**Comment by bonitalam** [comment]
Hi, I would also like to add another assay to this NTR request as they are similar. 

**editor preferred term:** Cleavage Under Targets and Tagmentation
**alternate terms:** CUT&Tag
**textual definition:** An in situ chromatin profiling assay in which a chromatin protein is bound in situ by a specific antibody, which then tethers to a protein A-Tn5 hyperactive transposase fusion protein (pA-Tn5) loaded with sequence adapters. Activation of pA-Tn5 results in factor-targeted tagmentation, generating fragments ready for PCR enrichment and DNA sequencing.  
**definition source for the textual definition:** https://www.nature.com/articles/s41467-019-09982-5
**logical definition:** DNA sequencing assay (OBI:0000626) —> CUT&Tag

**Comment by mgiglio99** [comment]
Hi @bonitalam 
I'm finally working on these - sorry for the huge delay.
I notice for both of these terms that the definition refers to these as being a type of in situ chromatin profiling assay. However, I don't see an 'in situ chromatin profiling assay' term anywhere in OBI.
Am I missing it? Or is this parent something you feel should be created?
I see that you have a logical def linked to 'DNA sequencing assay' - is that the asserted parent that you want these to have?
If so, then the definitions should read "A type of DNA sequencing in which ....."
Hope I'm making sense.
Also, I'm thinking that the term label should have lower case first letters, but that's something I want to check with the wider group as I'm not sure of OBI's policies on that.
Thanks,
Michelle

**Comment by mgiglio99** [comment]
Hi @bonitalam ,
I've put together a spreadsheet with some drafts of the terms. I made this based on thinking that you likely want 'DNA sequencing assay' to be the parent of these two terms - but if you actually want something different, we will revise accordingly.
https://docs.google.com/spreadsheets/d/1Zq_ScWaTp2U8BS8XYb-ZN1UInP-qEK1sD9fK6ln7w64/edit?usp=sharing
Michelle

**Comment by bonitalam** [comment]
Thanks for the updates @mgiglio99. I did suggest 'DNA sequencing assay' to be the parent of these terms. I don't think an 'in situ chromatin profiling' term needs to be made and your definitions in the spreadsheet look good. Thanks for checking about the capitalization. I just had them capitalized to follow the acronyms and how they were referred to in the papers.

**Comment by mgiglio99** [comment]
Terms and capitalization discussed on June 7, 2021 call.
All approved as in doc linked above.
These will go into the next pull request that I ask for.
(Which should be very soon.)

**Comment by mgiglio99** [comment]
Hi, I should have posted these a long time ago - apologies - here are the term ids that are reserved for the above terms:

OBI:0003033 cleavage under targets and release using nuclease assay
OBI:0003034 cleavage under targets and tagmentation

**Comment by mgiglio99** [comment]
These terms were included in the last release of OBI.
