### ISSUE TITLE
Add specimens from TURBO to OBI

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1197]
The TURBO team has defined some specimens required for our assay templating. 

Can the contents of 
https://github.com/PennTURBO/turbo-ontology/blob/master/ontologies/robot_implementation/more-specimens.tsv

just be added to 
https://github.com/obi-ontology/obi/blob/master/src/ontology/templates/biobank-specimens.tsv ?

**Comment by turbomam** [comment]
If I have requested a new specimen, do I have to additionally add the corresponding anatomical entity (etc.) to something like a OntoAnimals import text file?

**Comment by jamesaoverton** [comment]
Yes, for anatomical entities, please add them to https://github.com/obi-ontology/obi/blob/master/src/ontology/OntoFox_inputs/Uberon_input.txt and then run `make imports`.

**Comment by turbomam** [comment]
@jamesaoverton it looks like I had to manually copy robot.jar into the build directory

**Comment by turbomam** [comment]
@jamesaoverton I have made three commits on the same pull request https://github.com/obi-ontology/obi/pull/1199

sorry, that's probably a pain for you

it looks like Excel saved `src/ontology/templates/biobank-specimens.tsv` with different line endings. let me know if there's something I should do to remedy that.

**Comment by jamesaoverton** [comment]
Multiple commits on a PR is not a problem.

Please run `make sort` to fix the line endings.
