### ISSUE TITLE
derives from semantics for processed specimens?

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1198]
#1197 requests merging a TURBO specimen template into the OBI specimen template.

The TURBO template includes two "enhancements" to specimens currently defined in `obi-edit.owl`

We would like to raise the possibility of OBI asserting a direct 'derives from' relationship between 
- 'blood plasma specimen' and 'blood plasma'
- 'blood serum specimen' and 'blood serum'

That would decrease the number of SPARQL queries required to align specimens from systems like LOINC, that speak in terms of the bare anatomical entity like 'serum'.

Relevant snippet from the TURBO specimens template:

ID | CLASS_TYPE |  C 'processed   specimen' and (is_specified_output_of some 'collecting specimen from   organism') and ('derives from' some %)
-- | -- | --
http://purl.obolibrary.org/obo/OBI_0100016 | subclass | http://purl.obolibrary.org/obo/UBERON_0001969
http://purl.obolibrary.org/obo/OBI_0100017 | subclass | http://purl.obolibrary.org/obo/UBERON_0001977

**Comment by jamesaoverton** [comment]
Breaking apart this conjunction into parts for easier querying might be a good use case for ROBOT [`relax`](http://robot.obolibrary.org/relax) (normally used to relax equivalence axioms to subclass axioms).
