### ISSUE TITLE
NTRs: light source terms

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1200]
Name | Value
-- | --
Label | UV light source
Definition | A light source that provides UV light for use in a distant area using a delivery system.
Parent | OBI_0400065 light source

Name | Value
-- | --
Label | visible light source
Definition | A light source that provides visible light for use in a distant area using a delivery system.
Parent | OBI_0400065 light source

Name | Value
-- | --
Label | solar light source
Definition | A light source that light is produced from solar energy.
Parent | OBI_0400065 light source

The terms are needed by VEuPathDB database. 

Related tracker: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/76

**Comment by johnwjudkins** [comment]
Discussed 2020-10-05. Will add to OBI with "ultraviolet" spelled out. Jie will add to device template.
