### ISSUE TITLE
NTR: Immunoassay process

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1203]
As discussed at noon Eastern time today. I would like to add this soon, in support of a Covid assay that's common at the University of Pennsylvania Healthcare System, but will I wait a few days for community feedback.

label: "Immunoassay process"
subClassOf: "assay"
definition: "An assay that detects the linking of antigens and antibodies via special signaling mechanisms, such as EIA, ELISA, chemiluminescence, etc. that produces one measure (quantitative or qualitative) of the analyte of interest."
Definition source: LOINC User's Guide, Version 2.68, PUBLISHED JUNE 2020, page  47

**Comment by turbomam** [comment]
LOINC indicates that this class would not include flow cytometry or any technique that can determine the localization of an analyte, such as peroxidase immune staining or indirect immunofluorescence (IFA)

**Comment by turbomam** [comment]
Potential label:

Single-measure binding of antibody with reporter to antigen assay

**Comment by jamesaoverton** [comment]
Discussed on the 2020-08-17 call. Bjoern doesn't love "single-measure" but we could not think of something better. @turbomam will go ahead with this.

**Comment by cstoeckert** [comment]
This is in OBI.
