### ISSUE TITLE
OntoFox import terms required by assays from PennTURBO team

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1208]
I am getting ready to add lots of terms to the OBI OntoFox sheets.

There's roughly
- 700 ChEBI terms
- 40 PR terms

Plus the following, whose roles in assays may require some more scrutiny.

IRI | label
-- | --
http://purl.obolibrary.org/obo/DRON_00018971 | adalimumab
http://purl.obolibrary.org/obo/GO_0033130 | acetylcholine receptor binding
http://purl.obolibrary.org/obo/GO_0071735 | IgG immunoglobulin complex
http://purl.obolibrary.org/obo/NCBITaxon_1 | root
http://purl.obolibrary.org/obo/NCBITaxon_131567 | cellular organisms
http://purl.obolibrary.org/obo/NCBITaxon_33317 | Protostomia
http://purl.obolibrary.org/obo/NCBITaxon_33340 | Neoptera
http://purl.obolibrary.org/obo/NCBITaxon_6656 | Arthropoda
http://purl.obolibrary.org/obo/NCBITaxon_7434 | Aculeata <wasps, ants, and bees>
http://purl.obolibrary.org/obo/NCBITaxon_7438 | Vespidae
http://purl.obolibrary.org/obo/NCBITaxon_7439 | Vespinae
http://purl.obolibrary.org/obo/NCBITaxon_7440 | Dolichovespula
http://purl.obolibrary.org/obo/NCBITaxon_7441 | Dolichovespula maculata
http://purl.obolibrary.org/obo/NCBITaxon_7442 | Dolichovespula arenaria
http://purl.obolibrary.org/obo/NCBITaxon_7456 | Polistes
http://purl.obolibrary.org/obo/PATO_0002027 | osmolality
http://purl.obolibrary.org/obo/UO_0000061 | unit of molarity
http://purl.obolibrary.org/obo/UO_0000180 |  
http://purl.obolibrary.org/obo/UO_0000202 | catalytic (activity) concentration unit
http://www.ebi.ac.uk/efo/EFO_0000001 | experimental factor

The required terms were determined with the following SPARQL. The `!strstarts(str(?s), "turbo:")` shouldn't be necessary after switching to OBI IDs. I can clarify more if desired.

The SPARQL query does require one to populate the two named graphs into a RDF triplestore.

```SPARQL
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select 
* 
where {
    graph <https://raw.githubusercontent.com/PennTURBO/turbo-assay-templating/master/pipeline/build/turbo_assays.ttl> {
        ?s a owl:Class .
    }
    filter(isiri(?s))
    filter(!strstarts(str(?s), "turbo:"))
    minus {
        graph <http://purl.obolibrary.org/obo/obi.owl> {
            ?s a owl:Class .
        }
    }
    optional {
        ?s rdfs:label ?l .
    }
}
```

**Comment by turbomam** [comment]
I'll start by just adding these terms to the `[Low level source term URIs]` section.

I have commented them like this
> http://purl.obolibrary.org/obo/PR_000000017 # interferon gamma for TURBO assays

I have entered the UO terms into both

- UO_input_instance.txt
- UO_input.txt

**Comment by turbomam** [comment]
`make all` completed on my laptop. I think reasoning took a little longer... around 15 minutes? (I had a stopwatch running but was on a different screen when the reasoning ended.)

But I don't see my new imports (like http://purl.obolibrary.org/obo/CHEBI_18323 'anserine') in either the OntoFox output or build/obi_merged.owl

I'll push and submit a pull request fo others can see what I did

**Comment by johnwjudkins** [comment]
Discussed on 2020-10-05. Needs discussion with LOINC.

**Comment by cstoeckert** [comment]
Have taken a different approach to generating assays for TURBO needs.
