### ISSUE TITLE
NTRs for arthropod specimen collection

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1217]
The VEuPath team has curated the following terms relating to the capture of insects (and other arthropods) for study, and we think they are a good fit for OBI. They can also be viewed in our latest release. We classify each term as a descendant of either 'device' or 'planned process'.

Label | Definition | Parent
-- | -- | --
arthropod specimen collection by aspiration | A live arthropod specimen collection process that involves the use of an aspirator, a device which draws an arthropod by suction into a container. | adult arthropod specimen collection process
arthropod resting outdoors on artificial support specimen collection by aspiration | An arthropod resting outdoors specimen collection by aspiration that occurs while the arthropod rests on a processed material such as a wall or furniture. | arthropod resting outdoors specimen collection by aspiration
arthropod resting outdoors on natural support specimen collection by aspiration | An arthropod resting outdoors specimen collection by aspiration that occurs while the arthropod rests on an unprocessed material such as a plant. | arthropod resting outdoors specimen collection by aspiration
animal-biting arthropod specimen collection by aspiration | An arthropod specimen collection by aspiration that occurs while the arthropod is biting an animal. | arthropod specimen collection by aspiration
animal-biting outdoor arthropod specimen collection by aspiration | An animal-biting arthropod specimen collection by aspiration that occurs outside a building. | arthropod specimen collection by aspiration
arthropod resting in animal house specimen collection by aspiration | An arthropod specimen collection by aspiration that catches specimens resting inside an animal house. | arthropod specimen collection by aspiration
arthropod resting outdoors specimen collection by aspiration | An animal-biting arthropod specimen collection by aspiration that occurs while the arthropod is resting outside a building during a period of inactivity. | arthropod specimen collection by aspiration
knockdown arthropod specimen collection process | An arthropod specimen collection process that involves exposing arthropods to pesticide, then collecting them once they become dead or immobilized. | arthropod specimen collection process
live arthropod specimen collection process | An arthropod specimen collection process meant to collect live specimens. | arthropod specimen collection process
artificial pit shelter | An arthropod trap, consisting of a pit dug in the ground to provide a space for arthropods to rest and be collected. | resting arthropod trap
baited net trap | An arthropod trap designed to work with an animal (which could be human) inside a netted structure. This structure is designed so that an arthropod, attracted by the animal, can fly into the netted structure but can neither escape nor reach the animal. | arthropod trap
barrier trap | An arthropod trap consisting of a static physical barrier designed to funnel arthropods in flight into a container. | arthropod trap
BG-Sentinel trap | An arthropod trap that is manufactured by Biogents and is designed to attract arthropods through the use of a motorized fan to mimic convection currents produced by a human. The current also pulls arthropods into the trap, where a layer of gauze prevents the arthropods from escaping along with the air current. | arthropod trap
gravid trap | An arthropod trap that is designed to collect gravid female arthropods or their eggs. | arthropod trap
human-biting arthropod specimen collection by aspiration | An arthropod specimen collection by aspiration that occurs while the arthropod is biting a human. | arthropod trap
light trap | An arthropod trap that uses light as an attractant. | arthropod trap
Mosquito Magnet trap | An arthropod trap that is powered by propane and is designed to emit a combination of carbon dioxide, heat, water, and oct-1-en-3-ol attractants while simultaneously using suction to trap arthropods. | arthropod trap
Onderstepoort Veterinary Institute light-suction trap | A light trap that is designed to use motorized suction to trap arthropods in a collection bag once they approach the attractant. The light is supplied by an 8 watt tube, and the fan providing the suction has an 11-centimeter diameter. | arthropod trap
outlet window trap | An arthropod trap that is positioned adjacent to a window of a building and is designed to collect arthropods flying out of the building. | arthropod trap
ovitrap | An arthropod trap that consists of a container holding a mesh layer above water and is designed to trap arthropods hatched from eggs dropped over the water by gravid females. | arthropod trap
resting box trap | An arthropod trap that consists of a box that is open on one end. The placement of the box and modifications to it are done in such a way that it becomes attractive to an arthropod as a place to rest during a period of inactivity. | resting arthropod trap
Shannon trap | A planned process with the objective of collecting a specimen. | arthropod trap
resting arthropod trap | An arthropod trap that is designed to be attractive to an arthropod as a place to rest during a period of inactivity. | arthropod trap
arthropod trap | A device designed to catch arthropods. | device
BG-Counter | A device manufactured by BioGents that is designed to count mosquitoes passing through the device, differentiating the mosquitoes from other arthropods. | device
dipper for arthropod immatures | A device that is designed for the collection of arthropod larvae or pupae from water and has the shape of a ladle or a pan. | device
MosquiTRAP | A gravid trap consisting of an arthropod attractant and adhesive surface. | gravid trap
human-biting indoor arthropod specimen collection by aspiration | An arthropod specimen collection by aspiration that occurs while the arthropod is biting a human inside a building. | human-biting arthropod specimen collection by aspiration
human-biting outdoor arthropod specimen collection by aspiration | An arthropod specimen collection by aspiration designed to catch specimens that are in the process of biting a human outside a building. | human-biting arthropod specimen collection by aspiration
knockdown arthropod specimen collection by pyrethrum spray | A knockdown arthropod specimen collection process in which the pesticide is pyrethrum. | knockdown arthropod specimen collection process
Centers for Disease Control and Prevention light trap | A light trap that is designed to use motorized suction to trap arthropods in a collection bag once they approach the light attractant. This trap is also designed to be lightweight and operate in environments in which electricity may be scarce. | light trap
encephalitis virus surveillance trap | A light trap that uses carbon dioxide as attractant. The trap consists of a container of dry ice with holes in the bottom to allow the carbon dioxide to flow downward into a separate container, in which a motorized fan creates suction to collect arthropods. | light trap
light trap for indoor use | A light trap designed to be placed inside a building. | light trap
light trap for outdoor use | A light trap designed to be placed outside a building. | light trap
New Jersey light trap | A light trap that is designed to use motorized suction to trap arthropods in a collection bag once they approach the light attractant. | light trap
adult arthropod specimen collection process | A live arthropod specimen collection process in which the arthropods are in the adult stage. | live arthropod specimen collection process
aquatic arthropod specimen collection process | An arthropod specimen collection process that has the objective of collecting mosquitoes from an aquatic environment. (Edit: wrong def'n was here)| live arthropod specimen collection process
arthropod specimen collection process | A specimen collection process that has the objective of collecting arthropods as specimens. | planned process
resting bucket | An arthropod trap that consists of a bucket, which is lined with fabric and placed on its side, and a wet cloth inside the bucket. The placement of the box and modifications to it are done in such a way that it becomes attractive to an arthropod as a place to rest during a period of inactivity (not actively seeking a host). | resting arthropod trap
sticky resting bucket | An arthropod trap that consists of a bucket, which is lined with adhesive and placed on its side, and a wet cloth inside the bucket. The placement of the box and modifications to it are done in such a way that it becomes attractive to an arthropod as a place to rest during a period of inactivity. The trap is designed for arthropods to become caught in the adhesive so that they can be collected. | resting arthropod trap
sticky trap | An arthropod trap that is designed to capture arthropods resting on a surface by coating the surface with adhesive. | resting arthropod trap

**Comment by SAK22** [comment]
I think I am happy with these. I will ask the others in the VB team to take a look to be sure.

**Comment by samrund** [comment]
For the first term, why does the parent  have to be <Adult> resting? I'm imagining a imature tick could be aspirated  up?

artificial pit shelters -  do they actually have to be under a plant? Should it be a child of "resting arthropod trap"

resting box trap -   Should it be a child of "resting arthropod trap"?

**Comment by johnwjudkins** [comment]
@samrund I didn't mean to imply that the 1st term refers only to resting arthropods. I agree with your other points.

**Comment by johnwjudkins** [comment]
Discussed on 2020-10-05. Will add devices to device template and create sample collection template - others will fill out other terms that would go into this template.

**Comment by johnwjudkins** [comment]
We should also add (the individual manufacturer) BioGents, an organization that manufactures mosquito traps and other mosquito control products. They make the BG-Sentinel trap and the BG-Counter.

**Comment by johnwjudkins** [comment]
Requesting new column in sample-collection template to include bearer of specimen role through an axiom.
Example for 'arthropod specimen collection process':
`has_specified_output some (Arthropoda and 'has role' some 'specimen role')`

**Comment by jamesaoverton** [comment]
Ok, the column has been added.
