### ISSUE TITLE
has model

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#122]
has\_model

\* Domain: OBI:instrument
\* Range: model \(not yet present in OBI\) 

Related
has serial number

Range: IAO or datatype String

Comment: 
Tackles onomasticon discussions and boarder of Type/instance.

Reported by: DSchober

Original Ticket: "obi/obi-terms/122":https://sourceforge.net/p/obi/obi-terms/122

**Comment by turbomam** [comment]
Closed after discussion on 18. December 2017.  Haven't heard back form original requester.
