### ISSUE TITLE
remote patient assessment

### ISSUE THREAD

**Issue by miseminger** [obi-ontology/obi#1227]
I'd like to submit "remote patient assessment" or "telehealth patient assessment" as a subclass of “performing a clinical assessment” http://purl.obolibrary.org/obo/OBI_0600003.  This term would refer to a clinical assessment performed remotely by technological means (telephone or video).  Thanks!

**Comment by ddooley** [comment]
label: remote patient assessment
parent: performing a clinical assessment
definition: A clinical assessment performed remotely by technological means
definition source: 
example of usage: A telephone or video remote patient assessment conducted between a physician and patient.

I'll get Madeline to lookup def source.

**Comment by zhengj2007** [comment]
@ddooley FYI: guidelines for OBI term annotations, http://obi-ontology.org/page/OBI_term_guidelines

**Comment by miseminger** [comment]
definition source: Calton, B., Abedini, N., & Fratkin, M. (2020). Telemedicine in the Time of Coronavirus. Journal of pain and symptom management, 60(1), e12–e14. https://doi.org/10.1016/j.jpainsymman.2020.03.019  

term editor: Madeline Iseminger (https://orcid.org/0000-0002-0548-891X)

**Comment by ddooley** [comment]
OBI May 2 call: About interviewee who has assistance?

New parent: organism diagnostic process
Revised definition: "An organism diagnostic process which involves a remote assessment of a patient by a clinician."

**Comment by ddooley** [comment]
This has been completed!
