### ISSUE TITLE
Term "Antigen binding" subclass of "molecular function"?

### ISSUE THREAD

**Issue by FuqiX** [obi-ontology/obi#1228]
Hi, 

I was checking the OBI/Process class. I am a bit confused about the position of Term __Antigen binding__ http://purl.obolibrary.org/obo/GO_0003823. 

According to GO, it should be a subclass of Term __Molecular function__ http://purl.obolibrary.org/obo/GO_0003674  rather than a sibling of __Molecular function__. 

I am not sure if this is designed on purpose or should the GO hierarchy be used here?

Thanks for your reply.

Best,
Fuqi

**Comment by jamesaoverton** [comment]
Sorry for the delay. Yes, the GO hierarchy should be used. @beckyjackson please update the GO import to put Antigen binding under Molecular function.
