### ISSUE TITLE
Does OBI want the following sequence assembly datums?

### ISSUE THREAD

**Issue by ddooley** [obi-ontology/obi#1232]
We are deciding where to submit to.  I don't thing SO has anything in the datum department.  If not OBI then we'll put in GenEpiO.

d.

SUBCLASS OF | LABEL | DEFINITION | DEF SOURCE | example of use | Part Of | Exact Synonym@en
-- | -- | -- | -- | -- | -- | --
lab sequencing datum | amino acid sequence start site (user submitted) | The position of the first amino acid in a user-submitted protein (query) sequence. | Emma |   |   | Query Start (aa)
lab sequencing datum | amino acid sequence stop site (user submitted) | The position of the last amino acid in a user-submitted protein (query) sequence. | Emma |   |   | Query Stop (aa)
lab sequencing datum | nucleic acid sequence start site (user submitted) | The position of the first nucleotide in a user-submitted nucleotide (query) sequence. | Emma |   |   | Query Start (nt)
lab sequencing datum | nucleic acid sequence stop site (user submitted) | The position of the last nucelotide in a user-submitted nucleotide (query) sequence. | Emma |   |   | Query Stop (nt)
lab sequencing datum | amino acid sequence start site (reference) | The position of the first amino acid in a protein reference (subject) sequence. | Emma |   |   | Subject Start (aa)
lab sequencing datum | amino acid sequence stop site (reference) | The position of the last amino acid in a protein reference (subject) sequence. | Emma |   |   | Subject Stop (aa)
lab sequencing datum | nucleic acid sequence start site (reference) | The position of the first nucleotide in a nucelotide reference (subject) sequence. | Emma |   |   | Subject Start (nt)
lab sequencing datum | nucleic acid sequence stop site (reference) | The position of the last nucelotide in a nucelotide reference (subject) sequence. | Emma |   |   | Subject Stop (nt)

**Comment by ddooley** [comment]
I'll double check with the SO sequence ontology folks about taking these in, and when closer to finalization, with the protein ontology folks about labels/definitions.  Regardless, Emma could you elaborate on the terms "user submitted" and "reference".  

Part of the challenge in defining these is that an agency's "user submitted" sequence to some repository is at the very same time their own internal reference sequence, especially if they are providing them as a database.  

A second question arose about what "first" and "last" meant.  It seems it has been left implicit in the definitions that the datums are about a sequence of interest and its identified location in a reference genome (from some genomic sequence repository), and one from a laboratory comparing its resulting assembly with the reference in the repository.

**Comment by rvita** [comment]
I suggest rephrasing this way - change 'amino acid sequence start site (reference)' to
'reference protein start site' and definition:
 The position of the first amino acid in a specified reference protein sequence (pending what SO & Darren have to say).

**Comment by griffie** [comment]
Are these labels and definitions better? Thanks, Emma

Subclass of | Label | Definition | Def Source | example of use | Exact Synonym@en
-- | -- | -- | -- | -- | --
lab sequencing datum | input protein sequence start site | The position of the first amino acid in a protein sequence being analyzed (input protein sequence). Also known as the query protein start site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the start sites of proteins are identified by comparing the new sequence to that of a reference sequence in a database. The first amino acid of a protein sequence being analyzed is the input protein sequence start site. | Input Protein Start
lab sequencing datum | input protein sequence stop site | The position of the last amino acid in a protein sequence being analyzed (input protein sequence). Also known as the query protein stop site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the termination sites of proteins are identified by comparing the new sequence to that of a reference sequence in a database. The last amino acid of a protein sequence being analyzed is the input protein sequence stop site. | Input Protein Stop
lab sequencing datum | input gene sequence start site | The position of the first nucleotide in a gene sequence being analyzed (input gene sequence). Also known as the query gene start site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the start sites of genes are identified by comparing the new sequence to that of a reference sequence in a database. The first nucelotide of a gene sequence being analyzed is the input gene sequence start site. | Input Gene Start
lab sequencing datum | input gene sequence stop site | The position of the last nucelotide in a gene sequence being analyzed (input gene sequence). Also known as the query gene stop site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the termination sites of genes are identified by comparing the new sequence to that of a reference sequence in a database. The last nucelotide of a gene sequence being analyzed is the input gene sequence stop site. | Input Gene Stop
lab sequencing datum | reference protein sequence start site | The position of the first amino acid in a reference protein sequence (sequence being used for comparison). Also known as the subject protein start site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the start sites of proteins are identified by comparing the new sequence to that of a reference sequence in a database. The first amino acid of a protein sequence being used for comparison is the reference protein sequence start site. | Reference Protein Start
lab sequencing datum | reference protein sequence stop site | The position of the last amino acid in a reference protein sequence (sequence being used for comparison). Also known as the subject protein stop site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the termination sites of proteins are identified by comparing the new sequence to that of a reference sequence in a database. The last amino acid of a protein sequence used for comparison is the reference protein sequence stop site. | Reference Protein Stop
lab sequencing datum | reference gene sequence start site | The position of the first nucleotide in a reference gene sequence (sequence being used for comparison). Also known as the subject gene start site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the start sites of genes are identified by comparing the new sequence to that of a reference sequence in a database. The first nucelotide of a gene sequence used for comparison is the reference gene sequence start site. | Reference Gene Start
lab sequencing datum | reference gene sequence stop site | The position of the last nucelotide in a reference sequence (sequence being used for comparison). Also known as the subject gene stop site in a BLAST search. | Emma Griffiths | When a new genome is sequenced, the termination sites of genes are identified by comparing the new sequence to that of a reference sequence in a database. The last nucelotide of a gene sequence used for comparison is the reference gene sequence stop site. | Reference Gene Stop

**Comment by ddooley** [comment]
I will add the latest definition revisions to the sequence-analysis.tsv  template, where final edits can be reviewed in a pull request.
