### ISSUE TITLE
Clarify the definition of Cytometer under device/measurement device

### ISSUE THREAD

**Issue by handemcginty** [obi-ontology/obi#1240]
The current definition reads: "A cytometer is an instrument for counting and measuring cells."
We propose to change it to "A cytometer is an instrument for counting and measuring characteristics of cells."

We realized upon new term requests that measuring cells is a bit ambiguous.

**Comment by jamesaoverton** [comment]
Discussed on 2020-11-02. One more improvement would be "A cytometer is an instrument for counting and/or measuring characteristics of cells."

We should also revised the definition of 'cytometry assay' OBI:0001977 to match:

- currently "An assay that measures properties of cells."
- revised "An assay that counts and/or measures characteristics of cells."
