### ISSUE TITLE
"nasal cavity" (UBERON:0001707) has no parent

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#1247]
"nasal cavity" was added to the UBERON import, but it is an "immaterial anatomical entity" and we do not have this as an upper-level term for the UBERON import.

I think there are three options:
1. Add "immaterial anatomical entity" (or "anatomical cavity") as an upper level term
2. Find a new home for "nasal cavity"
3. Replace "nasal cavity" with some material anatomical entity (upon a quick search, I wasn't able to find a good replacement, but I also am not well-versed in the anatomy of the nose 🙂 )

**Comment by bpeters42** [comment]
where are we using it? For nasal swab I presume? That means we should go with 3), and refer to 'content of nasal cavity'. I have had discussions with Chris Mungall that we should create sibling classes for all the 'immmaterial entities' to link to 'content of'

**Comment by beckyjackson** [comment]
It's just for "nasal aspirate specimen".

Would "content of nasal cavity" be a new OBI term? I guess we could actually map it to "nasal cavity", though, because that would require importing "nasal cavity" anyway...

**Comment by bpeters42** [comment]
In my order of happiness: 

a) This to be solved in the Uberon layer, and I would request for each Uberon 'cavity' entry a sibling 'material entity located in cavity' entry. Any suggestion @cmungall has on how realistic that is to get done any time soon would be helpful. It seems like there is agreement on this, but this is touching on very old issues, so it might not happen. I naively think though that this specific proposal (creating separate classes for cavity / content of) has the potential to be least disruptive? 
b) change the design pattern in OBI for these specimens to be sample_of some (located_in some anatomical cavity) 
c) create an OBI placeholder class, to be removed  in the future, of 'material entity and located in cavity

I would love a); b) is realistic and ok; c) is cruel and listed for completeness 

I prefer

**Comment by beckyjackson** [comment]
Here's an option d)

We found "nasal cavity mucosa" in UBERON, which is a material anatomical entity. If we replace "nasal cavity" with this, we won't need to change anything else.
