### ISSUE TITLE
NTR: Illumina MiniSeq sequencing platform

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1249]
Hello, ENCODE would like to request a term for Illumina's MiniSeq sequencing platform. 

NTR: Illumina MiniSeq

* **Alternative terms:** MiniSeq
* **Textual definition:** A small benchtop DNA sequencer which is manufactured by the Illumina corporation with integrated cluster generation, sequencing and data analysis. The sequencer accommodates various flow cell configurations and can produce up to 25M single reads or 50M paired-end reads per run. 
* **Definition source for the textual definition:** https://www.illumina.com/systems/sequencing-platforms/miniseq.html
* **Logical definition (or parent term):** subclass of DNA Sequencer, is_manufactured_by value Illumina
* **Example of usage:** “Whole genome sequencing of Klebsiella pneumoniae ST11 was performed using an Illumina Miniseq Sequencing System.” ([PMID:31493526](https://pubmed.ncbi.nlm.nih.gov/31493526/)) 
* **Term editor:** Bonita Lam (ORCID ID: 0000-0001-9897-3238)

**Comment by handemcginty** [comment]
@mgiglio99 will look into this along with her other interests.

**Comment by mgiglio99** [comment]
Hi,
Here is the reserved term id for this term:

OBI:0003114 Illumina MiniSeq

**Comment by mgiglio99** [comment]
This term was included in the last release of OBI.
