### ISSUE TITLE
NTR: endotracheal tube

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1257]
Definition: A device that is inserted through the mouth or nose into the trachea in order to maintain the necessary gaseous exchange between an organism and its environment.

Source: Wikipedia "Tracheal tube"

Subclass axiom: 'has function' some 'transfer function'
~~(I say material separation because its purpose is to keep the airway from collapsing. I almost suggested 'transfer function', but the tube itself does not bear the function of gas exchange.)~~

This term will provide a defining axiom for another term I requested: #1250 
(necessary for the associated pull request to succeed)

**Comment by zhengj2007** [comment]
Discussed on OBI call 2020-11-23. 

OBI will take the term and expand specimen template, add new column for device. VEuPathDB group will discuss the logical axiom first.

New function associated the 'tracheal tube' need to be added in OBI, such as EUPATH: 'ventilation function'.

**Comment by johnwjudkins** [comment]
Here's my proposal for the function of the endotracheal tube:

Label: respiratory function
Definition: A transfer function to provide gaseous exchange between an organism and its environment.

This definition borrows from the GO term 'respiratory gaseous exchange by respiratory system' (which could be used in a defining axiom as a realization of this function). We could tie the 'ventilation function' to this as well, but I think "ventilation" is less specific in that it could refer to one-way flow.

**Comment by DanBerrios** [comment]
Discussed on OBI call 12/7/20.  Endotracheal tube is part of a ventilation apparatus.
<endotracheal tube> part_of some (bearer-of (has_function respiratory function))
