### ISSUE TITLE
NTR: single-nucleus RNA sequencing assay

### ISSUE THREAD

**Issue by bonitalam** [obi-ontology/obi#1258]
Hello, ENCODE are starting to get submissions of single-nucleus RNA-seq, and we would like to annotate with an official OBI term.

**editor preferred term:** single-nucleus RNA sequencing assay
**alternate terms:** snRNA-seq
**textual definition:** An RNA sequencing assay that uses RNA extracts as input that can be traced to a single nucleus of origin. 
**definition source for the textual definition:** [PMID:24248345](https://pubmed.ncbi.nlm.nih.gov/24248345/), [PMID:32341560](https://pubmed.ncbi.nlm.nih.gov/32341560/) - paper comparing single-cell and single-nucleus RNA-seq methods
**logical definition:** subclass of RNA-seq assay ([OBI:0001271](http://purl.obolibrary.org/obo/OBI_0001271))

**Comment by handemcginty** [comment]
@mgiglio99 will look into this along with other issues she has.

**Comment by bonitalam** [comment]
We no longer need this term, so I am closing this issue.
