### ISSUE TITLE
NTR: fibroblast specimen

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1259]
subClassOf  http://purl.obolibrary.org/obo/OBI_0001468, 'cell specimen'

derives from some fibroblast, http://purl.obolibrary.org/obo/CL_0000057, which is already in OBI

**Comment by DanBerrios** [comment]
Proposed Definition: A cell specimen comprised of a population of fibroblast cells.
Superclass: Cell specimen

Perhaps subclasses would/could indicate anatomical source.
