### ISSUE TITLE
NTR: "chorionic villi sample - blood" and "fibroblasts - blood"

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1260]
I'm putting these potential terms up for discussion here, although I haven't prepared logical definitions yet.

There are a decent number of lab results in our EHR for which the specimen is "[chorionic villi](https://en.wikipedia.org/wiki/Chorionic_villi) sample - blood": ~ 3000 for a sample of 40 patients, compared to ~ 100k for blood and ~ 15k for NA.

I think there are also "chorionic villi sample - fibroblast" specimens in the EHR, too (just not for this patient subset).

In addition to talking about the semantics of these terms, I'd be delighted if any of the clinically-oriented people in our group could say what these specimens really are and what they're good for. I see them matched up with just about the same analytes that are associated with plain blood specimens. Casual Googling hasn't led me anywhere useful yet. I may also talk to some clinicians here at Penn.

**Comment by turbomam** [comment]
Thanks for the great discussion. I think @cstoeckert and I are going to put this on hold until we have more evidence that iur collaborators would actually search over "chorionic villi sample - blood" specimens when building cohorts.

**Comment by cstoeckert** [comment]
This issue arose from the TURBO project which has not ended up needing these terms. Can reopen if that changes.
