### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1271]
There are roughly 10 branches that have my initials (mam) in the name. I think all of them have either been pulled into master or the pull request has been closed by mutual agreement.

Is there any reason I shouldn't delete those branches?

**Comment by jamesaoverton** [comment]
Please go ahead. If your branch is marked Merged or Closed then it should be safe to delete. If it's marked Open or Draft then don't delete. If there's a "New pull request" button then the branch was never turned into a PR, and you need to be more careful.

**Comment by jamesaoverton** [comment]
I just went through and deleted a bunch.

**Comment by turbomam** [comment]
Thanks. I deleted some more.
