### ISSUE TITLE
Add ID annotations to OBI?

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1272]
Why doesn't OBI have ID annotations (http://www.geneontology.org/formats/oboInOwl#id) like PR, CHEBI, GO, etc.?

**Comment by jamesaoverton** [comment]
I might not be understanding the question. All those ontologies are written (i.e. edited) in the legacy `.obo` format and converted to `.owl`. OBI has always been written in `.owl` and we convert to `.obo` to support legacy tools.

**Comment by turbomam** [comment]
That seems like a good explanation for why they have oboInOwl:id annotations for thier terms. 

I would find it handy to have the same kind of annotations in OBI. When I make lookup tables, I usually use CURIEs instead of full IRIs, since they take up less space. Being able to run SPARQL queries over the textual IDs saves me the step of creating IDs from IRIs with something like `'s|http://purl.obolibrary.org/obo/OBI_|OBI:'`

**Comment by jamesaoverton** [comment]
I would prefer not to add those to `obi.owl` on the grounds that they add more bytes to the file without adding any information. As you say, the transformation is trivial. If you need more power, [`robot export`](http://robot.obolibrary.org/export) lets you create tables from an ontology with full control over the output of labels, CURIEs, or IRIs.

**Comment by turbomam** [comment]
OK, I'll try `robot export`
