### ISSUE TITLE
Revise equivalency axiom for 'count'

### ISSUE THREAD

**Issue by APCox** [obi-ontology/obi#1275]
'count' is currently asserted as a subclass of 'measurement datum', but its equivalency axiom is:

     'data item' and (is_specified_output_of some counting)

This results in the term appearing twice in the hierarchy. While the axiom is technically not incorrect, it isn't as specific as it could be. Hence I propose changing the equivalency axiom to:

     'measurement datum' and (is_specified_output_of some counting)

Also, given that the elucidation is identical to the definition, the elucidation can be safely deleted.

**Comment by johnwjudkins** [comment]
Discussed 2021-04-05. Count is not always a measurement datum; the equivalency axiom is created as it is for safety. Recommend either APOLLO_SV makes the change in its hierarchy or let OBI have 'count'.

**Comment by jamesaoverton** [comment]
'count' is http://purl.obolibrary.org/obo/APOLLO_SV_00000032 right?

I don't think any change is required, but if so the change would have to be made in APOLLO_SV. If I'm mistaken, please reopen.
