### ISSUE TITLE
'longitude coordinate measurement datum' and 'latitude coordinate measurement datum'

### ISSUE THREAD

**Issue by PhiBabs935** [obi-ontology/obi#1277]
Was hoping for a clarification about the terms 'longitude coordinate measurement datum' and 'latitude coordinate measurement datum'.

As noted in their annotations, these terms are tied to 'Specimen Collection Location - Latitude' and 'Specimen Collection Location - Longitude' of the DMID Metadata Standards Core Sample [https://www.niaid.nih.gov/research/dmid-metadata-standards-core-sample].

Clarification, are the OBI terms only intended to strictly apply to longitude and latitude coordinate measurements of specimen collection sites? Or is it left open to apply more broadly? The former seems to be implied by the OBI terms being annotated with 'alternative term': 'Specimen Collection Location - Latitude' and 'Specimen Collection Location - Longitude'. 

On the other hand, the textual definitions given for these terms are broad enough that they do not explicitly exclude the latter interpretation (the descriptions for the corresponding DMID terms at the link above do exclude such an interpretation, e.g. 'Latitude coordinate for the site of the specimen collection event.')

I also ask because the Influenza Ontology has two related terms that I am looking to replace with terms from a higher ontology, or move up to a higher ontology. Namely, 

'collection longitude GPS' = The GPS longitude coordinate where the sample was collected.
'collection latitude GPS' = The GPS latitude coordinate where the sample was collected.

If the OBI term is intended to apply only to specimen/sample collection sites, then I can obsolete these in favor of the OBI classes.

**Comment by cstoeckert** [comment]
Jie and I created these terms as part of the NIAID metadata standards group. The intent is for them to be general and not only for specimen collection. The annotation "NIAID GSCID-BRC alternative term:Specimen Collection Location - Latitude" is to facilitate connecting fields in that standard to ontology terms and in this case a more general term.

**Comment by johnwjudkins** [comment]
@PhiBabs935 Go ahead with the new terms and we can close this item.
