### ISSUE TITLE
misspelling in specimen collection device's class expression?

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1282]
I just pulled master and saw this in `src/ontology/templates/devices.tsv`

> OBI:0002814     specimen collection device      specimen collection device      ready for release               A container used to collect a specimen. Container and 'has roll' some 'specimen collection container role'                              https://orcid.org/0000-0002-8844-9165                                   device

specifically: 'has roll' 

Probably somebody's already working on it in another branch, but I'll err on the side of caution and note it here.

I'm mentioning @jamesaoverton and @ddooley 
Let me know if you want me to remove you. Also, I wouldn't be offended it you did it yourself.

**Comment by ddooley** [comment]
Thanks for catching that. It was accidentally left in definition.
