### ISSUE TITLE
Terms to move from FLU to OBI

### ISSUE THREAD

**Issue by PhiBabs935** [obi-ontology/obi#1286]
Hi, below are some Influenza Ontology terms that I was wondering if OBI would like to adopt. This is part of a project to revive FLU, while replacing/moving terms that should be defined elsewhere. Note that the definitions presented here are from a developmental version of FLU, not the last 2015 release version on Bioportal and Ontobee. 

subclass of | label | Definition | Definition Source | Axiom | Note
-- | -- | -- | -- | -- | --
worker role | nucleotide   sequencer role | Worker role realized by a person   that is involved in determining the order of the nucleotides in a nucleic   acid sequence. | Partially modelled on on the   definition for OBI's nucleic acid sequencer | realized in SOME sequencing assay |  
worker role | extractor role | Worker role that is realized by   a person who separates the desired component of an input material from the   remainder. | Definition is modeled upon OBI's   extraction. | realized in SOME extraction |  
time measurement datum | extraction   date | Time measurement datum that   specifies when some material was extracted from an input material. | Definition is modeled upon   EUPATH's DNA extraction date. |   |  
time measurement datum | extraction   time | Time measurement datum that is   the result of measuring the duration of an extraction process. | Meredith Keybl, Shane Babcock |   |  
postal address | laboratory   address | Postal address used as a   directive to deliver something to a laboratory. |   |   |  
specimen   collection time measurement datum | specimen collection time post   disease onset | A specimen collection time   measurement datum that is the measure of a time when specimens are collected   after the onset of disease in a host. | GROUP:FLU, Shane Babcock |   | Originally submitted to EUPATH.   Chris Stoeckert suggested submitting this and EUPATH's 'specimen collection   time post infection' to OBI.
specimen   collection time measurement datum | specimen   collection time post infection                      [EUPATH term] | A specimen collection time   measurement datum that is the measure of a time when specimens are collected   after an infection starts. | EuPathDB |   | term editor: John Judkins

**Comment by cstoeckert** [comment]
Discussed on Feb. 8, 2021. Concern with creating worker roles for every process that is done. Note that there are a couple worker roles like these but not clear we want to proliferate these. These worker roles need to be discussed further. 
Time measurement datums are OK to put into OBI. Note that extraction time should be extraction duration time to distinguish from what time the extraction occurred. 
Raised point of having start and stop of processes for these processes to discuss further.

**Comment by PhiBabs935** [comment]
Thanks. The original FLU developers I am in consultation with have already expressed that we do not need to try and keep every term. So I am not wedded to keeping everything. If the OBI community is of the view that the worker roles terms are unneeded, we can always just obsolete them from FLU.

Agreed on the label change for 'extraction time'

**Comment by cstoeckert** [comment]
Looks like this issue has been addressed.
