### ISSUE TITLE
NTR: blood meal host organism and related data items

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#1288]
As described in https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/116, VEuPathDB needs 4 new terms:
prevalence of pathogen - data item
blood meal host organism - organism with role 'blood meal source role'
presence of blood meal host organism - data item (boolean)
prevalence of blood meal host organism (e.g., % of mosquitoes that have human blood as a meal) - data item
Should these be included in OBI or in VEuPathDB ontology?

**Comment by cstoeckert** [comment]
Discussed on OBI call Feb. 8, 2021. Agree that these all belong in OBI. There is some relation to immune exposure terms although capturing different targets so should coordinate.

**Comment by cstoeckert** [comment]
Also adding 'blood meal source role' from VEuPathDB ontology since needed for 'blood meal host organism'

editor preferred term: prevalence of pathogen in specimens
alternate terms: prevalence of pathogen
textual definition: A data item that is the frequency of detection of a specified pathogenic organism in collected specimens. 
example of usage: prevalence of Plasmodium falciparum in Mosquito samples assayed by PCR
definition source for the textual definition: VEuPathDB
logical definition: subclass of data item

editor preferred term: prevalence of blood meal specimens from a host organism
alternate terms: host blood index
textual definition: A data item that is the frequency of blood whose source is from a specified host organism in collected blood meal specimens.
example of usage: prevalence of blood meal host organism in specimens measured as % of blood meal specimens collected from mosquitoes that had human blood as a meal.
definition source for the textual definition: VEuPathDB
logical definition: subclass of data item

editor preferred term: presence of blood from host organism in blood meal specimen
alternate terms: presence of blood meal host organism
textual definition: A data item that indicates whether blood in a blood meal specimen came from a specified host organism.
example of usage: presence of blood meal host organism indicated by boolean values of yes or no.
definition source for the textual definition: VEuPathDB
logical definition: subclass of data item

editor preferred term: blood meal source organism
alternate terms: blood meal host organism
textual definition: An organism that is the source of a blood meal. 
example of usage: 
definition source for the textual definition: VEuPathDB
logical definition: subclass of  organism and realizes some ‘blood meal source role' 

editor preferred term: blood meal source role
alternate terms: 
textual definition: A role borne by an organism that is gained during a process in which another organism ingests blood as food from the organism.
example of usage: A mosquito feeds on a human whereby the human acquires the blood host role for the mosquito blood meal.
definition source for the textual definition: http://purl.obolibrary.org/obo/EUPATH_0000791
logical definition: subclass of role

**Comment by SAK22** [comment]
@cstoeckert I am happy with these, will confirm with Bob in case I have missed anything.

**Comment by cstoeckert** [comment]
Thanks!

**Comment by cstoeckert** [comment]
@bpeters42 do these work for you in light of work on immune exposure terms?

**Comment by johnwjudkins** [comment]
Discussed 2021-03-01. Hector will review w/i next 2 weeks.

**Comment by hectorguzor** [comment]
After going over the terms with @bpeters42 it was determined that these aren't relevant to immune exposure terms.

**Comment by cstoeckert** [comment]
editor preferred term: blood meal source organism
alternate terms: blood meal host organism
textual definition: An organism that is the source of a blood meal.
example of usage:
definition source for the textual definition: VEuPathDB
logical definition: subclass of organism and realizes some ‘blood meal source role'
-> subclass of organism and 'has role' some ‘blood meal source role'
