### ISSUE TITLE
file merge (OBI:0002566) has axioms that are more specific than label/def suggests

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1294]
id: OBI:0002566
name: file merge
def: "A data transformation in which data contained in 2 or more files are merged into a single file." []
is_a: OBI:0200000 ! data transformation
relationship: OBI:0000293 OBI:0000973 ! has_specified_input sequence data

why is the specific input sequence data?

**Comment by mgiglio99** [comment]
Hi @cmungall 
This was discussed on the April 19 call. There was agreement that the sequence data axiom should be dropped.
You could go ahead and make the change at your convenience.
Assigning this one to you.
Thanks

**Comment by cmungall** [comment]
sorry not sure I will have time for this. I recommend on future calls you have Protege open with a PR for all trivial fixes and deal with them during the call
