### ISSUE TITLE
NTRs: additional arthropod collection terms

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1302]
Label | Definition | Parent
-- | -- | --
'arthropod attractor role' | A role of a material entity realized in drawing an arthropod in the direction of the material. | role
'arthropod collection process with automated identification' | An arthropod specimen collection process that involves a device that produces data specifying the types of arthropod collected. | 'arthropod specimen collection process'
'gravid female arthropod specimen collection process' | An arthropod specimen collection process that has the objective of collecting gravid female arthropods. | 'arthropod specimen collection process'
'resting flight-capable arthropod specimen collection process' | An arthropod specimen collection process that occurs while an arthropod that is capable of flight is resting outdoors during a period of inactivity. | 'arthropod specimen collection process'
'daytime arthropod specimen collection by aspiration' | An arthropod specimen collection by aspiration that occurs in the daytime. | 'arthropod specimen collection by aspiration'
'arthropod resting in human house specimen collection by aspiration' | An arthropod specimen collection by aspiration that catches specimens resting inside a human house. | 'arthropod specimen collection by aspiration'
'landing arthropod specimen collection process' | An arthropod specimen collection process that occurs while the arthropods land on a surface. | 'adult arthropod specimen collection process'
'flying adult arthropod collection process by passive interception' | An adult arthropod specimen collection process that has the objective of collecting arthropods capable of flight, through the use of a barrier trap. | 'adult arthropod specimen collection process'
'device for resting of adult arthropods for collection' | A device that is designed to provide a solid surface that is attractive to an arthropod as a place to rest during a period of inactivity. | device
'well net for arthropod immatures' | A device that is designed for the collection of arthropod larvae or pupae from water and consists of a conical net. | device
'arthropod trap containing small non-human animal bait' | An arthropod trap that uses as attractant an animal that is not human and is the size of a chicken or smaller. | 'arthropod trap'
'trap for emerging adult arthropods' | An arthropod trap that is designed to trap an arthropod as it emerges from water at the beginning of its adult stage. | 'arthropod trap'

**Comment by zhengj2007** [comment]
Discussed on March 22nd, 2021 OBI call. No objection to add the terms in OBI.

**Comment by jamesaoverton** [comment]
Closed by #1317
