### ISSUE TITLE
enzymatic activity assay NTR

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1303]
Label: Enzymatic activity level assay

Definition: an assay in which the activity (not abundance) of any enzyme is determined? measured?

Examples: ALT
vs measuring ATP levels with luciferase, in which an enzyme is a reagent

Parent class: assay

see also #1304

**Comment by cstoeckert** [comment]
Propose going for a very general definition:
"An assay in which the activity of an enzyme is determined."

**Comment by jamesaoverton** [comment]
Discussed with the CEBS team on 2022-04-20. This is our suggestion:

Label: enzymatic activity assay
Definition: An assay in which the activity of an enzyme is determined.
Parent class: assay
Target Entity: catalytic activity (for lack of a more specific 'enzyme activity')

**Comment by mgiglio99** [comment]
Discussed on April 25th call.
Decided to make slight changes.
label to: enzymatic activity level assay
definition to: An assay in which the level of catalytic activity of an enzyme is determined.

**Comment by jamesaoverton** [comment]
In reviewing PR #1572 we noticed that 'insecticide resistance by detecting enzyme activity assay' is somehow related. These could maybe use the new 'enzyme activity level assay' as a detection technique. Not a high priority.
