### ISSUE TITLE
new term requests receptor repertoire sequencing 

### ISSUE THREAD

**Issue by rvita** [obi-ontology/obi#1307]
2 new terms requested for HIPC:
editor preferred term: T cell receptor repertoire sequencing assay
alternate terms:  TCR repertoire sequencing assay 
textual definition: A sequencing assay that determines the sequences of DNA or RNA molecules that encode the repertoire of T cell receptors within an input sample. 
definition source for the textual definition:  Rosati, E., Dowds, C.M., Liaskou, E. et al. Overview of methodologies for T-cell receptor repertoire analysis. BMC Biotechnol 17, 61 (2017). https://doi.org/10.1186/s12896-017-0379-9
logical definition: subclass of sequencing assay (OBI:0600047)

editor preferred term:  B cell receptor repertoire sequencing assay
alternate terms:  BCR repertoire sequencing assay; Antibody repertoire sequencing assay
textual definition: A sequencing assay that determines the sequence of a DNA or RNA molecules that encode the repertoire of B cell receptors within an input sample. 
definition source for the textual definition: Rosati, E., Dowds, C.M., Liaskou, E. et al. Overview of methodologies for T-cell receptor repertoire analysis. BMC Biotechnol 17, 61 (2017). https://doi.org/10.1186/s12896-017-0379-9
logical definition: subclass of sequencing assay (OBI:0600047)

**Comment by jamesaoverton** [comment]
@rvita These terms have been added to OBI with these IDs:

| Term ID | Label | 
| --- | --- |
OBI:0002990 | T cell receptor repertoire sequencing assay
OBI:0002991 | B cell receptor repertoire sequencing assay
