### ISSUE TITLE
Device setting

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#133]
Assigned to Bjoern to account for the specification part

Device\_setting inheres\_in some device and is concretisation of some \(device\_setting\_specification and is\_about a quality of the device\)

Device\_setting – directly under dependent continuants Editornote: this may be a quality although who knows?
Examples, 300V for 4 hours, 200mvolts, 37degrees.A knob set a 300 V is the device setting, the protocol stating to set the instrument to 300V is a device setting specification

Reported by: fgibson_sf

Original Ticket: "obi/obi-terms/133":https://sourceforge.net/p/obi/obi-terms/133

**Comment by turbomam** [comment]
Term has been created as a quality, will close after 18. December 2017 discussion. 

Mark: add a reference to this discussion in obi.owl (development version)

Not a top priority right now, possibly revisit the issue of whether this is a quality after making more progress with assays?
