### ISSUE TITLE
Assess Eagle-i Resource Ontology terms (ERO)

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1332]
ERO has is officially no longer actively developed:

https://github.com/OBOFoundry/OBOFoundry.github.io/issues/909#issuecomment-816298651

When ERO was being built, ERO developers were an active part of OBI development. The scope or ERO and OBI overlap -- I'm not 100% clear on how much they overlap. Are there terms that OBI should adopt from ERO or coin anew in OBI?

These are the steps I propose:

1. a quick analysis of what's in ERO
2. a query of how ERO is used by other OBO ontologies as represented in Ontobee
3. ask OBO Discuss who is using ERO and what for

Hopefully this would give use a solid sense of what ERO terms are most valuable. Then we could try an group them and try to line them up with OBI branches or templates.

I am chronically over-tasked, so I don't expect to get to this any time soon. Help would be appreciated.

**Comment by mgiglio99** [comment]
All - leave a comment here with sets of terms that you think are worth salvaging.

**Comment by johnwjudkins** [comment]
immunoassay http://purl.obolibrary.org/obo/ERO_0001362

**Comment by cstoeckert** [comment]
Discussed on May 10, 2021 call. Very broad term that may be useful for manufacturers but maybe not for researchers. Maybe use more specific terms like  enzyme-linked immunosorbent assay instead. Consensus is that there is not a strong case for this.

**Comment by johnwjudkins** [comment]
'patient screening' http://purl.obolibrary.org/obo/ERO_0000722

It is defined as an assay and has the context of an investigation.

**Comment by johnwjudkins** [comment]
Discussed on 2021-09-20. ERO 'patient screening' term may be too broad.

**Comment by linikujp** [comment]
Confirm that "patient screening" is very broad. If search google using "patient screening", there are multiple situations doing screening of patients: 1. clinical trial, 2. research study, 3. general cancer preventive screening, 4. screening a patient to see if fits for a surgical procedure, or even 5. the COVID-19 screening tests.

**Comment by hectorguzor** [comment]
This PR has been open for a long time now. I will go ahead and close it.  If there are other terms that OBI should adopt from ERO we can reopen this issue and discuss those terms.
