### ISSUE TITLE
Clean up some unparsed triple errors

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1336]
These are probably harmless but ugly. @beckyjackson can you please look into this when you have time?

```
2021-04-23 16:55:03,052 ERROR org.obolibrary.robot.IOHelper - Input ontology contains 3 triple(s) that could not be parsed:
- <http://purl.obolibrary.org/obo/OBI_0000979> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147501962.
- <http://purl.obolibrary.org/obo/OBI_0000998> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147501963.
- <http://purl.obolibrary.org/obo/OBI_0000958> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147501961.
```

**Comment by jamesaoverton** [comment]
Discussed on 2021-05-10. These three terms are:

- <http://purl.obolibrary.org/obo/OBI_0000979> ambidexterous
- <http://purl.obolibrary.org/obo/OBI_0000998> left handed
- <http://purl.obolibrary.org/obo/OBI_0000958> right handed

The problem are the `rdf:type` axioms like this, which you would read as "'is about' some 'ambidextrous handedness'":

```
        <rdf:type>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000219"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/PATO_0002204"/>
            </owl:Restriction>
        </rdf:type>
```

OWLAPI is not happy about this, so these axiom don't show up in OLS or Ontobee.

I suggest just dropping these axioms.

**Comment by cstoeckert** [comment]
DIscussed on May 10, 2021 and agree with removing problematic restrictions.
