### ISSUE TITLE
Write a script to relabel a term

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#1341]
Currently, if you want to update the label of a term, you need to check for all its usages in templates. It would be useful to have a script that does this automatically, e.g.:
```
src/scripts/relabel.py OBI:0000070 test
```

... where arg 1 is the ID of the term you're relabeling and arg 2 is the new label. The script will look for the term's old label and replace all usages of that.

**Comment by jamesaoverton** [comment]
I would like to accept the old label and not just the old ID.

In #1340 I mentioned that it would also be nice to be able to locate usages. If you end up doing something like that in this script, please also update the locate script.
