### ISSUE TITLE
comments from Robert H.

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#135]
Below a copy of an email Robert sent with comments on OBI end of december. I started replying, but meant to finish after the OBI meeting - some items had already been cleaned up and others were on the agenda for the branches.

Copied here so as to not loose them. 

Melanie

Hi Melanie,

I have some remarks about OBI laying around. I wanted to revise and
verify them and send you a real text, but I won't have time to do
this before I go on vacation. So I just send you my notes, in the hope
that you find them useful. Each paragraph starts with the OBI class I
looked at when writing a comment. They are not ordered by importance,
and some comments are probably just wrong.
If you have questions, let me know, also if you cannot decipher my
notes and need a real text :\) I will not be on vacation for another
week and can still answer emails.

Have a great Christmas,
Rob.

OBI Ontology notes
\------------------

remarks

\[RH\]enzyme: has-part some protein -&gt; enzyme
disjunction+complete definition problem; I have part some protein, but
I am no enzyme
formal def. does not coincide with def-label

entity of organismal origin -&gt; artifact object
not clear to me; subclass e.g. "chimera"; not sure if there are
natural chimeras...

\[MC\]Biomaterial branch.
We had the discussion regarding the fact that chimeras can be natural. In our case, entity of organismal origin \(EOO\) is a defined class, meant to represent every biomaterial that derived from organism and is output of a material transformation. So it would cover "artificial chimeras" but not the natural ones. 
It is a recurring problem in the biomaterial branch.

\[RH\]population as subclass of artifact seems wrong: selection of a bunch
of organisms for an experiment does not make the group an artifact,
the group was there before it was selected; in particular, being
selected is a role played by this group

\[MC\]yes.

\[RH\]EBV-transformed B-Cell: should probably refer to EBV instead of
"Viruses" \(plural?\), because it is completely defined

\[MC\]The viruses plural comes from NCBI taxonomy that we "mireot" \(i.e. light import\) in. So we keep their label.
You are right for the EBV, we should get that one specifically instead of using Viruses in general.

\[RH\]person -&gt; Eucaryota: should probably be human -&gt; Eucaryote, person
seems like a legal term

\[MC\]We did update that recently.
We changed the label to homo sapiens, with alternative term natural person, and an editor note reading: "Was changed from person to homo sapiens and alternative term: ''natural 
person', definition &amp;quot;This is a common offshore legal term meaning a living 
breathing person as opposed to an unnatural person such as a corporation&amp;quot; 
Source: Alan Ruttenberg: 
http://www.google.com/search?client=safari&amp;amp;rls=en&amp;amp;q=define%3Anatural+person&amp;amp;ie=UTF-8&amp;amp;oe=UTF-8"

\[RH\]Organism: hasrole some ...; why? organsims that lived thousands of
years ago, did they have a role? What about organisms living now, but
that are not investigated \(and may be extinct tomorrow, and never
investigated in the future\)?
still don't understand BFO's roles

\[MC\]Yes, Alan pointed out the same issue \(specifically that his cat, though being an organism, would never be specimen\).
We did remove these restrictions. 
I am also confused with BFO roles, but we decided to use them with their context. So a cat that would be subject for an experiment could have the specimen role, but not cats in general.
Barry said he is working \(with others\) on clarifying roles, functions and dispositions in BFO, so hopefully we will have a clear answer soon.

\[RH\]historically \(not\) part: why does it say in def that this is a role
when it is subclass of quality?

\[MC\]We need to clean that whole hierarchy up. Several terms had been added under role/qualities. They were first under role \(thus the definition\), then have been moved under qualities. 
If you look at them they are all what we call "conferred qualities", i.e. qualities resulting from a process. For example ligated is a "quality" of a material that is specified output of a ligation.
I think those should be replaced with defined classes, for example we would have "ligated material", but this needs to be discussed. Some OBI-ans said they would like to have the adjective standing on its own somewhere \(i.e. having only ligated\). 
I'm thinking giving it a try on one example, asking for feedback from the consortium and see if the defined class solution is acceptable.

\[RH\]relational quality of continuant: qualities of multiple entities
\(relations\); example left-of, right-of; how do I find out in how many
entities the quality must inhere? in the left-of example, assume that
it is 3 arguments: two entities and a third specifying the observer;
how do I distinguish between the left, the right, and the observer
entity? Should be roles within the relation? -&gt; not in BFO; probably
PATO related question

\[MC\]I'm not sure I'm following you. If I have 3 entities in a row: 1 2 3.
1 is right-of 2, 2 is left-of 1
I think the relational qualities are always between 2 entities, and there is no observer.

\[RH\]dead: quality of what? only potentially living things, e.g., organism
and cell; but organism are \(text-def\) defined as living; still
organism when "dead"?

\[MC\]I was suggesting to move dead under disposition, but again disposition of what. Latest proposal was having a defined class "alive material" which would have the disposition "dead".
Again, Barry asked us to keep it on hold while BFO clarifies the dispositions definition.
organisms include dead ones, we discussed this during one of our last calls: http://groups.google.com/group/obi-biomaterial/browse\_thread/thread/efba8b0b4d4887d2?hl=en.
We should modify the text definition.

\[RH\]disease -&gt; disposition; difference between having a disease and
disposition to get a disease; discussion required for disease;
probably realized by process;

\[MC\]disease is under disposition, and disease course is under process.
I had a very similar question 2 weeks ago: http://groups.google.com/group/obi-biomaterial/browse\_thread/thread/8862f803c2bb10cf?hl=en

Bjoern replied: "Briefly:  The disease disposition inheres only in those humans / mice or
whatever that have some kind of physical disorder. For cancer that would
e.g. be to have some mutated cells that replicate abnormally. Those
cells could still be destroyed by immune mechanisms before any
clinically observable disease occurs. The disease course is the process
realization of the disposition, and is what I think you will want to
refer to. This would be something like:

blood derived\_from \(mouse bears cancer realized in disease course\) "

\[RH\]drug role: what are the relations between the chemical and the role
and the organisation assigning the role? ; probably other role-related
BFO question

def: Drug role is a role assigned to an entity by a regulatory agency that is designed to diagnose, treat or prevent an abnormal medical condition   

\[MC\]We recently added regulatory agency under biomaterial:  A regulatory agency is a organization that has responsibility over the legislation \(acts and regulations\) for a given sector of the government. 
We should probably have an approval process, and then the chemical would bear the drug role when it is specified output of an approval process.

\[RH\]placebo role -&gt; def. refers to substance \(because it "does not
contain..."\); should distinguish role from substance playing the role
same for several roles; maybe problem of CDISC defs.

\[MC\]Yes - I will forward to the role branch.

\[RH\]regulatory role; def looks like process def. -&gt; BFO role discussion

\[MC\]Not sure about that one. The regulatory role is realized during the approval process, but the organization bears the role.

\[RH\]biological specimen role + organism: every organism plays this role
\(or some other investigation role\), according to organism def, but
there are \(certainly\) organisms which are not under investigation;
study-role result of specimen-role subclass study-participant-role

\[MC\]These have been removed for the reasons you mention.

\[RH\]study participant role: many sub-classes can be roles played outside
of a study, or be discovered as result of study

\[MC\]This is currently being cleaned - the role branch has been working with the PlanAndPlannedProcess branch to define properly terms like study, investigation, protocol etc.

\[RH\]function: defs look like goal-specifications; what is difference \(or
relation\) to objective-specifications?

\[MC\]The objective specification is something that a process realizes as part of a plan.
The function is the inherent utility of an entity.

For example, a data transformation has an objective of normalizing data. A centrifuge has the function of centrifugating. 

Though you are right in your observation, and it has been decided that the PlanAndPlannedProcess branch would take care of the function branch, the idea being that a function is canonically realized in a process. There is currently a defined class "canonical realization of device function", the idea being that the function could be automatically derived from the process.

\[RH\]causality assessment: def says, it is a role, but it is not according
to formal def

\[MC\] a class I didn't know :\)
I'm afraid I don't understand what you mean, maybe it has been modified recently.

\[RH\]digital quality vs. digital entity: difference, why entity subclass
quality?

\[MC\]digital quality is the term chosen by Barry in IAO. The editor note reads:  Need to rework digital entity. Digital quality was suggested by Barry. 
This is an are that hasn't been worked on yet on the IAO side.

\[RH\]intraperitoneal injection: no idea what this is, completely defined;
still seems too strong: same as superclass, just utilizes device
"syringe"; does not state that syringe is used for injection, could be
used for different purpose; due to complete def, would still be
classified as injection; due to complete def. of class "injection":
should state that stuff is administered using the syringe, not that
process utilizes a syringe \(can use it for many different things\)

\[MC\]The subtlety here is that with the relation utilizes\_device the device realizes its function. In the case of a syringe, it would realize the injection function.
Though checking on the relation definition this is not obvious. We had a similar issue with has\_input and has\_output, and we replaced them with has\_specified\_input and has\_specified\_output, to make it clear that not everything present at the beginning of the process is input, but only those that are relevant to the plan.
I will add to the agenda for the relation branch.

\[RH\]clinical diagnosis: input: patient, output: diagnosis; strange use of
material transformation, patient transformed\_into diagnosis?

\[MC\]It may have been modified since you looked at it. Some of the restrictions had been changed just before latest release, and it messed up a bit things with the process branch. These have been repaired in the meanwhile. Clinical diagnosis is now classifying under objective driven process, and outputs data \(diagnosis\). At the end, it should classify under assay \(input material and outputs data\)

\[RH\]group assignment: input: population, output: 2 groups of organism?
what is transformed into what? In "reality", some organisms stand on
the grass or whereever; don't change after division in 2 groups, but
their role in the study changes \(or is being created\)

concentrate: label of class could be "concentration"?

\[MC\]probably - will forward to process branch.

\[RH\]staining: complete def.; but what about proesses which use as input
already stained things, and have as output the same things? should
have as input some non-stained entity, as output a stained one; or use
partial def instead of complete

\[RH\]data transformation: sub-classes defined using has\_objective; what
about processes with an objective which is not realized? process with
object of data averaging, but failed, is it still data averging
process?

\[RH\]relations:
is\_about: uses part\_of information artifact in def; can IAs have
parts? What mereological axioms hold?

\[RH\]denotation: defined using "pointing to"; axioms required for "pointing
to" \(at least\)

\[RH\]represents, describes: no def, not clear

\[RH\]results\_from: no def

\[RH\]Summary:
\- completely defined classes problematic \(as usual\), should be
reviewed, see whether both directions of def hold
\- BFO roles still not clear to me
\- use of relational qualities not clear to me \(must check with PATO\)
\- check out Info Artifact Ont
\- check relation defs in RO

Reported by: mcourtot

Original Ticket: "obi/obi-terms/135":https://sourceforge.net/p/obi/obi-terms/135

**Comment by turbomam** [comment]
bump
@cstoeckert will catch up in 2017/2018

**Comment by hectorguzor** [comment]
Discussed on OBI Call 2023-03-20: Sorry much time has passed, if there are still issues please add them to a new issue tracker item. We will go ahead and close this for now. Thanks.
