### ISSUE TITLE
medical device

### ISSUE THREAD

**Issue by rvita** [obi-ontology/obi#1356]
OGMS wants to import 'device' from OBI http://purl.obolibrary.org/obo/OBI_0000968
but wants OBI to consider creating a defined class for "medical device" being a better level to be relevant for OGMS
Note that the same device can be used in both a medical setting and in other nonmedical settings.
https://github.com/OGMS/ogms/issues/160

**Comment by hectorguzor** [comment]
Discussed on OBI call 2021-06-14: OBI prefers to not create 'medical device' and recommends OGMS to import 'device'.
