### ISSUE TITLE
NTR: coma severity assay

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1357]
Definition: An assay that has the objective to determine the severity of coma in a patient.
Parent: [physical examination of individual](http://purl.obolibrary.org/obo/OBI_0002441)
I'm submitting this as a general term for an assay that has a coma scale as an output, such as the [Blantyre](https://en.wikipedia.org/wiki/Blantyre_coma_scale) or [Glasgow](https://en.wikipedia.org/wiki/Paediatric_Glasgow_Coma_Scale) coma scale.

**Comment by hectorguzor** [comment]
discussed on 2021-06-14: def= A physical examination of individual that has the objective to determine the severity of coma in a patient.

examples of usage:  examining a patient and grading their coma status on the Blantyre or Glasgow coma scale.
