### ISSUE TITLE
Consider removing "SPLIT" from Parent columns

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1359]
OBI has been pretty consistent about only allowing one asserted parent term, but our ROBOT templates do allow more than one by specifying a "SPLIT" in the ROBOT template string.

I don't remember why we do with with the ROBOT templates. Maybe there were exceptions we wanted to handle?

**Comment by hectorguzor** [comment]
There are 3 templates that specify a "SPLIT" in the parent class column: `assays.tsv`, `sample-collection.tsv` and `devises.tsv`. The "SPLIT" can be removed from `assays.tsv` and `sample-collection.tsv` without changes to obi.owl. There only appears to be one term in `devises.tsv` that has two asserted parent terms ("protective apron" in row 391).

**Comment by ddooley** [comment]
Can do.  It can remain under "personal protective clothing item".  Can one attach it as subclass of apron via an equivalency axiom though in the devices.tsv table? I'm not seeing a column for the equiv. axiom.

**Comment by jamesaoverton** [comment]
I guess we never needed it before, but it's fine to add a new column, like the "additional axioms" of the assays template.

**Comment by hectorguzor** [comment]
If we move 'apron' to the "associated axioms" column and keep 'personal protective clothing item' as the asserted parent, 'protective apron' still appears as a subclass of both in obi.owl.

**Comment by hectorguzor** [comment]
Discussed on OBI call 2021-06-14: recommend keeping under 'protective apron'. 'apron' does not seem necessary as a grouping class. We propose to make 'apron' obsolete.
