### ISSUE TITLE
'pathogen detection assay' should be child of 'organism identification assay'

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1360]
Currently, these two are siblings. But 'pathogen detection assay' is equivalent to 

assay
 and (has_specified_output some ('is about' some pathogen))
 and (achieves_planned_objective some 'detection of pathogenic organisms objective')

so should be under 'organism identification assay'.
(Perhaps the label should also be changed to 'pathogen organism detection assay' for clarity.)

**Comment by hectorguzor** [comment]
Discussed on OBI call 2021-06-14: keep label the same, and make parent 'organism identification assay'.  Change the definition to "an organism identification assay that aims to detect pathogens".
