### ISSUE TITLE
Discussed on the call 10/19: To clearly differentiate from STATO term and make OBI specific, the relationship label should be tightened to be 'is experimental model output for', and the domain being 'measurement datum'

### ISSUE THREAD

**Issue by jdowens-commit** [obi-ontology/obi#1362]
Discussed on the call 10/19: To clearly differentiate from STATO term and make OBI specific, the relationship label should be tightened to be 'is experimental model output for', and the domain being 'measurement datum'

_Originally posted by @bpeters42 in https://github.com/obi-ontology/obi/issues/1234#issuecomment-712303406_

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2021-08-30. We would prefer to keep the discussion in #1234.
