### ISSUE TITLE
NTRs for 3D neuron morphology determination assays

### ISSUE THREAD

**Issue by patrick-lloyd-ray** [obi-ontology/obi#1364]
Following discussion with @hectorguzor, I'd like to submit the following NTRs: https://docs.google.com/spreadsheets/d/1Nc6rZwuUvNtrv4GOQBMckNmXggWhM9_lHJKD1r8xe_E/edit?usp=sharing

Any comments, suggestions, revisions, and the like are welcome.

**Comment by hectorguzor** [comment]
Discussed in OBI call 2021-08-16: Consider putting neuron assays under 'cytometry assay' as inferred classes. Patrick and Hector will discuss this as they work on the PR.
