### ISSUE TITLE
western blot assay questions

### ISSUE THREAD

**Issue by mgiglio99** [obi-ontology/obi#1365]
Hello,
Some questions related to existing Western blot terms:

1. Why is the term label for OBI:0000854 'western blot analysis' instead of 'western blot assay' when it is a term in the assay branch?
2. Shouldn't there be a linkage between OBI:0001669 'far-Western blot assay' and 'western blot analysis' ('western blot assay'). It seems that far-Western should be a child of western (inferred child?). Currently OBI:0001669 is a child of 'binding assay' OBI:0001146. And related to this, should OBI:0000854 'western blot analysis (assay)' be linked to 'binding assay' OBI:0001146?
3. Small note: "western" should not be capitalized in OBI:0001669.

Thanks,
Michelle

**Comment by mgiglio99** [comment]
Discussed at June 7, 2021 call.
Regarding:
1. consensus is to change to "assay"
2. Will connect 'far-western blot assay' to 'western blot assay' via 'far-western bot assay' will have detection_technique as 'western blot assay'
3. western will always be lower-cased

@cstoeckert Does the above look correct? 
(I couldn't capture the notes right after the call as I had back-to-back meetings all day today - so I'm afraid I'm remembering wrong.)
Thanks!

**Comment by cstoeckert** [comment]
Yes, you captured what we discussed and agreed on. Thanks @mgiglio99 !
