### ISSUE TITLE
NTR: laboratory-based population

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#1370]
This term is requested for the VEuPathDB project and will be imported into the VEuPathDB ontology once available. This will be used instead of MIRO_30000033 as MIRO is inactive.
Thanks,
Chris

editor preferred term: laboratory-based population
textual definition: A population where the collection of individuals is located and maintained in a laboratory, research, or production facility.
definition source for the textual definition: VEuPathDB
logical definition: subclass of ‘population’

**Comment by jake-emerson** [comment]
Would this fit as a research resource ID (https://scicrunch.org/resources)?

**Comment by cstoeckert** [comment]
@jake-emerson If you mean, are some of these laboratory-based populations available to be shared and could be given a resource ID, then yes.
