### ISSUE TITLE
Request to import OGMS 'clinical laboratory test'

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1379]
VEuPath imports [clinical laboratory test](http://purl.obolibrary.org/obo/OGMS_0000056) as a parent to [blood test](http://purl.obolibrary.org/obo/EUPATH_0011795) and similar terms we are submitting to OBI in #1322. This allows terms like 'blood test' to include not only analyte assays but also the counting of cells in a specimen.

**Comment by zhengj2007** [comment]
@johnwjudkins Can we close it?

**Comment by johnwjudkins** [comment]
Closing. 'blood assay' and similar terms are children of 'assay'. The proposed change is not necessary.
