### ISSUE TITLE
NGRL testing technologies

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#138]
Hi,

Below some testing technology terms used by the National Genetics Reference Laboratories. Could be useful for OBI. SNOMED mapping included.

Cheers
Tomasz

\----

Amplification Refractory Mutation System \(ARMS\)	
382111000000104 | Amplification refractory mutation system assay \(procedure\)

CF common mutation test kit \(an ARMS test\)
382241000000108 | Cystic fibrosis 20 common mutation test kit \(procedure\)

Analysis of 29 mutations using the Elucigene CF29 kit \(an ARMS test\)
382251000000106 | Cystic fibrosis 29 common mutation test kit \(procedure\)

Conformation sensitive capillary electrophoresis \(CSCE\)
382261000000109 | Conformation sensitive capillary electrophoresis \(procedure\)

Denaturing gradient gel electrophoresis \(DGGE\)
382351000000103 | Denaturing gradient gel electrophoresis \(procedure\)

Denaturing high performance liquid chromatography \(dHPLC\)
382611000000109 | Denaturing high performance liquid chromatography \(procedure\)

Heteroduplex analysis
382741000000102 | Heteroduplex analysis \(procedure\)

Loss of heterozygosity analysis
382751000000104 | Loss of heterozygosity analysis \(procedure\)

Meta polymerase chain reaction assa \(Meta-PCR\)
382871000000103 | Meta polymerase chain reaction assay \(procedure\)

Multiplex ligation-dependent probe amplification \(MLPA\)
382801000000106 | Multiplex ligation dependent probe amplification \(procedure\)

Mutagenically separated PCR \(MS-PCR\)
383001000000109 | Mutagenically separated polymerase chain reaction analysis \(procedure\)

Multiplex PCR	383041000000107
Multiplex polymerase chain reaction analysis \(procedure\)

PCR Polyacrylamide Gel Electrophoresis \(PCR-PAGE\)
252326002 | Polyacrylamide gel electrophoresis \(procedure\)

Protein Trucation Test \(PTT\)	
383221000000105 | Protein truncation test \(procedure\)

Sanger sequencing	
382791000000107 | Chain termination sequencing \(procedure\) + synonym

The SNPlex™ Genotyping System from ABI
383231000000107 | Single nucleotide polymorphism genotyping system \(procedure\).

Single strand conformation polymorphism analysis \(SSCP\)
383241000000103 | Single strand conformation polymorphism analysis \(procedure\)

Single strand conformation polymorphism and heteroduplex analysis \(Heteroduplex/SSCP\)
383251000000100 | Single strand conformation polymorphism and heteroduplex analysis \(procedure\)

Pyrosequencing™ \(Sequencing by synthesis\)
383261000000102 | Pyrosequencing \(procedure\)

Real Time PCR
383191000000103 | Real time polymerase chain reaction \(procedure\)

Quantitative PCR \(qPCR\)
383211000000104 | Quantitative polymerase chain reaction \(procedure\)

Quantitative Fluorescence PCR \(QF-PCR\)
383271000000109 | Quantitative fluorescence polymerase chain reaction analysis \(procedure\)

Melting curve analysis
383181000000100 | Melting curve analysis \(procedure\)

Digital PCR
383311000000109 | Digital polymerase chain reaction analysis \(procedure\)

Reverse transcription PCR \(RT-PCR\)
383141000000108 | Reverse transcriptase polymerase chain reaction \(procedure\)

Oligo Ligation Assay \(OLA\)
382231000000104 | Oligonucleotide ligation assay \(procedure\)

Service levels:

Sequencing of entire coding region
Definition: Determination of the nature and order of the nucleotide bases of the gene being tested.	
383361000000106 | Sequencing of entire coding region \(procedure\)

Sequencing of selected exons
Definition: Determination of the nature and order of the nucleotide bases of specific exons of a gene.
383391000000100 | Sequencing of exon of gene \(procedure\)

Mutation Scanning
Definition: The analysis of DNA by one of a variety of methods to identify regions of a gene that may contain a sequence variant.	
synonym of 118117001 | Gene mutation analysis \(procedure\)

Targeted Mutation Analysis
Definition: Testing for the presence of specific commonly occurring mutations found in most, or a high proportion of, individuals with a specified disease.
383401000000102 | Targeted mutation analysis \(procedure\)

Testing for known mutations in family members  
Definition: Testing of at-risk family members for their family-specific \(private\) mutation.	
383411000000100 | Testing for known mutation in family member \(procedure\)

Gene Tracking
Definition: Testing DNA sequence polymorphisms \(normal variants\) that are near or within the gene of interest to track the inheritance of a disease-
causing \(pathogenic\) mutation within a family.
383421000000106 | Gene tracking \(procedure\)

Copy number analysis \(or dosage analysis\)	
Definition: Testing specific genes where large deletions or duplications \(extending over one or several exons\) are known to be pathogenic, or determination of the proportion of mutant mitochondria \(heteroplasmy\) in patients affected with disorders that are caused by
383431000000108 | Gene copy number analysis \(procedure\)

Reported by: tadamusiak

Original Ticket: "obi/obi-terms/138":https://sourceforge.net/p/obi/obi-terms/138

**Comment by turbomam** [comment]
Closing after 18. December 2017 discussion.  Can reopen if terms become necessary in any use case.  Names and definitions present, would need to identify parent classes.
