### ISSUE TITLE
Question about "fluorescence detection assay" logic

### ISSUE THREAD

**Issue by hectorguzor** [obi-ontology/obi#1403]
Hi everyone, 

In looking into the logic of "fluorescence detection assay" it was noticed that under the output column it has ('material entity' and ('bearer of' some fluorescence)). In https://academic.oup.com/database/article/doi/10.1093/database/baab040/6318069 it specifies that assays are modeled to have some 'measurement datum' as an output. Given that many assays use 'fluorescence detection assay' as a detention technique, I wanted to verify if this is correct. 

Thanks.

**Comment by jamesaoverton** [comment]
I'm confident that `'material entity' and ('bearer of' some fluorescence)` was only meant to be in the "input" column and not in the "output" column. So please just remove `'material entity' and ('bearer of' some fluorescence)` from the output column for all the fluorescence assays.
