### ISSUE TITLE
NTR for IEDB: binding datum and assays 

### ISSUE THREAD

**Issue by hectorguzor** [obi-ontology/obi#1416]
The IEDB team is requesting the following terms to better organize 'binding datum':

**categorical binding datum**
_textual definition_: A binding datum about two or more material entities to form a complex that is expressed as a categorical value. 
_editor preferred term_: qualitative binding datum
_logical definition_:  subclass of = binding datum and 'has value specification' some 'categorical value specification' 

**quantitative binding datum**
_textual definition_: A binding datum about two or more material entities to form a complex that is expressed using numbers.
_logical definition_: subclass of = binding datum 

we are also requesting the following assays:

**assay measuring quantitative binding of a MHC:ligand complex**
_textual definition_: An assay that detects the binding of a MHC molecule with a ligand, and produces a quantitative measurement of the binding as an output. 
_logical definition_: subclass of = assay 
_target entity_ = 'MHC protein complex binding to ligand' 
_output_ = 'quantitative binding datum' 

**assay measuring quantitative binding of a antigen:antibody complex**
_textual definition_: An assay that detects the binding of an antigen with an antibody and produces a quantitative measurement of the binding as an output. 
_logical definition_: subclass of = assay
_target entity_ = 'immunoglobulin binding to epitope'
_output_ = 'quantitative binding datum'

**assay measuring quantitative binding of a epitope:MHC:TCR complex** 
_textual definition_: An assay that detects the binding of a MHC:epitope complex with a T cell receptor, and produces a quantitative measurement of the binding as an output.
_logical definition_: subclass = assay 
_target entity_ = 'MHC:epitope complex binding to TCR'
_output_ = 'quantitative binding datum'

**Comment by hectorguzor** [comment]
Also requesting the following two quantitative binding datum terms:

**EC50 binding datum**
_textual definition_: A quantitative binding datum that is expressed as a half-maximal effective concentration (EC50).
_logical definition_:   equivalent to = quantitative binding datum and ((half maximal effective concentration (EC50)) and ('is about' some binding))

**IC50 binding datum**
_textual definition_: A quantitative binding datum that is expressed as a half-maximal inhibitory concentration (IC50).
_logical definition_: equivalent to = quantitative binding datum and ((half maximal inhibitory concentration (IC50)) and ('is about' some binding))

**Comment by bpeters42** [comment]
A few edits in the below:

categorical binding datum
textual definition: A binding datum that is expressed as a categorical value.
editor preferred term: qualitative binding datum
logical definition: subclass of = binding datum and 'has value specification' some 'categorical value specification'

quantitative binding datum
textual definition: A binding datum that is expressed using numbers.
logical definition: subclass of = binding datum

we are also requesting the following assays:

assay measuring quantitative binding of a MHC:ligand complex
textual definition: An assay that detects the binding of a MHC molecule with a ligand, and produces a quantitative measurement of the binding as an output.
logical definition: subclass of = assay
target entity = 'MHC protein complex binding to ligand'
output = 'quantitative binding datum'

assay measuring quantitative binding of an antigen:antibody complex
textual definition: An assay that detects the binding of an antigen with an antibody and produces a quantitative measurement of the binding as an output.
logical definition: subclass of = assay
target entity = 'immunoglobulin binding to epitope'
output = 'quantitative binding datum'

assay measuring quantitative binding of an epitope:MHC:TCR complex
textual definition: An assay that detects the binding of a MHC:epitope complex with a T cell receptor, and produces a quantitative measurement of the binding as an output.
logical definition: subclass = assay
target entity = 'MHC:epitope complex binding to TCR'
output = 'quantitative binding datum'

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2021-09-27:

1. Does the pattern used here overlap with 'blood assay datum'? #1428 We should lay out our pattern and consult with the UPenn group.
2. Should (more of) these be under 'value specification'? It would be good to conserve the old 'binding datum' term, which a lot of our immune essays depend upon. We are linking 'categorical binding datum' to "'has value specification' some 'categorical value specification'". But maybe there's a better way to do this.

**Comment by jamesaoverton** [comment]
Discussed on OBI call 2021-10-04.

Answering (2): These binding datum terms can be used in predictions (for example), so they are not 'measurement datum's. On the other hand, they are **about** binding. Value specifications are not **about** anything, so these binding datums are not value specifications.

Regarding (1) we discussed this some more, and the whole situation is even messier than James remembered. Bjoern's opinion is that we will have to refactor all of this to clean it up properly, and that we shouldn't keep tripping ourselves up about it each time.

**Comment by jdowens-commit** [comment]
Sorry to inconvenience everyone but, what do this mean for me. I will love some one to inform me before closing and cleaning up.  I need to live for my children and I am going to ask for help from you  all.
