### ISSUE TITLE
NTR: blood assay datum

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1428]
VEuPath needs terms for the data items resulting from assays like 'blood assay' and 'urine assay' (to be parent to more specific assay result terms). So I propose:

Label: 'blood assay datum'
Definition: A measurement datum that is the specified output of a blood assay.
Equivalent axiom: 'measurement datum' and is_specified_output_of some 'blood assay'.

**Comment by jamesaoverton** [comment]
I can see that this is a useful term. I have three concerns

1. would we need a value-specification version of this, for predictions or settings?
2. would we need additional terms for other assays, such as 'blood microbiology assay datum'?
3. would we need additional terms for other specimen types, such as 'arterial blood assay datum'?

The concern is the cost of parallel hierarchies. If multiple groups are using a few high-ish level terms like this, then there are clear benefits to precomposing.

**Comment by johnwjudkins** [comment]
Discussed on 2021-09-20. This is meant to cover measurements on blood specimens, not microbiology test results. A better label could be 'blood measurement datum' etc.

**Comment by johnwjudkins** [comment]
To answer one of the concerns: I intended in the original post to only introduce '(specimen type) assay datum' terms, but microbiology data terms would also be useful. This is an outline with my suggestions of example terms, their parents, and defining axioms. I would include more specimen types besides blood & feces. VEuPath requires data terms for detection of individual species in specimens and parents for them like 'bacteria in blood datum'. I think the parent terms are broad enough to go in OBI.

label | parent | subclass axiom
-- | -- | --
blood assay datum | data item | is_specified_output_of some 'blood assay'
feces assay datum | data item | is_specified_output_of some 'feces assay'
feces microbiology datum | organism identification datum | is_specified_output_of some 'feces microbiology assay'
blood microbiology datum | organism identification datum | is_specified_output_of some 'blood microbiology assay'
bacteria in blood datum | blood microbiology datum | 'is about' some Bacteria
virus in blood datum | blood microbiology datum | 'is about' some Virus
eukaryota in blood datum | blood microbiology datum | 'is about' some Eukaryota

'bacteria in blood datum' would be a datum about some type of bacteria detected in a blood specimen.

**Comment by jamesaoverton** [comment]
Discussed on OBI call 2021-10-04: We tried to harmonize with #1416 but got stuck. The consensus on the call is that we should not get stuck on this -- it will all have to get fixed properly later. We should just push ahead with these.
