### ISSUE TITLE
NTR: Laboratory

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1436]
OBIB team is requesting the term, 'laboratory'

Label: laboratory
Textual definition: An organization that performs research, provides services, or processes materials.
Definition source: eagle-i resource ontology
Parent: organization

Related trackers: 
https://github.com/biobanking/biobanking/issues/83
https://github.com/obi-ontology/obi/issues/408

**Comment by johnwjudkins** [comment]
Discussed 2021-10-18. Not necessarily research organization. Need to elaborate on "services". Suggested definitions: An organization that develops or uses technologies to advance human understanding, An organization that performs assays, processes specimens, analyses data and similar services. May need related facility term. May want 'biomedical laboratory' as label. Will discuss with OBIB to improve definition. Children of this term in OBIB are helpful in improving definition: http://www.ontobee.org/ontology/OBIB?iri=http://vivoweb.org/ontology/core%23Laboratory

**Comment by cstoeckert** [comment]
Laboratories included in OBIB are ones which acquire, evaluate, and characterize tissues including analyzing components such as DNA/RNA. Of the proposed definitions from the 2021-10-18 OBI call, this one fits best: "An organization that performs assays, processes specimens, analyses data and similar services." Biomedical laboratory would be an appropriate label. 
Alternatively, could have a more specific "tissue laboratory" which is "An organization which acquires, evaluates, and/or characterizes tissues including analyzing components such as DNA/RNA."

**Comment by DanBerrios** [comment]
OBI proposes:

Label: Biomedical laboratory
Textual definition: An organization that performs biomedical assays, processes biospecimens, analyses biomedical data and conducts similar planned processes.
Definition source: OBIB
Parent: organization

Discussed possibility of adding class axioms but will defer that at this time.

**Comment by mbrochhausen** [comment]
may I suggested having the restriction to biomedical being reflected in the label?

**Comment by cstoeckert** [comment]
Here's a counter proposal from OBIB:
An organization that performs assays, processes specimens, analyses data and conducts planned processes relevant to the life sciences.

**Comment by wdduncan** [comment]
Should this be a subclass of ENVO's [laboratory facility](https://ontobee.org/ontology/ENVO?iri=http://purl.obolibrary.org/obo/ENVO_01001406)?

**Comment by wdduncan** [comment]
Or to avoid confusion between a facility (human construction) and an organization perhaps use label "biomedical laboratory organization".

**Comment by johnwjudkins** [comment]
2023-02-06 OK with updated label & definition (Chris & Bill). Jie will update PR.

**Comment by cstoeckert** [comment]
OBI dev call Feb. 13, 2023. No objections. All approve. OK to update PR accordingly.
