### ISSUE TITLE
NTRs: membrane feeding device, membrane feeding assay

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1439]
label: membrane feeding device
definition: A device that contains blood in a membrane penetrable to mosquitoes, designed to feed mosquitoes without the need for an animal host.

label: membrane feeding assay
definition: An assay that evaluates host-to-mosquito transmission of a parasite organism by feeding a specimen of host blood infected with the parasite organism to a collection of mosquitoes through a membrane feeding device and, after a given time, dissecting the mosquitoes and counting the number of parasite organisms within them.
measurand: 'parasite organism'
evaluant: Culicidae (NCBITaxon term for mosquito)
device: 'membrane feeding device'

This assay is often used to test the effectiveness of drugs or antibodies against parasite transmission, but essentially it evaluates the transmission capability of the parasite. 'evaluant' cannot refer to transmission (since it is a process), but the evaluation has a material basis in the number of parasites found within the dissected mosquito, so I identified the dissected mosquito as the evaluant and the parasite as the measurand.

**Comment by cstoeckert** [comment]
since this is mosquito specific, should probably include that in the labels
i.e. mosquito membrane feeding device, mosquito membrane feeding assay

Also, should put the mention of "This assay is often used to test the effectiveness of drugs or antibodies against parasite transmission." as an example of usage.
