### ISSUE TITLE
OBI "device" should be renamed?

### ISSUE THREAD

**Issue by ddooley** [obi-ontology/obi#1453]
Right now "device" has very specific semantic: A material entity that is designed to perform a function in a scientific investigation, but is not a reagent.  Should this be renamed "scientific investigation device".  And should OBI or ENVO have a much more general "device" term to cover non-scientific devices?  I ran into this when trying to position a new ENVO term "bottle" as a general purpose thing and got in trouble over there!

Also, is equipment a subclass of device?  E.g. I'd call a bottle a device, but would I call it a piece of equipment?

**Comment by sebastianduesing** [comment]
I believe this issue can be closed, given the decision to adopt & generalize OBI:device in COB.
