### ISSUE TITLE
Write script to determine which new terms have been merged

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1454]
We've been using the [OBI Term ID Reservation](https://docs.google.com/spreadsheets/d/1tpDrSiO1DlEqkvZjrDSJrMm7OvH9GletljaR-SDeMTI/edit#gid=224833299) Google Sheet for a while. There's a 'merged' column which should be "TRUE" if the term has been actually been merged into `master`. We need a script that we can use to fill out that column. Then we should look for terms that have been on that sheet for a long time but not yet merged.

(Even better than "TRUE" would be a commit ID, but that seems like a lot of work.)

**Comment by beckyjackson** [comment]
I'm guessing we would want to use COGS for this? The one problem I can think of is that since we aren't creating a new Google Sheet each time, we would need to store some shared credentials in this repository.

**Comment by jamesaoverton** [comment]
As a first pass, I would just like to get a copy of the table with the 'merged' column filled. Then we can worry about how to get that information into the Google Sheet.

**Comment by beckyjackson** [comment]
Can we make the Google Sheet available to anyone with the link, or do you want to keep it restricted? I was just going to use `curl` to grab it but this won't work if it's restricted.

**Comment by jamesaoverton** [comment]
Yeah. I think the permissions got messed up at some point. I made it viewable by anyone.
