### ISSUE TITLE
Detection Technique Definition 

### ISSUE THREAD

**Issue by hectorguzor** [obi-ontology/obi#1488]
Discussed during OBI 2022 workshop:

We need a clear definition of what counts as a detection technique. We decided on the following tentative definition. 

assay B is a _detection technique_ in assay A if:

1. assay B is a part of assay A. and 
2. the target entity of assay B and the target entity of assay A are disjoint. and 
3. if either:
* a. the data item output of assay B **is_proxy_for** the data item output of assay A. or 
* b. the data item output of assay A is the specified output of some [data transformation](http://purl.obolibrary.org/obo/OBI_0200000), with the output of assay B as a specified input.

**What we need to do moving forward:**

1. clarify whether 'detection technique' is a class or a design pattern/ annotation property/ 'role'.
2. clarify how is_proxy_for is being used in the definition. this could be interpreted as a 'no data transformation re-interpretation' of a data item, based on knowing how it was constructed. do we want to use OBI [is_proxy_for](http://purl.obolibrary.org/obo/OBI_0000314)? or something else?
3. figure out how to specify the  'data transformation' part for assays that have one.
4. figure out how to implement logical definition into assays template to identify incorrect techniques. and how to document detection technique definition for future development if the implementation of logical definition into template is not possible.

**Comment by bpeters42** [comment]
Of note, the definition of 'is_proxy_for' in OBI is not between data items, but between the entity being measured. So I think it should be target of B is_proxy_for target of A. I think that actually holds in general.

**Comment by johnwjudkins** [comment]
Discussed 2022-02-07. Agree that target entity (either case) is not always a measurand. Can drop 3b (original post). Will discuss further next week.

**Comment by hectorguzor** [comment]
Discussed 2022-02-14: 
responses to action items in the original post: 
1) Detection technique is not a class. assays can be used as a detection technique in some contexts, but not others. it is not a role, under BFO only independent continuants can bear roles. Bjoern is suggesting to think of these as 'process characteristics', but we don't have these yet. He will discuss this in the next meeting. 
2) 'is proxy for' is a relation between entities being measured. So the target of the detection technique is a proxy for target of general assay. 
3) no need to specify 'data transformation'. 
4) this needs to be discussed.

**Comment by bpeters42** [comment]
Discussion on call 2/28: 
**detection technique**: An assay (A) that is part of another assay (B), where the target entities of A and B are disjoint, and the target entity of A is a proxy for the target of assay B. 

In template, we can do: has_part some (% and 'detection technique') 

Alternatives discussed, that we can flip out later. 
[has_part some (% and realizes some (detection technique process characteristic))
has_part some (% and realizes some concretizes some (detection technique design))]

This should be tried out and modeled, to ensure we can query for assays with a shared detection technique, and we should ensure that the RNA-Seq modeling can be implemented.

**Comment by hectorguzor** [comment]
Discussed on OBI call 2022-03-21: We will create a 'detection technique' class in `assays.tsv` and change the axiom for the detection technique column to ('has part' some (% and 'detection technique)). 

next step: figure out or just try a way to make primary assay and detection technique assay disjoint. If assay D (detection technique) is a part of assay A, D should be disjoint from A. This will be a different issue.
