### ISSUE TITLE
2 terms with same definition

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1497]
The definitions for 'Centers for Disease Control and Prevention light trap' and 'New Jersey light trap' are exactly the same. I suspect this happened because part of the definition for the former was removed and became an editor note. I propose changing its definition:
 
A light trap that is designed similarly to the New Jersey trap—in that it uses motorized suction and light attractant—and is powered by a six-volt battery.

source: https://vectorbio.rutgers.edu/outreach/cdctrap.htm
(I think we can leave the editor note as is)

**Comment by zhengj2007** [comment]
Discussed on OBI call 2022-03-14

John will update the definition for 'Centers for Disease Control and Prevention light trap' and create pull request.
