### ISSUE TITLE
NTR: diagnostic process and diagnosis

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#1505]
Discussed [the issue](https://github.com/obi-ontology/obi/issues/623) on 2022 OBO workshop, day 2 (Feb 1st, 2022) 

OGMS has these terms.
[OGMS_0000104: 'diagnostic process' ](http://purl.obolibrary.org/obo/OGMS_0000104)
A health care process that involves the interpretation of a clinical picture from a given patient (input) and the assertion to the effect that the patient has a disease, disorder, or syndrome of a certain type, or none of these (output).

[OGMS_0000073: diagnosis](http://purl.obolibrary.org/obo/OGMS_0000073)
The representation of a conclusion of a diagnostic process.

Both about 'patient'. However, OGMS did not define what patient is. The terms are likely only applied to human. So, OBIers decided to add more general 'diagnostic process' and 'diagnosis' including animals (e.g. mouse) and even plants. Here are proposed label and definition.

Label: organism diagnostic process (for distinguish with OGMS one)
Parent: drawing a conclusion based on data
Definition: A drawing a conclusion based on data that involves the interpretation of data about a given organism (human, animal, or plant) and the assertion to the effect that the organism has a disease, disorder, or syndrome of a certain type, or none of these as output.

Label: diagnosis of an organism
Parent:  conclusion based on data
Definition: A conclusion based on data about that an organism has a disease, disorder, or syndrome of a certain type, or none of these.

Hi @ramonawalls, could you please check whether they are what we decided to add?

**Comment by zhengj2007** [comment]
Discussed on OBI call 2022-03-14.

Will add the terms in OBI.

**Comment by zhengj2007** [comment]
OBI imported OGMS:diagnosis as subClass of 'data item' as it is defined in OGMS. Should align the OGMS term with OBI one. 

Two options:
1. import OGMS:diagnosis as subClassOf OBI:'diagnosis of an organism'
2. define OBI:'conclusion based on data' as 'data item' rather than ICE

If I remember correctly, we discussed in the workshop and thought it is more accurate to define the 'conclusion based on data' as an ICE. If it is the decision, I propose to import OGMS:diagnosis as subClassOf OBI:'diagnosis of an organism'.

**Comment by zhengj2007** [comment]
Discussed on OBI call 2022-03-28. We decided not import OGMS:diagnosis and moved current subClasses of OGMS:diagnosis to OBI 'diagnosis of an organism'.

**Comment by jamesaoverton** [comment]
Was this fully addressed by PR #1520? If so, please close this issue.
