### ISSUE TITLE
NTR: milk assay datum, umbilical cord blood assay datum 

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1515]
These follow the same pattern for specimen assay data as #1428.

milk assay datum - A data item that is the specified output of a milk assay.
umbilical cord blood assay datum - A data item that is the specified output of an umbilical cord blood assay.

**Comment by hectorguzor** [comment]
Discussed on OBI call 2022-03-21: these look good and @johnwjudkins will work on PR.
