### ISSUE TITLE
GO:0040030 is obsolete, but not properly marked obsolete in OBI

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#1517]
OBI includes [GO: 0040030 obsolete regulation of molecular function, epigenetic](http://purl.obolibrary.org/obo/GO_0040030) (including "obsolete" in the label), but it lacks the "obsolete" annotation. I did not immediately see a replacement term. It also has two children in OBI: 

- [GO:0044030 regulation of DNA methylation](http://purl.obolibrary.org/obo/GO_0044030)
- [GO:0040029 regulation of gene expression, epigenetic](http://purl.obolibrary.org/obo/GO_0040029)

**Comment by DanBerrios** [comment]
Discussed on the call 4/11/22, James to handle.

**Comment by jamesaoverton** [comment]
It looks like [GO:0044030 regulation of DNA methylation](http://purl.obolibrary.org/obo/GO_0044030) is used in OBI ~30 times, but the other two GO terms mentioned here are not used. So I will remove the two unused GO terms from our import, and make GO:0044030 a direct child of 'biological_process'.
