### ISSUE TITLE
NTR: peripheral blood mononuclear cell specimen

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1532]
label:
peripheral blood mononuclear cell specimen

definition:
A processed specimen that is extracted from whole blood using gradient centrifugation that separates the blood into a layer of peripheral blood mononuclear cells under the top layer of plasma. It contains lymphocytes, monocytes or macrophages that are critical components in the immune system.

alternative term:
PBMC specimen

definition source:
http://en.wikipedia.org/wiki/Peripheral_blood_mononuclear_cell

term editor:
Jie Zheng | Chris Stoeckert

**Comment by rvita** [comment]
you may want to refer to this CL term in this obi term
peripheral blood mononuclear cell
Term IRI: http://purl.obolibrary.org/obo/CL_2000001
