### ISSUE TITLE
organizations duplicate definitions ROBOT report error

### ISSUE THREAD

**Issue by hectorguzor** [obi-ontology/obi#1533]
Duplicate definitions were identified in the ROBOT report for organizations. See the list of terms here:

https://docs.google.com/spreadsheets/d/16EMx4nZruzSshe08_rPBD-xdVqyuIrHaQWtNy37WQos/edit?usp=sharing 

One solution is to just remove definitions for these terms or maybe change the definitions to `rdfs:comment` in the`organizations.tsv`.

**Comment by zhengj2007** [comment]
Discussed on OBI call 2022-05-09. We decided to remove the duplicated definitions of the organization instances.
