### ISSUE TITLE
new term request for CFDE-GlyGen project : synaptosome preparation process

### ISSUE THREAD

**Issue by nsuvarnaiari** [obi-ontology/obi#1545]
Hi OBI,

We would like to request a new term 'synaptosome preparation process' for which the provisional OBI id has been registered in the registry. The details are:

Name: 'synaptosome preparation process'
New OBI term id: OBI:0003384
Parent class: 'material component separation' OBI:0600014
Definition: A material component separation process where a synaptic terminal is isolated from a neuron by mild homogenization of nervous tissue under isotonic conditions and subsequent fractionation using differential and density gradient centrifugation.
Source of definition: [https://en.wikipedia.org/wiki/Synaptosome](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSynaptosome&data=05%7C01%7Csnadendla%40som.umaryland.edu%7C15728c081ee84f13333708da383758da%7C717009a620de461a88940312a395cac9%7C0%7C0%7C637884107608793230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P%2Fc28VYNEkO2RQB%2B%2FHd4qEEY1TYkxg4%2BNO8uQzg1vjk%3D&reserved=0)

We are not able to decide between two parent classes as the correct parent for this term. We would like to have your thoughts and input on this. The one we proposed is 'material component separation' (def: a material processing in which components of an input material become segregated in space) because during the synaptosome preparation process, synaptic terminal is separated from a neuron, which is the synaptosome. Another possible parent class is 'specimen collection process' OBI:0000659 (def: A planned process with the objective of collecting a specimen) as synaptosome that is separated is used as a specimen in downstream assays. 

Thanks,
Suvvi and [mgiglio99](https://github.com/mgiglio99)

**Comment by cstoeckert** [comment]
Discussed on June 6, 2022 OBI call. Consensus is that the parent should be 'material component separation'. Specimen collection would probably come before this process.

**Comment by mgiglio99** [comment]
Finished
