### ISSUE TITLE
subtypes of electrophysiology assay should be classified under electrophysiology assay

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1547]
[electrophysiology assay](http://purl.obolibrary.org/obo/OBI_0002176) has no child terms

these should be underneath it:

 - intra cellular electrophysiology recording assay _An electrophysiology recording assay where the recording location of the electrode is intracellular_
 - extracellular electrophysiology recording assay _An electrophysiology recording assay where the recording location of the electrode is extracellular_

current structure:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/50745/170891455-563b5db8-5842-4fba-964d-f8093cacfee2.png">

I also recommend 

- removing space in "intra cellular"
- checking that the genus of definitions is an actual term (I don't think there is an intention for a electrophysiology *recording* assay from a electrophysiology assay)
- use simple DPs and auto-classification

Also watch out for hidden GCIs and future ragged lattice issues here. How do these axes combine? Is single-unit always extracellular? are there no intracellular measurements of the caudate nucleus?

**Comment by cstoeckert** [comment]
Discussed on June 6, 2022 call. At least part of this issue was addressed in https://github.com/obi-ontology/obi/pull/1499
Will be in next release.

**Comment by hectorguzor** [comment]
I think the major issues brought up have been addressed with PR #1499 and #1592. @cmungall  thanks for bringing these up. If there is still something that hasn’t been addressed that needs immediate attention please let me know. For now, I will go ahead and close this issue.
