### ISSUE TITLE
NTRs: Freezer, Freezer handle

### ISSUE THREAD

**Issue by Anoosha-Sehar** [obi-ontology/obi#1563]
Dear OBI curators,

I would like to request these terms as a part of the AMR-GRDI project. 
Thank you.

Label: Freezer
Parent: environmental control device (OBI:0001034)
Definition: A compartment, room, or device for freezing things or keeping them frozen.
Definition source: [https://www.merriam-webster.com/dictionary/freezer]

Label: Freezer handle
Parent: environmental control device (OBI:0001034)
Definition: The handle of a freezer door.
Comment: part of relation

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2022-07-25. @Anoosha-Sehar Do you mean a freezer that is scientific equipment, as opposed to the more general http://purl.obolibrary.org/obo/ENVO_01000583 'refrigerator'?

**Comment by Anoosha-Sehar** [comment]
Hi James. Yes, that's right. I also had a discussion with Damion and we concluded to request these terms to ENVO. 
Thank you very much for looking into it.
