### ISSUE TITLE
Reformulation of 'ontology' document header tag

### ISSUE THREAD

**Issue by kdumschott** [obi-ontology/obi#1569]
Hello, The current formulation of the "ontology" document header tag in the .obo file is set as "ontology: obi.obo", resulting in the ontology being 'obi.obo' instead of 'obi' when we load it into our database.

According to the Built-in OBO Semantics in [The OBO file format guide](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2), the ontology tag should correspond to the ID prefix of the terms that belong to that ontology, translated to lowercase. Therefore, we suggest reformulating the tag to "ontology: obi" so that it corresponds with the OBO formatting.

**Comment by cstoeckert** [comment]
Looked at on OBI Oct. 3, 2022 call. this is a release pipeline issue, @cmungall what should we change?

**Comment by cmungall** [comment]
Try simply removing the annotate step in that command, you're explicitly setting the ontology iri to obi.obo

Overall there is a lot going on in that command. I recommend separating the process of making some kind of filtered version from the task of format conversion
