### ISSUE TITLE
ANOVA should be a subclass of statistical hypothesis test to be consistent with STATO

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1570]
OBI:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/50745/179564331-8725831a-4e5f-4150-9efc-4e3ceae0de56.png">

note that ANOVA and 'statistical hypothesis test' are siblings

STATO:

<img width="137" alt="image" src="https://user-images.githubusercontent.com/50745/179563839-6afa6a73-f12b-48bf-95b0-29f9b1906ca8.png">

STATO injects its own intermediate "between group comparison statistical test" between two OBI classes. I think injection is problematic, but that is for STATO and OBI to work out.

However, STATO also injects an is-a between two OBI classes, ANOVA and 'statistical hypothesis test' - I am not sure why that was injected into STATO rather than requested directly of OBI

**Comment by bpeters42** [comment]
Good catch! We should change the placement of ANOVA to be a statistical test in OBI. I did a quick review of other data transformation processes in OBI, and there are no obvious other examples of this happening.
