### ISSUE TITLE
OBI_00001975 has 8 characters in identifier

### ISSUE THREAD

**Issue by cthoyt** [obi-ontology/obi#1593]
http://purl.obolibrary.org/obo/OBI_00001975 (chromatin immunoprecipitation) is the only instance of an OBI term with a local unique identifier of length 8. Is this an oversight?

**Comment by jamesaoverton** [comment]
It was a mistake that we discovered quite a while after the term was published and in use. We added checks to prevent that from happening in the future. The last time we discussed the problem, we decided to leave it alone.

**Comment by cthoyt** [comment]
Alright then there's nothing to do here.
