### ISSUE TITLE
NTR: Gram stain assay

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1603]
Definition:
An organism identification assay that identifies bacteria based on the differential retention of a crystal violet-iodine complex within the cell membrane.

Comment:
Gram-positive bacteria retain the violet stain whereas gram-negative bacteria do not.

Source:
NCI|American Heritage Medical Dictionary

**Comment by johnwjudkins** [comment]
Discussed 2022-10-10. Definition OK. Will define output data of combination of Gram stain and differential media assays as:
'data item' and (has_part some (has_specified output of some 'Gram stain assay') and has_part some (has_specified output some 'differential media assay')

**Comment by mgiglio99** [comment]
Hi John,
I think we should change the definition to say "....within the cell wall" (rather than membrane).
Michelle
