### ISSUE TITLE
NTRs: lymph specimen, digestive tract specimen 

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1607]
label: lymph specimen
definition: A specimen that is derived from a portion of lymph collected from an organism. (edited per CS comment & 'blood specimen' definition)
(UBERON:0002391)

label: digestive tract specimen
definition: A specimen that is derived from part of a digestive tract.
alt. label: gastrointestinal specimen
(UBERON:0001555)

**Comment by cstoeckert** [comment]
I think we want to say for lymph specimen, derived from a portion of lymph.
