### ISSUE TITLE
OBI:0002781 and OBI:0002783 have the same EquivalentTo

### ISSUE THREAD

**Issue by shawntanzk** [obi-ontology/obi#1608]
Not sure if OBI cares about duplicate equivalencies but currently 
ERROR Equivalence: <http://purl.obolibrary.org/obo/OBI_0002781> == <http://purl.obolibrary.org/obo/OBI_0002783>

This pinged as ODK comes with an equivalence check during release process 

'lower respiratory tract specimen' and 'lower respiratory tract aspirate specimen' have are EquivalentTo
```
specimen
 and (is_specified_output_of some 
    ('collecting specimen with swab'
     and (has_specified_input some 'lower respiratory tract')))
```
If not an issue, please do help me close this ticket :) thanks!

**Comment by jamesaoverton** [comment]
I think this is a duplicate of https://github.com/obi-ontology/obi/issues/1476, and it looks like I dropped the ball on it.

**Comment by shawntanzk** [comment]
whoops searched for the wrong thing, thanks @jamesaoverton - will close this ticket

**Comment by jamesaoverton** [comment]
Much appreciated!
