### ISSUE TITLE
Some OBI terms not getting displayed in tree view in OLS

### ISSUE THREAD

**Issue by nsuvarnaiari** [obi-ontology/obi#1610]
JUST FYI: When searched with some OBI terms in OLS, the terms get displayed in the results page but when clicked, the page gets redirected to another page saying something went wrong. Raised a ticket with OLS - https://github.com/EBISPOT/OLS/issues/641

Thanks,
Suvvi

**Comment by jamesaoverton** [comment]
Strange. It looks fine in Ontobee <https://ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0003301> and there's nothing out-of-the-ordinary about this term.

**Comment by nsuvarnaiari** [comment]
The issue has been fixed at OLS. Please refer to https://github.com/EBISPOT/OLS/issues/641 for more details.

**Comment by jamesaoverton** [comment]
@nsuvarnaiari Thanks for chasing this problem down!
