### ISSUE TITLE
Format term-tracker-item annotations consistently

### ISSUE THREAD

**Issue by matentzn** [obi-ontology/obi#1621]
A handful of easy-to-fix cases: https://api.triplydb.com/s/-p00wlgwm

**Comment by jamesaoverton** [comment]
@hectorguzor could you please make these small fixes?

**Comment by hectorguzor** [comment]
@jamesaoverton one of the terms with a bad term-tracker annotation format is an IAO term 
 http://purl.obolibrary.org/obo/IAO_0006011 
 
Below is the term-tracker item for this term. 
https://github.com/information-artifact-ontology/ontology-metadata/issues/40
 
This wouldn’t be a PR for OBI, but IAO to fix right? Should I just create a PR for the IAO repository for this term?

**Comment by jamesaoverton** [comment]
Yeah, please make an IAO PR for that fix. Much appreciated!
