### ISSUE TITLE
Clarification regarding identifier modeling pattern in OBI (and OBO) needed

### ISSUE THREAD

**Issue by StroemPhi** [obi-ontology/obi#1624]
# The problem
There are identifieres, e.g. DOI, PubMed ID or specimen identifier, subsumed under [IAO:symbol](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000028&lang=en&viewMode=All&siblings=false#) & [IAO:centrally registered identifier symbol](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000577&lang=en&viewMode=All&siblings=false#) in OBI, although there is also the class [IAO:identifier](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0020000&lang=en&viewMode=All&siblings=false#) & [IAO:centrally registered identifier](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000578&lang=en&viewMode=All&siblings=false#). While some OBO ontologies follow OBI, reusing these classes and/or defining new identifiers also under IAO:symbol or IAO:CRID symbol, some use IAO:identifier and IAO:CRID identifier to do so.

This discrepancy has historical reasons, since IAO:identifier most likely wasn't available back when these identifiers were coined in OBI, as it was first defined in PNO using the IAO namespace and was only recently merged into IAO (https://github.com/information-artifact-ontology/IAO/issues/236). I feel a bit bad having been the one starting that overdue integration proposal and now also am the one pointing to the not yet addressed consequences it entails. But I now know more about previous OBO work and that this issue has been lingering around for more than a decade (see the very important context [here](https://docs.google.com/document/d/1Iv5VS8kbOnoQbBTt-FaJU37gK9MXkENm7pHGSk_q4d0/edit#heading=h.2q2cubd254cj) & [here](https://code.google.com/archive/p/information-artifact-ontology/wikis/IAO_0000028_aka_symbol.wiki)). So, with the pending [integration of PNO into IAO](https://github.com/information-artifact-ontology/IAO/issues/237), I think we have a great opportunity to work on harmonizing the different currently existing practices of modeling identifiers either as subclasses of IAO:symbol or of IAO:identifier by making really clear what the difference between IAO:symbol and IAO:identifier are. I already referred to this discrepancy in [this now closed IAO issue](https://github.com/information-artifact-ontology/IAO/issues/259#issuecomment-1292198815) and there @zhengj2007 suggested that writing an issue here might be best, although it is equally relevant for IAO and other ontologies reusing and or defining identifiers.

I've tried my best to gather the information I could find regarding this issue (mostly by using OLS and following links in editor notes/comments or GH issues/PRs), which will hopefully allow us to sort things out in a way most or hopefully all can agree on.

## Which OBO ontologies follow the OBI pattern, using IAO:symbol as parent for identifiers?
* CHEMINF defines alot (mostly chemical DB ids) under [IAO:centrally registered identifier symbol](https://www.ebi.ac.uk/ols/ontologies/cheminf/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000577&lang=en&viewMode=All&siblings=false#)
* see [EUPATH:IRB number](https://www.ebi.ac.uk/ols/ontologies/eupath/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FEUPATH_0000535&lang=en&viewMode=All&siblings=false#)
* see children GENEPIO's [IAO:symbol](https://www.ebi.ac.uk/ols/ontologies/genepio/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000028#) 
* [ICO:review board approval number](https://www.ebi.ac.uk/ols/ontologies/ico/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FICO_0000111&lang=en&viewMode=All&siblings=false#)
* [LABO:medical record identifier](https://www.ebi.ac.uk/ols/ontologies/labo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHADO_0000006&lang=en&viewMode=All&siblings=false#)
* I guess the whole [NOMEN - A nomenclatural ontology for biological names](https://www.ebi.ac.uk/ols/ontologies/nomen)
* [ORNASEQ:experiment name](https://www.ebi.ac.uk/ols/ontologies/ornaseq/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FORNASEQ_0000004&lang=en&viewMode=All&siblings=false#)
* in PDRO children of [IAO:centrally registered identifier symbol](https://www.ebi.ac.uk/ols/ontologies/pdro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000577&lang=en&viewMode=All&siblings=false#)

## Which OBO ontologies follow the PNO pattern, using IAO:identifier as parent for identifiers?
* In Apollo_SV, subsumed under [IAO:identifier](https://www.ebi.ac.uk/ols/ontologies/apollo_sv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0020000&lang=en&viewMode=All&siblings=false) we not only find a duplicate to the most prominent example of the [PubMed identifier](https://www.ebi.ac.uk/ols/ontologies/apollo_sv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAPOLLO_SV_00000495&lang=en&viewMode=All&siblings=false#), but also that terms imported from OBI have been changed to be children of IAO:identifier, such as [grant identifier](https://www.ebi.ac.uk/ols/ontologies/apollo_sv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001629&lang=en&viewMode=All&siblings=false) or [digital object identifier](https://www.ebi.ac.uk/ols/ontologies/apollo_sv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0002110&lang=en&viewMode=All&siblings=false#)
* [DIDEO:drug concept set identifier](https://www.ebi.ac.uk/ols/ontologies/dideo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDIDEO_00000128&lang=en&viewMode=All&siblings=false#)
* [OHD:current dental terminology code](https://www.ebi.ac.uk/ols/ontologies/ohd/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCDT_1000001&lang=en&viewMode=All&siblings=false#)
* in PROCO three children under [IAO:centrally registered identifier](https://service.tib.eu/ts4tib/ontologies/proco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000578&viewMode=All&siblings=false#) (including likely duplicate to [CHEMINF:CAS registry number](https://www.ebi.ac.uk/ols/ontologies/cheminf/terms?iri=http%3A%2F%2Fsemanticscience.org%2Fresource%2FCHEMINF_000446&lang=en&viewMode=All&siblings=false#))

## Which OBO ontologies use a mix of either IAO:symbol or IAO:identifier as parent for identifiers?
* [EUPATH:IRB number](https://www.ebi.ac.uk/ols/ontologies/eupath/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FEUPATH_0000535&lang=en&viewMode=All&siblings=false#) as IAO:symbol and [geohash code](https://www.ebi.ac.uk/ols/ontologies/eupath/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FEUPATH_0043202&lang=en&viewMode=All&siblings=false#) as IAO:identifier
* in OBIB we have the two IAO:symbols [courier tracking number](https://www.ebi.ac.uk/ols/ontologies/obib/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0002191&lang=en&viewMode=All&siblings=false#) & [identification number of a protocol at a particular site](https://www.ebi.ac.uk/ols/ontologies/obib/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBIB_0000474&lang=en&viewMode=All&siblings=false#) (which looks very similar to [EUPATH:IRB number](https://www.ebi.ac.uk/ols/ontologies/eupath/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FEUPATH_0000535&lang=en&viewMode=All&siblings=false#)) and quite a lot of children of IAO:identifier
* in OMRSE see the children of [IAO:symbol](https://www.ebi.ac.uk/ols/ontologies/omrse/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000028&lang=en&viewMode=All&siblings=false#) & [social security number](https://www.ebi.ac.uk/ols/ontologies/omrse/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMRSE_00000000&lang=en&viewMode=All&siblings=false#)
* [OPMI:centrally registered study identifier symbol](https://www.ebi.ac.uk/ols/ontologies/opmi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOPMI_0000165&lang=en&viewMode=All&siblings=false#) and children of [IAO:centrally registered identifier](https://www.ebi.ac.uk/ols/ontologies/opmi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000578&lang=en&viewMode=All&siblings=false#)

## Which OBO ontologies use identifier like classes defined directly under IAO:ICE?
* [ONS:sampling identifier](https://www.ebi.ac.uk/ols/ontologies/ons/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FONS_0000049&lang=en&viewMode=All&siblings=false#), ONS:[event identifier name](https://www.ebi.ac.uk/ols/ontologies/ons/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FONS_0000043&lang=en&viewMode=All&siblings=false#)
* [ONTONEO:identifier code](https://www.ebi.ac.uk/ols/ontologies/ontoneo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FONTONEO_00000069&lang=en&viewMode=All&siblings=false#) a seemingly still work in progress --> problematic anyhow, as it reuses the deprecated relation property "[designates](https://www.ebi.ac.uk/ols/ontologies/ontoneo/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0020012&lang=en&viewMode=All&siblings=false)" imported from a idk how old OMIABIS

## Probably not relevant for OBO?
In AFO we can see the "mixup" of what is considered an identifier by looking at how they extend [IAO:symbol](https://www.ebi.ac.uk/ols/ontologies/afo/terms?iri=http%3A%2%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000028&lang=en&viewMode=All&siblings=false) as well as [IAO:identifier](https://www.ebi.ac.uk/ols/ontologies/afo/terms?iri=http%3A%2F%2Fpurl.allotrope.org%2Fontologies%2Fresult%23AFR_0000917&lang=en&viewMode=All&siblings=false). What is most obvious is the fact that they don't update upstream changes regularly (which was confirmed to my via email from the company that is contracted by Allotrope to do the ontology dev work).

## Other not yet refenced and related OBI issues I found
* https://github.com/biobanking/biobanking/issues/88
* https://github.com/obi-ontology/obi/issues/1246

**Comment by StroemPhi** [comment]
probably other historically relevant context: http://icbo.buffalo.edu/Presentations/Ruttenberg.pdf ICBO2012 presentation?
* relevant section on identifiers starting with page 65
* relevant section on symbols startig with page 96

**Comment by StroemPhi** [comment]
In how far is [CEUSTERS 2012 - An Information Artifact Ontology Perspective on Data Collections and Associated Representational Artifacts](http://dx.doi.org/10.3233/978-1-61499-101-4-68) relevant for this issue? Could "term" and "denotator" be helpful destinctions in the clarification?

**Comment by ddooley** [comment]
@StroemPhi are you able to recommend concrete steps to unify use of IAO:symbol and IAO:identifier use (with deprecation perhaps) in particular ontologies? If not perhaps this is best written up as a discussion paper, and action could arise in the community as a result of that?  We would like to close this item in either case as we don't have the bandwidth to coordinate this kind of change in use within the community.

**Comment by StroemPhi** [comment]
@ddooley sorry for my late response. As I wrote in the description, I opened this issue here, because @zhengj2007 said this would be the right place. Maybe it's better to move this discussion back to IAO?
