### ISSUE TITLE
Please roll back merged change to OBI:0001624 (keep definition in current release)

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1627]
Jie has informed me that changing the definition of [organism identification assay](http://purl.obolibrary.org/obo/OBI_0001624) as I've proposed in #1598 would contradict its meaning in the [NIAID metadata standard](https://www.niaid.nih.gov/research/dmid-metadata-standards-core-sample).

We wanted to catch this before it ended up in the next release. The definition is fine as is.

@jamesaoverton What steps should be taken here? Could you roll back this commit https://github.com/obi-ontology/obi/pull/1616/commits/96477f9f3d678d0249d996eb5723baab3a7de34f, or should I make another PR?

**Comment by jamesaoverton** [comment]
Ok. I’m not sure what the best steps are. I’ll look into it.
