### ISSUE TITLE
remove fluorescence imaging assays as children of fluorescence detection assay

### ISSUE THREAD

**Issue by hectorguzor** [obi-ontology/obi#1628]
Hi @mgiglio99 and @nsuvarnaiari 

As you know, I am working on [cleaning up assays](https://github.com/obi-ontology/obi/issues/1556) that are not consistent with definitions for **SubclassOf  (for assay)** and **detection technique**. You can find the list of assays [here](https://docs.google.com/spreadsheets/d/1Y_HUi3ZbwDMi2q_HU3stwv7BHh6UxbStLgB66-zFgkc/edit#gid=0). I provide the definitions for your reference below:

- **SubclassOf (for assay)**:  An assay A is a subclass of assay C if every conceivable instance of assay A is a subclass of assay C; specifically, (i) the target entity of assay A is a subclass of the target entity of assay C, and (ii) the data item output of assay A is a subclass of the data item output of assay C. 

- **Detection technique**: an assay (A) that is part of another assay (B), where the target entities of A and B belong to disjoint classes, and the target entity of A is a proxy for the target of assay B

I have identified a few assays your team worked on that are not consistent with these definitions. 
 

1. [fluorescence imaging-based cell morphology assay](http://purl.obolibrary.org/obo/OBI_0002951)
2. [fluorescence imaging-based protein phosphorylation state assay](http://purl.obolibrary.org/obo/OBI_0002954)
3. [fluorescence imaging-based cell viability assay](http://purl.obolibrary.org/obo/OBI_0002949)
4. [fluorescence imaging-based apoptosis assa](http://purl.obolibrary.org/obo/OBI_0002946)y
5. [fluorescence imaging-based reporter gene assay](http://purl.obolibrary.org/obo/OBI_0002960)
6. [fluroescence imaging-based cell cycle state assay](http://purl.obolibrary.org/obo/OBI_0002948)
7. [fluorescence imaging-based cell proliferation assay](http://purl.obolibrary.org/obo/OBI_0002947)
8. [fluorescence imaging multiplex cytological profiling](http://purl.obolibrary.org/obo/OBI_0002952)
9. [fluorescence imaging-based drug synergy assay](http://purl.obolibrary.org/obo/OBI_0002950)

 
Currently, these assays are inferred as children of ‘[fluorescence detection assay](http://purl.obolibrary.org/obo/OBI_0001501)’ and also use it as a detection technique. I recommend that all of these assays keep ‘fluorescence detection assay’ as a detection technique, but remove ('material entity' and ('bearer of' some fluorescence)) as a specified_input to avoid inference under ‘fluorescence detection assay’. That should make these consistent with the definitions above.
 
In some cases, we can specify their target entities to make it clearer that ‘fluorescence detection assay’ is being used as a detection technique.  Below I provide suggestions for what the target entities of these assays could be based on my understanding of them. Let me know what you think. 
 

1. [fluorescence imaging-based cell morphology assay](http://purl.obolibrary.org/obo/OBI_0002951): Target entity  = (‘[morphology](http://purl.obolibrary.org/obo/PATO_0000051)' '[quality of](http://purl.obolibrary.org/obo/RO_0000080)' some cell )  
2. [fluorescence imaging-based protein phosphorylation state assay:](http://purl.obolibrary.org/obo/OBI_0002954) Target entity = ( protein ‘[has quality](http://purl.obolibrary.org/obo/RO_0000086)’ some ‘[phosphorylation](http://purl.obolibrary.org/obo/PATO_0002262)”)
3. [fluorescence imaging-based cell viability assay](http://purl.obolibrary.org/obo/OBI_0002949):  Target entity = (‘[viability](http://purl.obolibrary.org/obo/PATO_0000169)’ ‘quality of’ some cell)
4. [fluorescence imaging-based apoptosis assa](http://purl.obolibrary.org/obo/OBI_0002946)y: Target entity = ‘[apoptotic process](http://amigo.geneontology.org/amigo/term/GO:0006915)’
5. [fluorescence imaging-based reporter gene assay](http://purl.obolibrary.org/obo/OBI_0002960):  Should the target entity of this assay be ‘[gene expression](http://amigo.geneontology.org/amigo/term/GO:0010467)’?
6. [fluroescence imaging-based cell cycle state assay](http://purl.obolibrary.org/obo/OBI_0002948): Should the target entity of this assay be (‘part of’ some [cell cycle](http://amigo.geneontology.org/amigo/term/GO:0007049))? 

Let me know what you all think.

**Comment by mgiglio99** [comment]
Discussed on Jan. 23 call:
There was general agreement with Hector’s proposal to keep ‘fluorescence detection assay’ as a detection technique, but remove ('material entity' and ('bearer of' some fluorescence)) as a specified_input to avoid inference under ‘fluorescence detection assay’. Suvvi and Michelle will take a look at Hector’s suggestions for adding target entities to these terms and get back to him.
