### ISSUE TITLE
NTR: organism detection assay (more general than OBI:0001624)

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1633]
These changes are not urgent.

Label: organism detection assay
Definition: An assay that detects a type of organism and/or the quantity of individuals of a type of organism. 

This is meant to be a more general term than [OBI:0001624](http://purl.obolibrary.org/obo/OBI_0001624) (which is used for NIH metadata, so its meaning should not change). Compared to OBI:0001624, this new assay is not limited to species identification; it can identify organisms by other taxa or life cycle stage, or it can measure density of organisms or count them.

Besides adding the new term, I'd like to replace "identification" with "detection" in the label and definition of OBI:0003064, because I would like this data term to be the output of the new, more general assay, rather than the output of OBI:0001624.

We should also consider relabeling OBI:0001624 to 'organism species identification assay' for clarity.

**Comment by zhengj2007** [comment]
For term OBI:0003064, it should be better to add logical axiom that reflect the textual definition.

**Comment by johnwjudkins** [comment]
Discussed 2022-12-05. May want measurand assay as superclass of analyte assay.

**Comment by johnwjudkins** [comment]
Changes in descendent terms to match this:

Remove the alternative label for 'differential medium assay', because the assay is not limited to bacteria.
All microbiology assay definitions should follow the 'feces microbiology assay' definition with the addition of "organism detection" between "An" and "assay" (so "An organism detection assay that detects microorganisms in a feces specimen." and similarly for other specimen types).
All "organism identification" terms should be "organism detection" except OBI:0001624.

**Comment by johnwjudkins** [comment]
2022-12-12:
'organism identification objective' should be 'organism species detection objective'.
'organism identification assay' can be relabeled as 'organism species detection assay' with equivalent axiom based on 'organism species detection objective'.

Need some note/alt. label noting changes. Alt. label 'organism identification assay' for legacy term.

**Comment by hectorguzor** [comment]
@johnwjudkins it looks like a PR was created and merged for this. Can I close this issue?

**Comment by johnwjudkins** [comment]
@hectorguzor Yes.
