### ISSUE TITLE
NTR: COA Terms

### ISSUE THREAD

**Issue by Daniel-Olson** [obi-ontology/obi#1637]
This NTR relates to a previous thread regarding Cpath's desire to include COA terms in OBI (https://github.com/obi-ontology/obi/issues/1586). 

This first set of terms were taken from the Friedreich's Ataxia Rating Scale (FARS). Additional information can be found in this template (https://docs.google.com/spreadsheets/d/1LOvA8ILhSKxc5WdcmD0NR-YQyo_WfSB_MqMFUjpuLeM/edit#gid=0) including the desired parent classes.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dolson/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dolson/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</head>

<body link="#0563C1" vlink="#954F72">

ontology ID | label
-- | --
OBI:0003501 | functional assessment
OBI:0003502 | facial atrophy assessment
OBI:0003503 | tongue atrophy assessment
OBI:0003504 | forced cough assessment
OBI:0003505 | speech test assessment
OBI:0003506 | finger to finger assessment
OBI:0003507 | nose to finger assessment
OBI:0003508 | dysmetria assessment
OBI:0003509 | rapid alternating hands assessment
OBI:0003510 | finger taps assessment
OBI:0003511 | heel along shin assessment
OBI:0003512 | heel to shin assessment
OBI:0003513 | muscle atrophy assessment
OBI:0003514 | muscle weakness assessment
OBI:0003515 | vibratory sense assessment
OBI:0003516 | position sense assessment
OBI:0003517 | deep tendon reflex assessment
OBI:0003518 | limits of stability assessment
OBI:0003519 | sitting posture assessment
OBI:0003520 | stance feet apart assessment
OBI:0003521 | stance feet apart assessment, with eyes closed
OBI:0003522 | stance feet together assessment
OBI:0003523 | stance feet together assessment, with eyes closed
OBI:0003524 | tandem stance assessment
OBI:0003525 | stance on one foot assessment
OBI:0003526 | tandem walk assessment
OBI:0003527 | gait assessment
OBI:0003528 | bulbar assessment
OBI:0003529 | spontaneous speech assessment
OBI:0003530 | limb coordination assessment
OBI:0003531 | upper limb coordination assessment
OBI:0003532 | lower limb coordination assessment
OBI:0003533 | nervous system functionality assessment
OBI:0003534 | upright stability assessment
OBI:0003535 | deep tendon reflex assessment of the knee joint
OBI:0003536 | observational assessment
OBI:0003537 | deep tendon reflex assessment of the ankle joint
OBI:0003538 | deep tendon reflex assessment of the tendon of biceps brachii
OBI:0003539 | deep tendon reflex assessment of the brachioradialis

</body>

</html>

**Comment by jamesaoverton** [comment]
@Daniel-Olson Can you please give general View access to that Google Sheet?

**Comment by Daniel-Olson** [comment]
Hi James, I have updated the permissions so that anyone with a link can view the sheet.

**Comment by jamesaoverton** [comment]
Closed by #1652.
