### ISSUE TITLE
obi-base.owl includes rdfs:labels for terms from other ontologies

### ISSUE THREAD

**Issue by balhoff** [obi-ontology/obi#1639]
I noticed that `obi-base.owl` includes labels and definitions for terms from other ontologies, including ChEBI, PATO, OGMS, and BFO. These will lead to duplicate and possibly conflicting annotations when obi-base is used with these ontologies.

**Comment by jamesaoverton** [comment]
Looks like I introduced a bug in fed5955ec7393b41067dc773df1dd65436b0d1c6 on 2022-08-29. I can fix that, but it still won't be great.
