### ISSUE TITLE
Equivalent axiom for 'antigen specific antibodies in blood assay datum'

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1650]
[antigen specific antibodies in blood assay datum](http://purl.obolibrary.org/obo/OBI_0003420) has as its parent [blood assay datum](http://purl.obolibrary.org/obo/OBI_0003243). It may be better to assert the parent as [antigen specific antibodies assay datum](http://purl.obolibrary.org/obo/OBI_0002145) to make this parent relationship more clear. As described in https://github.com/obi-ontology/obi/issues/1615, this data item may be better defined using the equivalent axiom 'antigen specific antibodies assay datum' and is_specified_output_of some 'blood assay'. (Then we would have a similar axiom for [antigen specific antibodies in milk assay datum](http://purl.obolibrary.org/obo/OBI_0003421).)

Edit: this last link had "blood" instead of "milk" in the link text; the link itself was correct.

**Comment by zhengj2007** [comment]
[antigen specific antibodies in blood assay datum](http://purl.obolibrary.org/obo/OBI_0003420) is a subclassOf [blood assay datum](http://purl.obolibrary.org/obo/OBI_0003243) but not a subClassOf 'antigen specific antibodies assay datum'. Based on the definitions of assays and their corresponding output, data items, it is not correct. So, propose to define the 'blood assay datum' term using equivalent axioms as proposed in the issue https://github.com/obi-ontology/obi/issues/1615. Then we can assert the 'antigen specific antibodies in blood assay datum' as a subClassOf 'antigen specific antibodies assay datum' and it will be inferred as a subClassOf 'blood assay datum'.

**Comment by johnwjudkins** [comment]
2023-02-06. Will go ahead with changes in PR.

**Comment by hectorguzor** [comment]
@johnwjudkins same for this one,  it looks like a PR was created and merged for this. Can I close this issue?
