### ISSUE TITLE
Possible to improve OBI_0002131?

### ISSUE THREAD

**Issue by allaway** [obi-ontology/obi#1665]
I was not sure where to request this change, please let me know if there is a better place:

[OBI_0002131](https://ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0002131), `Illumina Infinium MethylationEPIC BeadChip` refers to the 850k array, which appears to now be `Illumina Infinium MethylationEPIC BeadChip v1.0` and is being replaced this year with a 935k array, which is `Illumina Infinium MethylationEPIC BeadChip v2.0`. It would be very helpful to be able to distinguish these two arrays with distinct terms. Thanks for your consideration!

**Comment by sebastianduesing** [comment]
Hi there, thanks for submitting this issue. We discussed this on the Nov. 13 2023 OBI dev call. Apologies that it took us some time to get back to this one; I'll take care of this shortly and I'll follow up once the new terms are PRed.

**Comment by allaway** [comment]
Thanks!
