### ISSUE TITLE
Refine definition for OBI:irradiation to include notion of necessarily being a planned process

### ISSUE THREAD

**Issue by DanBerrios** [obi-ontology/obi#1666]
The current definition of OBI:irradiation is:

irradiation is a process by which a material entity is exposed to radiative energy, which could be ionizing radiation (such as gamma rays or X-rays)  or not such as UV light or microwaves

This however does not include the required attribute of being a planned process.  This makes it hard to distinguish from unplanned irradiation processes.  
In addition, the definition is written to imply limited to EM radiation (even though strictly it does not require that).

Consider changing label to "planned irradiation"

Proposed new definition:

irradiation that is a planned process by which a material entity is exposed to radiative energy, which could be ionizing radiation (such as gamma rays, X-rays, charged particles or neutrons) or not, such as UV light or microwaves

**Comment by jamesaoverton** [comment]
Discussed on OBI dev call 2023-07-10. 

Change label: "planned irradiation"

Change definition: "A planned process by which a material entity is exposed to radiative energy, which could be ionizing radiation (such as gamma rays, X-rays, charged particles or neutrons) or non-ionizing radiation (such as UV light or microwaves)"
