### ISSUE TITLE
NTR: breath specimen, breath assay

### ISSUE THREAD

**Issue by johnwjudkins** [obi-ontology/obi#1668]
NCIT has [Breath test](http://purl.obolibrary.org/obo/NCIT_C116515), but I think it might be worth having an OBI term for a breath assay that fits the design pattern for other assay and specimen types (like blood assay). The specimen is gas exhaled from the body that can be analyzed for H<sub>2</sub>, CH<sub>4</sub>, CO<sub>2</sub>, etc. This specimen includes not only air from the lungs but also the GI system.

To fit the design pattern, we'd want an UBERON term for the bearer of the specimen role. UBERON has [excreted gas](http://purl.obolibrary.org/obo/UBERON_0034945), but only the excreted gas from the mouth is collected for a breath test.

**Comment by johnwjudkins** [comment]
2023-04-03: I will request new term in UBERON - something like "gas excreted from mouth".

**Comment by johnwjudkins** [comment]
https://github.com/obophenotype/uberon/issues/2863

**Comment by johnwjudkins** [comment]
VEuPath's ontology is no longer in active development, so I'm not opposed to closing this, but feel free to keep it open if there is any interest.

**Comment by ddooley** [comment]
We'll need an active proponent/ontology to push this request forward, so closing unless someone wants to step forward to reopen.
