### ISSUE TITLE
embryonic or  in ovo study design

### ISSUE THREAD

**Issue by masciam** [obi-ontology/obi#1690]
Embryonic  (vertebrates) or in a  fertilized egg study design are considered in vivo or should have a separated category?

**Comment by sebastianduesing** [comment]
Thanks for asking about this, and apologies for the delay—I've just realized we never responded to this after we discussed it on a dev call in May. As long as a study is being performed on a living organism, it is in vivo, so if the study is being performed on a living fertilized egg or embryo (as opposed to, for example, a study performed on a preserved embryo), that study is in vivo.

We'd be happy to create terms for _in ovo_ or embryonic study design if there's a need for those terms specifically. Just let me know if that would be helpful.

**Comment by ddooley** [comment]
Closing now until someone needs to put a "in ovo or embryonic study design" term forward.
