### ISSUE TITLE
README links to GitHub wiki instead of the OBI homepage for documentation

### ISSUE THREAD

**Issue by StroemPhi** [obi-ontology/obi#1696]
Should the link to the documentation in https://github.com/obi-ontology/obi/blob/master/README.md?plain=1#L11 be changed to resolve to http://obi-ontology.org/docs/?

**Comment by jamesaoverton** [comment]
I forget what's the most up-to-date. @ddooley do you remember?

**Comment by ddooley** [comment]
I'm at a loss to see what documentation links are in https://github.com/obi-ontology/obi/blob/master/README.md?plain=1#L11 in the first place? What line(s)?

**Comment by StroemPhi** [comment]
L11 of the README as well as http://obi-ontology.org/ link to https://github.com/obi-ontology/obi/wiki for further documentation. The wiki pages are mostly from 2018. Most of their content still holds true, as far as I can tell from an outsider POV. But if I understand the comments from @jamesaoverton on Slack correctly, http://obi-ontology.org/docs/ should be the point of entry. Maybe adding a link there to the ?older? wiki might be good?
