### ISSUE TITLE
New RO "measures characteristic" applied to assay and COB characteristic

### ISSUE THREAD

**Issue by ddooley** [obi-ontology/obi#1704]
Related to "assay" definition (related to latest change proposed in https://github.com/obi-ontology/obi/issues/1683), RO is likely getting a "measures characteristic" relation (see https://github.com/oborel/obo-relations/issues/658) between an assay and a COB characteristic.  Now, COB [characteristic](http://purl.obolibrary.org/obo/COB_0000502) is a recasting of "[specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000016)".  

So "characteristic" covers not only characteristics of material entities at time t or over some duration, but also of abstract things like roles (e.g. how frequently they are played), or as I recall, processes or occurrents related to material things, like flooding level rate of change.  Is that ok?  Does latest proposed assay definition need to be changed in this regard?

"A planned process that has the objective to produce information about a material entity (the evaluant) by examining it."

It seems the definition doesn't restrict the spatial-temporal scope of the material entity being examined (and its relations to other entities), so no change needed?

**Comment by bpeters42** [comment]
I am very much in favor to leave the definition as is. 

So I hate raising the caveats: The thing that is new about COB: characteristic is not that it includes roles, functions, or dispositions. But that it also includes the vaguely defined 'process profiles'. Something like the frequency of heartbeats in a specific time interval. Which presumably is not an intrinsic property of the heart. But time-dependent, and impacted by time-dependent factors. I am sure there are better examples. 

But I can't think of an example where we have an assay that does not have a material that is being investigated as the evaluant. In the above example, that would be the heart for which the beating is measured. 

We should not let edge cases drive our development. So I would strongly support Damions proposal to leave this as is.

**Comment by ddooley** [comment]
Closing this now as no change needed.
