### ISSUE TITLE
Suggestion of definition modification for OBI_0003366: organism diagnostic process

### ISSUE THREAD

**Issue by pfabry** [obi-ontology/obi#1710]
The term is currently defined as: "A drawing a conclusion based on data that involves the interpretation of data about a given organism (human, animal, or plant) and the assertion to the effect that the organism has a disease, disorder, or syndrome of a certain type, or none of these as output."

1. This seems to exclude diagnosing a pathological process such as a myocardial infarction or a seizure.
2. This seems to be applicable only to currently present disease, disorder, or syndrome, but diagnosis are regularly about past conditions.

Therefore the definition might be updated as follows: "A drawing a conclusion based on data that involves the interpretation of data about a given organism (human, animal, or plant) and **has as output** the assertion to the effect that the organism has **or had** a disease, disorder, or syndrome of a certain type; **or is undergoing or underwent a pathological process of a certain type;** or none of these."

**Comment by jamesaoverton** [comment]
Discussed on the OBI dev call 2023-07-10. The core issue seems to be about OBO-level alignment on disease modelling, e.g. https://github.com/OBOFoundry/COB/pull/226. We would prefer to wait for that to be resolved in COB before making deeper changes to OBI.

We will include the past-tense in the definition: "A drawing a conclusion based on data that involves the interpretation of data about a given organism (human, animal, or plant) and the assertion to the effect that the organism has **or had** a disease, disorder, or syndrome of a certain type, or none of these as output."
