### ISSUE TITLE
NTR :  Illumina NextSeq 1000

### ISSUE THREAD

**Issue by Anoosha-Sehar** [obi-ontology/obi#1711]
Hi, we need this term as a part of the AMR-GRDI specifications. 

editor preferred label: Illumina NextSeq 1000

alternative terms: NextSeq 1000

textual definition: =**DNA sequencer which is manufactured by the Illumina corporation using sequence-by-synthesis chemistry that fits on a benchtop and uses P1 and P2 flow cells.**
definition source: [https://www.illumina.com/systems/sequencing-platforms/nextseq-1000-2000.html](https://www.illumina.com/systems/sequencing-platforms/nextseq-1000-2000.html)

Parent term: DNA Sequencer

Requester Ontology: GENEPIO

Term editor: https://orcid.org/0000-0001-5275-8866

**Comment by sebastianduesing** [comment]
Hi, thanks for submitting this NTR. Sorry for the delay on this—the OBI dev calls paused over the summer, and we're just now getting caught up on issues. We discussed this one on the OBI dev call yesterday (09.18.2023) and I've just submitted a PR for this (#1731).

**Comment by Anoosha-Sehar** [comment]
Okay, great! Thank you very much, @sebastianduesing!!
