### ISSUE TITLE
MERFISH addition to OBI

### ISSUE THREAD

**Issue by ropelews** [obi-ontology/obi#1724]
**editor preferred term**: Multiplexed Error-Robust Fluorescence in situ Hybridization 
**alternative terms:** MERFISH
**textual definition** 
A highly multiplexed single-molecule imaging method using combinatorial FISH labeling with error resistant encoding schemes. 
**definition source for the textual definition** https://doi.org/10.1126/science.aaa6090, https://en.wikipedia.org/wiki/Fluorescence_in_situ_hybridization#MERFISH
**logical definition (or parent term)** http://purl.obolibrary.org/obo/OBI_0003094
**ontology term requester**: Brain Image Library (www.brainimagelibrary.org)

**Comment by sebastianduesing** [comment]
Hi, and thanks for submitting this NTR! We discussed this on our 09.18.2023 development call, and I will be making a PR for this term this week. I'll follow up once that's done.
