### ISSUE TITLE
Addition of chemical roles and precursor role

### ISSUE THREAD

**Issue by cameronmore** [obi-ontology/obi#1727]
Hello, I would like to recommend that 'precursor role' be added to the ontology, as a compliment and sibling to 'solvent role' and 'reagent role'. Solvents and reagents work with precursors to product end products. The analogy of a table being produced by wood, nails, and a hammer is like the process of synthesizing a certain chemical--the wood is the precursor, the core component that becomes the main part of the end product, but it needs reagents and solvents (hammer and nails) to be crafted in just the right way.

A draft definition could be 'a chemical which serves as the core part of a chemical production process, upon which other chemicals act upon, like reagents and solvents.'

It also might be worth adding a class called 'chemical role' which is a role born by a chemical in some planned process. A reagent is a reagent in one process but may be a precursor in another, hence why its a role and not disposition, though it acquires this role because of its disposition to act in specific ways.

Thank you!

**Comment by ddooley** [comment]
Discussed Sept 11 OBI curation zoom. For parent class, suggest creating a "reactant role" in OBI as parent term rather than "chemical role" (which has different semantics in ChEBI).
Sebastian will work on a proposal here.

**Comment by cameronmore** [comment]
Thank you for the timely response!
