### ISSUE TITLE
synthesis

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#173]
def: the construction of a biomaterial from simpler biomaterials

this has no child terms, given this general definition it should have some e.g. PCR. Was this intended to convey bio or chemical synthesis or both?

Reported by: helenp

Original Ticket: [obi/obi-terms/173](https://sourceforge.net/p/obi/obi-terms/173)

**Comment by jamesaoverton** [comment]
I think this was implemented by http://purl.obolibrary.org/obo/OBI_0600040
