### ISSUE TITLE
NTR: water filtration

### ISSUE THREAD

**Issue by Anoosha-Sehar** [obi-ontology/obi#1743]
Hello, we need this term as a part of the AMR-GRDI specifications.

editor preferred label: water filtration

textual definition:  A filtration process which removes or reduces the concentration of particulate matter, including suspended particles, parasites, bacteria, algae, viruses, and fungi, as well as other undesirable chemical and biological contaminants from contaminated water using a water filter to produce safe and clean water.

Parent term: filtration

definition source: https://www.sciencedirect.com/topics/chemical-engineering/water-filtration 

Requester Ontology: GENEPIO

Term editor: https://orcid.org/0000-0001-5275-8866 
 
 Note: We are not attached to the definition, it's just to help in the curation process.

**Comment by DanBerrios** [comment]
Discussed on call 02/05/24: 

textual definition: A filtration process of water intended to remove or reduce the concentration of particulate matter, such as suspended particles, parasites, bacteria, algae, viruses, and fungi, as well as other undesirable chemical and biological contaminants.

@Anoosha-Sehar  Please confirm this re-write is ok.

**Comment by Anoosha-Sehar** [comment]
Hey @DanBerrios, Yes, the revised definition looks appropriate. 
Thank you very much!!

**Comment by bpeters42** [comment]
@sebastianduesing will create a pull request
