### ISSUE TITLE
Map to Emerald Cloud Laboratories (ECL) ontology

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1744]
[feel free to close if this is out of scope and not in the immediate area of interest for OBI]

ECL is a remotely operated research facility that handles all aspects of daily lab work — method design, materials logistics, sample preparation, instrument operation, data acquisition and analysis, troubleshooting, waste disposal:

https://www.emeraldcloudlab.com/

See this video: https://www.emeraldcloudlab.com/how-it-works/command/

ECL has what could be called an ontology (based on Wolfram Alpha Data Framework, not OWL), but it's more like a schema.org-style ontology.

https://www.emeraldcloudlab.com/documentation/

You can see the upper level classes and subtypes here:
https://www.emeraldcloudlab.com/documentation/types/

"objects" are either instances or value sets:

https://www.emeraldcloudlab.com/documentation/objects/

Some of this is in OBI territory:

<img width="419" alt="image" src="https://github.com/obi-ontology/obi/assets/50745/73627eb8-94d6-4732-8005-d959d7b966c3">

WDF also has the notion of Functions, for ECL these may often map to planned processes
https://www.emeraldcloudlab.com/helpfiles/aliquot

I think a lot of this is a different way of thinking than a realist OBO ontology. Although it could be argued that this is as real as it gets - imagine instantiating OBI objects and then shipping them off to a cloud lab to perform your protocol...

I have no specific use case for a mapping yet, but it seems not engaging and aligning is a missed opportunity

**Comment by bpeters42** [comment]
Automated (robot) science and ontologies for them have been part of OBI since its foundation (Larissa Soldatova contributed based on her work here: https://pubmed.ncbi.nlm.nih.gov/16873508/). If there is interest by these guys and they want to contribute, that is awsome, but we don't have bandwidth to reaching out to something like this.
