### ISSUE TITLE
MIREOT of EFO terms

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#176]
EFO is an application ontology developed by James, Helen and Jie for describing microarray datasets. We have mapped gene expression annotation to Chebi, Disease Ontology, NCIT, FMA, Brenda and some organism specific ontologies. We have a list of ~1000 terms which are candidates for the MIREOT process and which represent nodes in EFO that are mapped to annotations. 

The list of annotations and the ontology ids they map to are attached to this ticket. Thanks for Alan for providing and running code to get the mappings.  The EFO terms represent both experimental variables and also sample annotations. Possible problems will be deciding on two sets of parents in OBI, what to do when a term is not present in an obvious source ontology e.g. some terms come from NCI or UMLS only.

http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/spreadsheets/in/efo-terms-cited.txt - term list

Reported by: helenp

Original Ticket: [obi/obi-terms/176](https://sourceforge.net/p/obi/obi-terms/176)

**Comment by turbomam** [comment]
EFO has some useful terms. Need to be careful about importing them as-is, since EFO logic might require remodeling into OBI practices.  May want to redefine or create a new term.
