### ISSUE TITLE
create an individual that can be inferred as an instance of albumin free serum

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1767]
There was some discussion about 'albumin-free serum' in last-week's OBI meeting. See
- https://github.com/obi-ontology/obi/pull/1762

Is subClassOf `'has part' only (not (albumin))` necessary and sufficient to define 'albumin-free serum'. As a supplement to the discussion, I want to explore whether an individual could be created that does not assert the 'albumin-free serum' type but could be inferred to be a 'albumin-free serum'.

Some relevant classes:
- blood serum specimen: OBI:0100017 
- albumin-free serum: OBI:0003652 

See branch `albumin-free-serum-instance`

**Comment by turbomam** [comment]
- albumin: PR:000003918
- leptin: PR:000009758

**Comment by turbomam** [comment]
```
'blood serum specimen'
 and ('has part' some albumin)
```

**Comment by turbomam** [comment]
Neither of those individuals above satisfy 

```
'blood serum specimen'
 and ('has part' only albumin)
```

**Comment by turbomam** [comment]
Neither does this, at least with ELK

```ttl
<http://example.org/bsswoa_via_type> rdf:type owl:NamedIndividual ,
                                              obo:OBI_0100017 ,
                                              [ rdf:type owl:Restriction ;
                                                owl:onProperty obo:BFO_0000051 ;
                                                owl:allValuesFrom obo:PR_000003918
                                              ] ;
                                     rdfs:comment "Blood serum specimen with albumin only via type" .
```

----

```'blood serum specimen' and ('has part' only albumin)```

**Comment by jamesaoverton** [comment]
I think the axiom `'has part' only (not (albumin))` is at least a bit useful, for two reasons. First, we can assert that an instance `X has type 'albumin free serum'` and `X 'has part' some albumin`, and the reasoner will tell use there's a problem. Second, the axiom is pretty good documentation for a human.

I think you got what you wanted from this issue, so I'm going to close. But feel free to reopen.
