### ISSUE TITLE
Add a concept to represent ring trials

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1768]
A ring trial is an experiment to determine reproducibility by performing the same experiment under different conditions in different laboratories. See for example https://eco-fab.org/about-ecofab-initiative/

I think this is probably best represented as a study design in OBI. I don't think there is a need to create shadow classes under planned process. It may even be best represented as a property of a study.

I can make a PR if someone points me at the best exemplar for this kind of thing.

**Comment by bpeters42** [comment]
Talked about on the OBI call 4/15. Sebastian will take a look and Jennifer will email a colleague that conducts such trials.

**Comment by bpeters42** [comment]
Definition: "ring trial design" = A study design with the objective of establishing the reproducibility of an experimental approach by performing experiments in different laboratories under the same conditions and comparing the experimental outcomes." 

Example: Establishing the sensitivity and specificity of an instrument to detect the presence of mercury in a specimen by sending the instrument, protocols, and a set of (blinded) specimens with known presence of mercury to four labs, and comparing the results. 

@cmungall - any edits?

**Comment by bpeters42** [comment]
Will add this term as suggested above in 7 days if we don't hear otherwise.

**Comment by cmungall** [comment]
Looks good to me!
