### ISSUE TITLE
generation of genetic mutations

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#177]
Hi Alan,
Do you have any thoughts about how the Mutation Type enumeration from BIRNlex \(http://bioportal.bioontology.org/visualize/29684/birnlex\_7023\) would exist in NIFSTD?

I'm forwarding the whole thread.

Thanks,
Fahim

You can view these classes through bioportal link:
\---------- Forwarded message ----------
From: Maryann Martone &lt;maryann@ncmir.ucsd.edu&gt;
Date: Wed, Jul 29, 2009 at 8:55 PM
Subject: Re: Enumeration Classes: TaxonRank, Maturation stage, Mutation Type
To: Chris Mungall &lt;cjm@berkeleybop.org&gt;
Cc: Sarah Maynard &lt;smaynard@ncmir.ucsd.edu&gt;, Stephen Larson &lt;slarson@ncmir.ucsd.edu&gt;, Fahim Imam &lt;smtifahim@gmail.com&gt;, neurolex@googlegroups.com

Thanks Chris.  We'll contact Alan about the Mutation Type enumerations 

On Jul 29, 2009, at 5:12 PM, Chris Mungall wrote:

MutationType:

This is a nice comprehensive list of mutation types. SO already has sequence\_variant and chromosome\_variation. Some of these might belong in SO, although some are experimental artefacts and might better live in OBI.

Alan said:

Hi Imam,

I agree with Chris that a number of these terms actually describe
protocols/objectives for inducing mutation, e.g. Chlorambucil induced
mutation:"mutation induced by treatment with the chemical mutagen
chlorambucil"

I think these would be modeled as combinations of objectives \(to
introduce a genetic mutation, for example\) and processes, in which
materials were treated in certain ways \(material transformations,
adding material entity to target\)

A quick review says these -&gt; obi \(marked +. No + before those that aren't OBI\)

\+ Chemically induced mutation
\+ Chlorambucil induced mutation
Chromosomal aberration
Chromosomal rearrangement
\+ Cre/Flp-mediated transgenic insertion mutation
Deletion mutation
Duplication mutation
\+ ENU induced mutation
\+ Floxed/Frt targeted mutation
\+ Gene Trap mutation
Insertion mutation \(ambiguous - can be natural or experimental -
latter would be OBI\)
Inversion mutation
\+ Knock-in targeted mutation
\+ Knock-out targeted mutation
\+ Other chemically induced mutation \(we don't have "other" classes
typically - one annotates to the more general class, or explicitly
states which types it is not\)
Overexpression mutation \(ambigous - can refer to objective, or can be
result of natural mutation\)
Radiation induced mutation \(ambiguous - can be natural or
experimentally induced\)
\+ Random gene disruption transgenic insertion mutation
\+ Randomly expressed transgenic insertion mutation
\+ Reporter targeted mutation
Robertsonian translocation mutation
Spontaneous mutation
\+ Targeted mutation
\+ Transgenic insertion mutation
Translocation mutation
\+ Transposase-mediated transgenic insertion mutation
Transposition mutation
Wild-type mutation \(oxymoron?\)

Reported by: alanruttenberg

Original Ticket: [obi/obi-terms/177](https://sourceforge.net/p/obi/obi-terms/177)

**Comment by hectorguzor** [comment]
Discussed on OBI call 2023-03-20: Sorry for the lack of activity on this issue. we are in the process of closing old issues. If these terms are still needed, please reopen them as a new issue tracker item.
