### ISSUE TITLE
OBI_0001185 "selectively maintained organism" includes strain but strains are not always selectively maintained

### ISSUE THREAD

**Issue by DanBerrios** [obi-ontology/obi#1770]
http://purl.obolibrary.org/obo/OBI_0001185

Definition: An organism that is bred to have some uniform behavioral, morphological, physiological, or genetic characteristics with similarly bred organisms
Annotations
•	definition editor: Bjoern Peters, Helen Parkinson, Philippe Rocca-Serra, Jie Zheng, Chris Stoeckert
•	alternative term: cultivar; strain; ecotype
•	definition source: MO_9 StrainOrLine, MO_71 Ecotype, MO_124 Cultivar
•	has curation status: metadata complete

The use of the words "selectively maintained" and "An organism that is bred to have..." implies that humans are taking some actions (maintaining or breeding) organsims to create this class of organism....  However, there are certainly "strains" of organisms that no one has bred and that instead just come about through natural, non-anthrogenic means (e.g., many respiratory virus strains). For the Space Life Sciences Ontology, we preferred the definition of "strain" from NCIT:strain:

Term IRI: http://purl.obolibrary.org/obo/NCIT_C14419
Definition: A population or type of organisms that is genetically different from others of the same species and possessing a set of defined characteristics. [Definition Source: NCI]
 
...even though the phrase "genetically different" is outdated now that we know more about genetics and genetic differences between individuals.  We got passed the outdated phrase because members of strains are still assumed to have more in common "genetically" with other members of the strain than with those of other strains...

Our suggestion would be to rename this class (back?) to "strain" or else maybe something like "genetically similar members of a species" (awful wordy), and alter the definition to:

Definition: A group of genetically similar organisms that often all share some behavioral, morphological, or physiological  characteristics as well

**Comment by DanBerrios** [comment]
If you want to assign this to me, I can lead the discussion on this...

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2024-03-18. Some notes:

- 'strain' rank in NCBITaxon is widely used, but had no definition and a bad identifier: http://purl.obolibrary.org/obo/NCBITaxon_strain
- there is a "taxrank" ontology in OBO, which has a bunch of taxonomy ranks but does not have 'strain': http://obofoundry.org/ontology/taxrank.html
- Population and Community Ontology has various 'collection of organism' terms http://purl.obolibrary.org/obo/PCO_0000000 but does not have 'strain'

Bjoern suggests this distinction:

- NCBI Taxon for natural organism evolutionary classification
- PCO for populations of organisms in the wild
- OBI for inbred organisms for experiments
- VBO has breeds of animals

**Comment by bpeters42** [comment]
Summarizing the conclusions: The general 'strain' concept is not in OBI's primary scope, so we will not create it here. It could be included in COB to coordinate the different classes mentioned above from different OBO ontologies. Closing the issue here.
