### ISSUE TITLE
NTR 'deionized water' and 'water deionization process' 

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#1772]
'water deionization process'  subClassOf OBI:0600014  'material component separation'

'deionized water' output of 'water deionization process'

'water deionization process' should explain processes typically used to deionize water and the expected output, possibly in terms of resistance to the flow of electricity

@jamesaoverton Should I also create an objective?  Should I this to obi-edit.owl, or should I use some templating approach?

**Comment by bpeters42** [comment]
Closing; Marke will add in ENVO.
