### ISSUE TITLE
NTR: single-nucleus methylcytosine and transcriptome sequencing assay

### ISSUE THREAD

**Issue by jenjou** [obi-ontology/obi#1785]
Preferred Term: single-nucleus methylcytosine and transcriptome sequencing assay
Synonyms: snmCT-seq
Definition: A multiomic method to measure the cytosine DNA methylation and gene expression signature of single cells.
Relevant info: https://www.biorxiv.org/content/10.1101/434845v1
Parent Term: OBI:0001177 (RNA sequencing assay) and OBI:0001266 (DNA methylation profiling by high throughput sequencing assay)

**Comment by DanBerrios** [comment]
We are the process of re-organizing our sequencing-related assays.  We could add this term sooner rather than later, but its placement in the ontology could shift later as a result. @jenjou Would you prefer us to wait until that reorg is done, or do  you need this term more urgently? @jenjou

**Comment by jenjou** [comment]
I think having an official OBI term ID is more important to us than its exact placement within the ontology. However, we (IGVF Consortium) have set up a placeholder for internal use in the meantime, so we can wait as needed. If it would make your development process easier to complete the reorganization before adding new terms, that seems OK with me.

**Comment by bpeters42** [comment]
Discussed on 7/8 call; let's try to create a class and then re-arrange it with everything else. @jenjou to clarify single nucleus vs. cell and update definition.

**Comment by jenjou** [comment]
I think there was some confusion on my part, since the linked Biorxiv preprint describes both a single cell and single nucleus version of the assay. Here I would just like to request the single nucleus type for now, so I would change the description to:

> A multiomic method to measure the cytosine DNA methylation and gene expression signature of single nuclei.

**Comment by DanBerrios** [comment]
For the snmCT assay, the input is both nuclear DNA and RNA.  (Same for scmCT).  We discussed that we should declare the parent to be DNA methylation profiling by high throughput sequencing assay, but also add an axiom to have it classified under RNA-seq/transcriptome profiling assay.
