### ISSUE TITLE
Make language tags consistent

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#1793]
Half the OBI definitions have lang=en, the others are plain literals/strings

```
➜  ontology git:(master) ✗ grep IAO_0000115 obi-edit.owl | grep -c lang=
656
➜  ontology git:(master) ✗ grep IAO_0000115 obi-edit.owl | grep -vc lang=
702
```

I don't think there is OBO guidance but I think intra-ontology consistency is always good, it seems your intent is to be explicit, I think it would be clearly safe to auto-convert all definitions to lang=en

**Comment by turbomam** [comment]
Background from @jamesaoverton 
- there used to be a plain RDF literal but now there are only language-tagged literals and datatype-tagged literals. A literal that has no explicit language or datatype tag is implicitly an xsd:string typed datatype literal
- adding a tag in Protege takes extra clicks so a lot of people don't do it

**Comment by turbomam** [comment]
@cmungall is explicitly calling out definitions, but this is equally applicable to the object of other triples

This work will need to be applied to inputs other than obi-edit, like ROBOT templates

I can help

**Comment by turbomam** [comment]
Attendees in today's meeting agree with the content of this PR and appreciate the clever implementation. The way Dragon AI modified the tab characters make break the expectations of the ROBOT template format.

**Comment by turbomam** [comment]
finish this PR on definitions and start another one for labels.
