### ISSUE TITLE
New term: NovaSeq X

### ISSUE THREAD

**Issue by oquendoM** [obi-ontology/obi#1802]
**editor preferred term:** NovaSeq X Series
**alternative terms:** NovaSeq X System, NovaSeq X, NovaSeq X Plus
**textual definition:** The NovaSeq X and NovaSeq X Plus are sequencers with three flow cell types manufactured by Illumina. The NovaSeq X provides an output of up to 8 Tb (26-52 billion reads per run), while the NovaSeq X Plus doubles this capacity with its dual flow cell configuration (up to 16 Tb and 52-104 billion reads per run). The sequencer utilizes XLEAP-SBS chemistry, advanced reagents built upon proven Illumina SBS, which enables faster and more accurate sequencing.
definition source for the textual definition: https://emea.illumina.com/systems/sequencing-platforms/novaseq-x-plus.html
**logical definition (or parent term):** DNA sequencer (http://purl.obolibrary.org/obo/OBI_0400103)
**example of usage:** To record with which machine a DNA or RNA sample was sequenced.
**term editor:** Morgana Barroso Oquendo

**Comment by mgiglio99** [comment]
Discussed on 7/29 call
Thanks for this term request. We suggest that it would be best to have separate terms for each of NovaSeq X and NovaSeq X Plus since they have a significant difference from each other.
Could you split this out into those two with corresponding definitions.

**Comment by oquendoM** [comment]
Hi, sure!

editor preferred term: **NovaSeq X**
alternative terms: NovaSeq X System, NovaSeq X Series
textual definition: The NovaSeq X is a sequencer with three flow cell types manufactured by Illumina. The NovaSeq X provides an output of up to 8 Tb (26-52 billion reads per run). The sequencer utilizes XLEAP-SBS chemistry, an advanced version of Illumina's sequencing by synthesis (SBS) technology, which enables faster and more accurate sequencing.
definition source for the textual definition: https://emea.illumina.com/systems/sequencing-platforms/novaseq-x-plus.html
logical definition (or parent term): DNA sequencer (http://purl.obolibrary.org/obo/OBI_0400103)
example of usage: To record with which machine a DNA or RNA sample was sequenced.
term editor: Morgana Barroso Oquendo

editor preferred term: **NovaSeq X Plus**
alternative terms: NovaSeq X System, NovaSeq X Series
textual definition: The NovaSeq X Plus is a sequencer with three flow cell types manufactured by Illumina. It features a dual-flow cell configuration, allowing to reach an output of up to 16 Tb (52-104 billion reads per run). The sequencer utilizes XLEAP-SBS chemistry, an advanced version of Illumina's sequencing by synthesis (SBS) technology, which enables faster and more accurate sequencing.
definition source for the textual definition: https://emea.illumina.com/systems/sequencing-platforms/novaseq-x-plus.html
logical definition (or parent term): DNA sequencer (http://purl.obolibrary.org/obo/OBI_0400103)
example of usage: To record with which machine a DNA or RNA sample was sequenced.
term editor: Morgana Barroso Oquendo

**Comment by sebastianduesing** [comment]
Thanks for the quick response! I've created a pull request to add these two terms.
