### ISSUE TITLE
administer substance in vivo

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#189]
Summary of email discussion 11/12 Au 09

administer substance in vivo is classified under animal care. Problems:

The output of an 'administer substance in vivo' is not always an 
organism - assuming this implies a live organism. This could therefore 
be replaced by material entity.

The text definition states that - 'a substance is intentionally given to 
an organism through a specified route of administration'

\- the specified route is not true of the 'administer substance in vivo' 
parent class, only the subclasses and this should be removed from the 
definition.

HP thinks this class should be a child of 'adding material entity into a target'  and not animal care.

Reported by: helenp

Original Ticket: [obi/obi-terms/189](https://sourceforge.net/p/obi/obi-terms/189)

**Comment by turbomam** [comment]
Looks like this is now a subclass of 'adding a material entity into a target', OBI_0000274

**Comment by jamesaoverton** [comment]
Right, see http://purl.obolibrary.org/obo/OBI_0600007

I'll close this issue now.
