### ISSUE TITLE
cross species anatomy

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#197]
Comment in the manuscript: We need to call out our stand on species neutral anatomy somehow. Helen had some work on this I understand. Otherwise we should note that we would like a solution for this. 

Reported by: bpeters42

Original Ticket: [obi/obi-terms/198](https://sourceforge.net/p/obi/obi-terms/198)

**Comment by jamesaoverton** [comment]
We now use UBERON for cross-species anatomy.
