### ISSUE TITLE
BIRN placeholder term remapping

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#218]
These are terms in use in Birnlex which they want to have OBI ids updated for. Contact is Fahim Imam / Maryann.

Reported by: bpeters42

Original Ticket: [obi/obi-terms/221](https://sourceforge.net/p/obi/obi-terms/221)

**Comment by hectorguzor** [comment]
Discussed on OBI call 2023-03-20: Sorry for the lack of activity on this issue. we are in the process of closing old issues. If these terms are still needed, please reopen them as a new issue tracker item.
