### ISSUE TITLE
nucleic acid sequence

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#224]
nucleic acid sequence: A data item that is is a string of characters \(e.g., A, G, C,T, U, N, R, Y, etc.\) and represents the order of nucleotides found somewhere in nature or synthesized.

This term is needed by InfluenzO.
Thanks,
Melanie

Reported by: mcourtot

Original Ticket: [obi/obi-terms/227](https://sourceforge.net/p/obi/obi-terms/227)

**Comment by hectorguzor** [comment]
Discussed on OBI Call 2023-03-20: OBI has http://purl.obolibrary.org/obo/OBI_0000973 sequence data term. we will go ahead and close this issue.
