### ISSUE TITLE
executes relation

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#227]
Proposal to create a shortcut relation'executes' between a participant of a planned process and the planned process. It should be the logical equivalent of

"the entity that is bearer of the concretization of the plan specification that is realized in the planned process", 

The reason for introducing this \(or other shortcut relations\) is to avoid the  otherwise 'overly baroque modeling' 

Priority 9 for the SIG paper; if this is not consensus immediately, the paper should avoid the relation and use the complex modeling instead, and the priority can be downgraded. 

Reported by: bpeters42

Original Ticket: [obi/obi-terms/230](https://sourceforge.net/p/obi/obi-terms/230)

**Comment by jamesaoverton** [comment]
Now defined by STATO and imported into COB: http://purl.obolibrary.org/obo/STATO_0000102
