### ISSUE TITLE
extra cellular /intra cellular physiology recording

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#238]
needs to have located\_in extra cellular region/ intra cellular region logical definition added. 

Reported by: helenp

Original Ticket: [obi/obi-terms/242](https://sourceforge.net/p/obi/obi-terms/242)

**Comment by hectorguzor** [comment]
Discussed on OBI call 2023-03-20: Sorry for the lack of activity on this issue. we are in the process of closing old issues. If these terms are still needed, please reopen them as a new issue tracker item.
