### ISSUE TITLE
replicon_function

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#26]
We identified the need for a term replicon\_function during a biomaterial call. This will help us define plasmids.
replicon\_function: borne by a DNA or RNA, realized as GO:0006260 mode\_of\_participation has\_input
inheres\_in some \(DNA or RNA\) 
realized\_as some \(GO:0006260\)

replicon = \(GO:0006260\) will be a bfo:process

Reported by: mcourtot

Original Ticket: "obi/obi-terms/26":https://sourceforge.net/p/obi/obi-terms/26

**Comment by turbomam** [comment]
Closed after review in OBI call, 18. December, 2017
Plasmid term already present in OBI (OBI_0000430)
