### ISSUE TITLE
plasmids (DNA and RNA)

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#27]
dna\_plasmid: dna and has\_function replicon\_function

see http://sourceforge.net/tracker/index.php?func=detail&aid=1894635&group\_id=177891&atid=886178 for replicon\_function

circular\_dna\_plasmid: dna\_plasmid and has\_quality circular \(PATO\)

on the same model, circular\_rna\_plasmid, linear\_dna\_plasmid, linear\_rna\_plasmid

Reported by: mcourtot

Original Ticket: "obi/obi-terms/27":https://sourceforge.net/p/obi/obi-terms/27

**Comment by turbomam** [comment]
Closed because dependent term request (has_function replicon_function) were closed.

@mcourtot feel free to reopen if relevant
