### ISSUE TITLE
Reagent role

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#279]
Reagent role will be removed and a defined class for reagent will be added instead under matieral entity. 
definintion is required, Alan notes:
part of the action - it will be a union of bears of some set of roles/functions

Reported by: jamesmalone

Original Ticket: [obi/obi-terms/285](https://sourceforge.net/p/obi/obi-terms/285)

**Comment by jamesaoverton** [comment]
'reagent' http://purl.obolibrary.org/obo/OBI_0001879
