### ISSUE TITLE
data sets, bundle for repository, investigation docs

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#303]
old definition of data set: A data set is an information content entity that is an aggregate of other data items that have something in common and are considered to form a unit and are packaged together for some purpose, for example depositing into a repository.

Chris wants to use the term data set to mean something more like a vector elements each of which are the same type. 

We still need a term that describes the repository bundle. We also need to see whether there is a distinction to be made between a bundle and "documentation of an investigation" a term Chris used, but which we don't currently have in the ontology.

Reported by: alanruttenberg

Original Ticket: [obi/obi-terms/309](https://sourceforge.net/p/obi/obi-terms/309)

**Comment by jamesaoverton** [comment]
If this is still needed, please reopen.
