### ISSUE TITLE
too generic labels for NMR instruments

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#315]
acquisition computer, autosampler, flow probe, flow high resolution probe, indirect detection probe. 

Review whether these labels are to generic and consider renaming.

I have seen these for NMR instruments but the same review is appropriate for other instrument labels

Reported by: alanruttenberg

Original Ticket: [obi/obi-terms/321](https://sourceforge.net/p/obi/obi-terms/321)

**Comment by jamesaoverton** [comment]
We have not had any other complaints about these labels in a decade, so let's leave them alone unless there is a specific need to change them.
