### ISSUE TITLE
chemical solution

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#333]
chemical solution def reads "A material entity that is made up of at least 2 scattered molecular aggregates, one playing the role of solvent and the other one playing the role of solute."
I think that would cover more than what we intend \(i.e. buffers\): blood serum may fall under there \(http://tinyurl.com/yemccw7, measuring proteins in blood serum\)

Reported by: mcourtot

Original Ticket: [obi/obi-terms/339](https://sourceforge.net/p/obi/obi-terms/339)

**Comment by jamesaoverton** [comment]
If there's specific proposal, please reopen.
