### ISSUE TITLE
inter-rater reliability

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#334]
It's under process now.
If it should be under process, this name is bad.
Is this supposed to be a data transformation? Or an investigation?

Reported by: alanruttenberg

Original Ticket: [obi/obi-terms/340](https://sourceforge.net/p/obi/obi-terms/340)

**Comment by jamesaoverton** [comment]
Currently 'inter-rater reliability objective' http://purl.obolibrary.org/obo/OBI_0200091
