### ISSUE TITLE
duplicate - acquisition, object acquisition

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#336]
object acquisitiion: an object acquisition is an acquisition of an object from an investigator, institution or vendor. Participant roles include source, destination, carrier, container, transaction record, payer...

acquisition: the process of obtaining a continuant from a source.

Reported by: alanruttenberg

Original Ticket: [obi/obi-terms/342](https://sourceforge.net/p/obi/obi-terms/342)

**Comment by jamesaoverton** [comment]
'material acquisition' http://purl.obolibrary.org/obo/OBI_0600010 is now a child of 'acquisition'
