### ISSUE TITLE
term request: administration of infectious agent to host

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#343]
please add the term "administration of infectious agent to host".  this term should be a subtype of "administration in vivo".  the suggested definition is: An administration in vivo in which the administered substance is an infectious agent and the target organism is a potential host of that agent.  thank you.

Reported by: lgcowell

Original Ticket: [obi/obi-terms/350](https://sourceforge.net/p/obi/obi-terms/350)

**Comment by sebastianduesing** [comment]
Fulfilled by http://purl.obolibrary.org/obo/OBI_1110007 "administration in vivo with infectious agent."

Closing.
