### ISSUE TITLE
yeast artifical chromosome vector

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#345]
this should be a child of 'chromosome' if we import that from another source
check where to get chromosome

Reported by: mcourtot

Original Ticket: [obi/obi-terms/352](https://sourceforge.net/p/obi/obi-terms/352)

**Comment by jamesaoverton** [comment]
'chromosome' is now imported from GO http://purl.obolibrary.org/obo/GO_0005694. If someone wants to add logic for that, please reopen.
