### ISSUE TITLE
CD8 receptor

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#353]
note reads "This term does not belong in ONTIE.  It should be imported from PRO, but there seems to be no appropriate term as of 08/17/2009."

Reported by: mcourtot

Original Ticket: [obi/obi-terms/360](https://sourceforge.net/p/obi/obi-terms/360)

**Comment by jamesaoverton** [comment]
The OBI term should be obsoleted and replaced by the PR term
