### ISSUE TITLE
chromatography devices

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#359]
column cartridge: note reads: "chromatography device, check on definition \!"
column cartridger: note reads "check on definition \!"
column chromatography detector: note reads "chromatography detector, defined class/xps"

Reported by: mcourtot

Original Ticket: [obi/obi-terms/366](https://sourceforge.net/p/obi/obi-terms/366)

**Comment by jamesaoverton** [comment]
I'll remove these curator comments.
