### ISSUE TITLE
DNA ligase

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#362]
note reads "5/22 Need to explore if there are GO / other classes exist that capture this. We need it now for cloning experiments"

Reported by: mcourtot

Original Ticket: [obi/obi-terms/369](https://sourceforge.net/p/obi/obi-terms/369)

**Comment by jamesaoverton** [comment]
Looks like we're using the PR term now http://purl.obolibrary.org/obo/PR_000023089
