### ISSUE TITLE
ELISPOT assay

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#366]
note reads "2/26/09: RESOLVE: we need to specify the produced substance that is desired to be detected. Analyte does not work, as this is not a concentration, and this is not present at the start of the assay."

Reported by: mcourtot

Original Ticket: [obi/obi-terms/373](https://sourceforge.net/p/obi/obi-terms/373)

**Comment by jamesaoverton** [comment]
I don't see that note on http://purl.obolibrary.org/obo/OBI_0600031 anymore
