### ISSUE TITLE
'activated' cells

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#394]
The IEDB used 'lymphoblast' for LPS blast, and other mitogen/cytokine activated cells. That term is now retired from the cell ontology, and it should be properly defined in terms of activation procedures etc. In that process, the distinction between cells and cell cultures should also be revisited. 

Reported by: bpeters42

Original Ticket: [obi/obi-terms/401](https://sourceforge.net/p/obi/obi-terms/401)

**Comment by jamesaoverton** [comment]
Should now be covered by the distinction between Cell Ontology and the Cell Line Ontology.
