### ISSUE TITLE
english/us spellings

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#399]
There are a bunch of words, particularly "ising"/"izing" that differ english to US. There is no consistency about which is chosen when there are both alternatives. figure out what to do

Reported by: alanruttenberg

Original Ticket: [obi/obi-terms/406](https://sourceforge.net/p/obi/obi-terms/406)

**Comment by jamesaoverton** [comment]
OBO policy is (now) US spellings for primary labels.
