### ISSUE TITLE
devices and instruments

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#406]
Hi all,
you all have probably discussed this for many months or years, but we newcomers need to jump in somewhere...

Currently, there are entities that one might commonly think of as instruments or devices as subclasses of 'processed material'. The definition of this class is: "Is a material entity that is created or changed during material processing."  One can argue that some devices and instruments do not meet these criteria of being created or changed. One idea is to have 'device' be a subtype of 'material entity' with a definition something like: "material entity that has\_function some function"
and 'Instrument' a subtype of 'device', whereby an 'instrument' is a device that participates in a planned process and has\_specified\_input and has\_specified\_output of a continuant \(since there can be inputs/outputs of information content entities such as a data set, or material entities such as cells\).

The subtypes of 'instrument' could be entities defined based on their participation in classes of planned processes and/or by the type of processed material.

This may seem very simplistic, please don't laugh.

Melissa Haendel and Carlo Torniai

Reported by: mellybelly

Original Ticket: [obi/obi-terms/413](https://sourceforge.net/p/obi/obi-terms/413)

**Comment by jamesaoverton** [comment]
If this issue is still relevant, please reopen.
