### ISSUE TITLE
laboratory

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#408]
Another naive request. all new terms.

'material\_entity'
\---'laboratory'   Def: material entity that performs research, provides services, or processes materials.
\------ 'core\_facility'  Def: laboratory that provides a service to personnel or organizations external to the core facility.
\-------'research\_facility'  Def: laboratory that only performs research \(eg. does not have a service provider role\).

Given these definitions, it might be the case that we would want to define or add proper roles for these classes, such as 'service provider role' and 'researcher role'. Questions are who can have these roles? Can a core facility and a person both have a 'service provider role'?

This is just the tip of the iceberg, please advise:-\).

Reported by: mellybelly

Original Ticket: [obi/obi-terms/415](https://sourceforge.net/p/obi/obi-terms/415)

**Comment by jamesaoverton** [comment]
Should be closed by #1436
