### ISSUE TITLE
Restrictions are needed to some RNA extraction process

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#492]
Some RNA extraction terms were added to OBI. Details on the tracker item
https://sourceforge.net/tracker/?func=detail&aid=2915152&group\_id=177891&atid=886178
All the definitions and restrictions are in a file attached to the tracker item.

Now nuclear/cytoplasmic/organellar/polyA RNA extraction process and RNA extract material entities are not linked to RNA origins or structure. It should be worked out.

Reported by: zhengj2007

Original Ticket: [obi/obi-terms/499](https://sourceforge.net/p/obi/obi-terms/499)

**Comment by jamesaoverton** [comment]
I think these have been added under 'RNA extraction': http://purl.obolibrary.org/obo/OBI_0666666
