### ISSUE TITLE
fasted subject / organism

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#494]
need to indicate physiological status of organism when representing some IUPAC clinchem analyte assays where the analyte is blood drawn from patients who underwent overnight fast.

generalization to organism other than human, could be applied to fasted cell and measurement carried on a supernatant medium.

See  related thread:
Re: \[IAO\] Laboratory test modeling using spreadsheet template

Reported by: proccaserra

Original Ticket: [obi/obi-terms/501](https://sourceforge.net/p/obi/obi-terms/501)

**Comment by sebastianduesing** [comment]
To be done: specify overnight fasting, include example of usage that states blood testing application. Discussed Jan 08 2024.
