### ISSUE TITLE
functional complementation assay

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#504]
functional complementation assay is an assay in the function of gene is demonstrated by restoring function \(usually by inseritng  a wild-type copy\)  of the gene in question in an organism known to be lacking a working version \(either via knock-out or knock-down using RNAinterfence for instance\)

Need to add associated/related assays:
yeast 2 hybrid, 
function disruption assay \(RNA interference....\)

Reported by: proccaserra

Original Ticket: [obi/obi-terms/513](https://sourceforge.net/p/obi/obi-terms/513)

**Comment by jamesaoverton** [comment]
We have 'yeast 2-hybrid assay' http://purl.obolibrary.org/obo/OBI_0001679. We don't have the suggest parent.
