### ISSUE TITLE
Single-Nucleotide-Resolution Nucleic Acid Structure Mapping 

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#505]
an assay which uses chemical or enzymatic agent to determine the secondary structure of nucleic acid sequence by obtaining information about backbone accessiblity and/or base-pairing at individual nucleotide position.

Request/collaboration with RNAO

Reported by: proccaserra

Original Ticket: [obi/obi-terms/514](https://sourceforge.net/p/obi/obi-terms/514)

**Comment by jamesaoverton** [comment]
I think we have this term: http://purl.obolibrary.org/obo/OBI_0001026
