### ISSUE TITLE
resolution/resolving power

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#506]
a dependent continuant describing the ability of an instrument or an experimental procedure to distinguish between 2 entities of interest.
examples:
In mass spectrometry, resolution is a measure of the ability to distinguish between two peaks of different mass-to-charge ratio, m/z.
In nucleic acid mapping assays, single nucleotide resolution indicates that the assay is able to provide information for individual nucleotide in a nucleic acid molecule

Collaboration with RNAO

Reported by: proccaserra

Original Ticket: [obi/obi-terms/515](https://sourceforge.net/p/obi/obi-terms/515)

**Comment by sebastianduesing** [comment]
Proceed as information content entity. Discussed January 08 2024.
