### ISSUE TITLE
librairies under recombinant vector

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#518]
MC: phage display library and cDNA library classify under recombinant vector - I think there is a tracker item for those - they have grain recombinant vector but are not is\_a

Jie: Yes. I added the restriction. It is "has\_grain" some "recombinant vector". Not "is\_a".

MC: Because they are output of recombinant vector cloning, which has a restriction has specified output recombinant vector, they get inferred under recombinant vector anyway. Maybe updating the specified output on the recombinant vector cloning process?

Reported by: mcourtot

Original Ticket: [obi/obi-terms/527](https://sourceforge.net/p/obi/obi-terms/527)

**Comment by zhengj2007** [comment]
The recommended logical axioms were added in two library terms.
