### ISSUE TITLE
OBI_0200199 mass spec and gc as datatransformation

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#533]
OBI\_0200199  class with rdfs:label 'gas chromatography mass spectrometry' is an asserted child of data transformation.

not logically defined
would require changing label -&gt; mass spectrometry spectrum analysis or something along those lines

Reported by: proccaserra

Original Ticket: [obi/obi-terms/542](https://sourceforge.net/p/obi/obi-terms/542)

**Comment by jamesaoverton** [comment]
Now a child of 'mass spectrometry analysis'
