### ISSUE TITLE
efficacy of treatment assay and T-cell assay

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#543]
Efficacy of treatment assay" and T-cell assay as a study design. This will done offline during the workshop

Reported by: helenp

Original Ticket: [obi/obi-terms/552](https://sourceforge.net/p/obi/obi-terms/552)

**Comment by jamesaoverton** [comment]
I think this now exists: http://purl.obolibrary.org/obo/OBI_0001507
