### ISSUE TITLE
hybridoma cell line and related process

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#554]
Need a new term as part of the antibody work. Should be a specified output of the related planned process 'B-cell hybridoma generation'.

Definition: something to the effect of -  fusing a specific antibody-producing myeloma \(B cell cancer\) cell that is selected for its ability to grow in tissue culture and for an absence of antibody chain synthesis. The antibodies produced by the hybridoma are all of a single specificity and are therefore monoclonal antibodies.

Talk to Bjoern.

Reported by: mellybelly

Original Ticket: [obi/obi-terms/566](https://sourceforge.net/p/obi/obi-terms/566)

**Comment by jamesaoverton** [comment]
We have 'establishing cell line' http://purl.obolibrary.org/obo/OBI_0001867 process, but haven't added specific types. Reopen if that's desired.
