### ISSUE TITLE
multi issues from review

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#567]
Fix very high level classes:
1\) Under GDC:
Sequence related stuff:
\- propose to rename the imported SO terms 'region' to 'property of sequence region'???, 'polypeptide' to 'polypeptide sequence', ...
\- 'secondary structure of sequence macromolecule' is under quality; should now be under GDC?

2\) Under 'spatial region'
\- 'interrogation point' should be a site, and 'jet\_in\_air\_flow\_chamber' seems to be a material entity \(the chamber\)

3\) Everything needs parentage review \(e.g. 'macromolecule' should be child of 'molecular entity'; all 'XXX document' should be child of document etc.\)

4\) Vote strongly to remove unused bfo classes \('spatial region', 'object boundary', 'object', 'object aggregate', 'fiat object part', and everything except 'processual entity'  from 'occurent'\). They are extremely confusing in conjunction with the OBI hierarchy.

Reported by: bpeters42

Original Ticket: [obi/obi-terms/579](https://sourceforge.net/p/obi/obi-terms/579)

**Comment by bpeters42** [comment]
Closing as this discussion is now in COB.
