### ISSUE TITLE
New Assays from EFO

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#576]
Attached is a spreadsheet with definitions of some assays that are in EFO that should live in OBI longer term. I've added some axiomatic info as well. 

Reported by: jamesmalone

Original Ticket: [obi/obi-terms/588](https://sourceforge.net/p/obi/obi-terms/588)

**Comment by sebastianduesing** [comment]
Closing now as many terms from the original sheet have been added to OBI. If there are any terms on the sheet that are still needed, please open a new NTR for those ones specifically.
