### ISSUE TITLE
has_member_of_organization and is_assigned_by relations

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#615]
In OBI, there is relation 'is member of organization' that relates person to organization. However, it has no inverse relation. Would like it is available in OBI when we want to relate an organization to a person. Propose relation 'has member of organization' with domain organization and range human being.

There could be many identifiers associated with one entity such as specimen. If we only use 'specimen identifier', it is hard to know which identifier refer to. Propose relation 'is assigned by' with domain 'symbol' which to distinguish different identifiers denote to same entity, such as 'specimen identifier' is assigned by organization and participates\_in material storage service, or participates\_in material transport service. In this case, we know that one specimen identifier is used by storage and one for transport.

Reported by: zhengj2007

Original Ticket: [obi/obi-terms/628](https://sourceforge.net/p/obi/obi-terms/628)

**Comment by jamesaoverton** [comment]
'has organization member' http://purl.obolibrary.org/obo/OBI_0001688
