### ISSUE TITLE
Misleading label for OBI_0302867 

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#634]
The class is labeled "predicted datum". That sounds be be defying the definition of "data item", plus it does not fit the definition of OBI\_0302867 which reads:
"A data item that was generated on the basis of a calculation or logical reasoning".
I propose changing the label. A discussion on the OBI Develop list today did not return any voice in favor of the name.
A name that was proposed was "calculated datum". There might be some issues with that, too, however, it is a far better label than "predicted datum"

Reported by: *anonymous

Original Ticket: [obi/obi-terms/648](https://sourceforge.net/p/obi/obi-terms/648)

**Comment by sebastianduesing** [comment]
Discussed at OBI call on 05.08.2023. OBI team decided to close issue due to lack of activity. If new issues/concerns come up, a new tracker item can be created.
