### ISSUE TITLE
"executes" as short cut relation

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#636]
the need:

currently, we need to state  &lt;planned process&gt; "realizes some \(concretizes some &lt;plan specification&gt;\)

the proposed solution \(simply to have a simpler/faster editing shorting for developers and an intuitive to users insight into OBI\):

executes  &lt;=&gt; realizes o concretizes 
with the following, domain "planned process" and range "plan specification"

Maybe extended to bridge between "planned process" and "directive information content entity"

Potential point of contention: investigation how it would behave when transitioning to BFO2.0

Reported by: proccaserra

Original Ticket: [obi/obi-terms/650](https://sourceforge.net/p/obi/obi-terms/650)

**Comment by StroemPhi** [comment]
I think this issue should be closed, as this relation exists in STATO already and is being reused in COB as pointed out by @zhengj2007's above issue link. See also: [STATO:0000102 in COB](https://www.ebi.ac.uk/ols4/ontologies/cob/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FSTATO_0000102?lang=en)

**Comment by StroemPhi** [comment]
https://github.com/obi-ontology/obi/issues/227 seems to be a duplicate of this issue
