### ISSUE TITLE
add relationship for RNA-seq assay to RNA-sequencing

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#648]
Update term RNA-seq assay \(OBI\_0001271\) should be a subclass of  RNA sequencing \(OBI\_0001177\)

Reported by: vsmalladi

Original Ticket: [obi/obi-terms/662](https://sourceforge.net/p/obi/obi-terms/662)

**Comment by zhengj2007** [comment]
Fixed. The RNA-seq assay (OBI_0001271) is inferred as subclass of RNA sequencing (OBI_0001177).
