### ISSUE TITLE
Add new objective for DNA replication

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#650]
Add new term for DNA replication timing assay:

term: nucleotide replication profiling feature identification objective
parent: molecular feature identification objective
description: A molecular feature identification objective that aims to identify features of  nucleotide replication

Reported by: vsmalladi

Original Ticket: [obi/obi-terms/664](https://sourceforge.net/p/obi/obi-terms/664)

**Comment by turbomam** [comment]
Speak up if you would like this reopened!
