### ISSUE TITLE
Wrong logical axiom of histology

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#652]
histology with one axiom:
'has part' some 
\('imaging assay'
and 'histological sample preparation'
and staining
and 'collecting specimen from organism'\)

I think we want to say, 
histology
'has part' some 'imaging assay'
and 'has part' some 'histological sample preparation'
and 'has part' some staining
and 'has part' some 'collecting specimen from organism'

rather than it has part of intersection of 
\('imaging assay'
and 'histological sample preparation'
and staining
and 'collecting specimen from organism'\)

Need to be fixed

Reported by: zhengj2007

Original Ticket: [obi/obi-terms/666](https://sourceforge.net/p/obi/obi-terms/666)

**Comment by zhengj2007** [comment]
issue has been fixed in OBI
