### ISSUE TITLE
Variable

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#662]
Following OBI call on June 10, 2013: need to have a container class for independent and dependent variable to enable specifying that 'study design' relate to variables.
NOTE:
has\_part relation should not be used to that linking as it causes reasoning problems when setting cardinalities

possibly need a new relation \(e.g. declares , range: variable, domain: study design

Reported by: proccaserra

Original Ticket: [obi/obi-terms/676](https://sourceforge.net/p/obi/obi-terms/676)

**Comment by sebastianduesing** [comment]
Discussed on January 08 2024.
