### ISSUE TITLE
comparative genomic hybridization by array and copy number variation profiling

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#665]
It should be some logical links between comparative genomic hybridization by array (http://purl.obolibrary.org/obo/OBI_0001393) and copy number variation profiling (http://purl.obolibrary.org/obo/OBI_0000537) since comparative genomic hybridization by array is  a technique to detect genomic copy number variations at a higher resolution.

Issue is found by Venkat (ENCODE project). I think we may create a new objective specification, 'copy number variation identification objective' (subClassOf 'molecular feature identification objective') and define 'copy number variation profiling' = assay and achieves_planned_objective some 'copy number variation identification objective'.

Reported by: zhengj2007

Original Ticket: [obi/obi-terms/679](https://sourceforge.net/p/obi/obi-terms/679)

**Comment by turbomam** [comment]
Speak up if you would like this reopened!
