### ISSUE TITLE
consistent representation of assay

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#667]
Latest version of OBI (SVN Revision: 3814) contains 631 assays. 452 assays have IEDB alternative labels. They should be created by IEDB group for IEDB project.

Most of assay terms were created using assay design pattern and contain following components:
- input material of assay
- output information content of assay
- device used in an assay
- objective of assay
- main processes of an assay
- evaluant role inheres in input material
- analyte role inheres in input material for an analyte assay

However, these components were represented differently in OWL. They should be represented consistently for classification and queries.

Three files attached. 
- OBI assays with axioms contains components listed above 
- Semantic representation of assay  with 3 use cases 
- Semantic representation of analyte assay with 4 use cases 

Reported by: zhengj2007

Original Ticket: [obi/obi-terms/681](https://sourceforge.net/p/obi/obi-terms/681)

**Comment by zhengj2007** [comment]
The assay harmonization work is complete.
