### ISSUE TITLE
In vivo, ex vivo

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#69]
AI from Vancouver workshop:

Biomaterial will attempt define in vivo, ex vivo etc as a defined class and see if this works, these may be at assay level not material level, and these will likely be processes. Assigned to: PRS

Reported by: jamesmalone

Original Ticket: "obi/obi-terms/69":https://sourceforge.net/p/obi/obi-terms/69

**Comment by jamesaoverton** [comment]
This should be resolved by the 'target environment' PR #1516
