### ISSUE TITLE
Intention of OBI_0000630 "hematology" term

### ISSUE THREAD

**Issue by obi-bot** [obi-ontology/obi#719]
On the 2015-01-26 call, while looking at #733, we noticed OBI_0000630 "hematology" and were wondering if the intention is to be an type of assay or a more general field of study.

If it is supposed to be an assay, we suggest appending "assay" to the label, and changing the has_specified_output to be "data item" rather than ICE (in line with planned changes from #733).

Reported by: jamesaoverton

Original Ticket: [obi/obi-terms/735](https://sourceforge.net/p/obi/obi-terms/735)

**Comment by jamesaoverton** [comment]
I think this was resolved long ago.
