### ISSUE TITLE
Generalize range of 'has specified value'

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#819]
'has specified value' (OBI_0001937) is a data property that defined as "A relation between a value specification and a number that quantifies it." and with range owl:real. An analogous data property is needed for numerical values as discussed on the April 10, 2017 OBI call. It was agreed that 'has specified value' should be made more general (range owl:thing) and applied to 'value specification'. More specific data properties such as 'has specified numerical value' can also be created as needed.

**Comment by bpeters42** [comment]
Call 5/1: 
Two step approach: 
1) Change label of http://purl.obolibrary.org/obo/OBI_0001937 to "has specified numeric value"
2) Create general property, as a parent of the above: "has specified value"
domain: value specification
range: LEAVE BLANK
Definition: A relation between a value specification and a literal. 
Editor note: This is not an RDF/OWL object property. It is intended to link a value found in e.g. a database column of 'M' (the literal) to an instance of a value specification class, which can then be linked to indicate that this is about the biological gender of a human subject.
