### ISSUE TITLE
please add class "case series study design"

### ISSUE THREAD

**Issue by hoganwr** [obi-ontology/obi#821]
suggested label "case series design"
suggested editor preferred term "case series study design"
suggested definition: "A study design that specifies (1) sampling only subjects who have experienced a particular event (outcome or exposure), , in a manner that does not permit absolute risk calculation, and (2) the specific data to be collected on each subject".
suggested comment: "The subjects are also called 'cases' hence the name of the design.  It is differentiated from a cohort study in that absolute risk of the outcome/exposure cannot be calculated because the sampling process is not sufficiently rigorous to do so."

More info:
https://www.ncbi.nlm.nih.gov/pubmed/22213493

Relevant quote from above:
"We propose that a cohort study is one in which sampling is based on exposure, follow-up is part of the study, and ab- solute risks can be calculated. A case series is a study in which only patients with the outcome are sampled (either those who have an exposure or those who are selected without regard to exposure), which does not permit calculation of an absolute risk (Table 2)."

**Comment by bpeters42** [comment]
Discussed on the 5/1 call. Based on our understanding, we want to propose an improved definition, let us know if it is accurate: "A study design that samples only subjects who have experienced a particular event (outcome or exposure). Such a design, in contrast to a cohort study, does not permit calculation of absolute risk as non-case subjects are not included.". 

We thought this was better as the first half sentence between 1 and 2 seemed to indicate that it is possible to recruit only cases and also calculate absolute risk. and the item following (2) seemed to be generic.

**Comment by hoganwr** [comment]
Looks great!  Thank you!

Bill

**Comment by hoganwr** [comment]
Just following up on this term request.  The tracker looks quite busy, but we could really use this class in ongoing work that motivated it in the first place.  Thanks for considering.

**Comment by ddooley** [comment]
Its heading for obi-edit now.

**Comment by hoganwr** [comment]
Great to hear - thanks for the update!

**Comment by ddooley** [comment]
just added to pull request.
