### ISSUE TITLE
NTR: database extract, transform, and load process

### ISSUE THREAD

**Issue by VarshaKhodiyar** [obi-ontology/obi#822]
Please could someone consider whether the term IAO term

'database extract, transform, and load process' IAO:0000650

could be imported into OBI  as a child of 'planned process' OBI:0000011

Many thanks,
Varsha

**Comment by bpeters42** [comment]
OBI is currently using an outdated version of IAO. We plan to update this in our next OBI release, at which point it should be automatically appear under 'planned process'.

**Comment by VarshaKhodiyar** [comment]
Great, thanks

**Comment by jamesaoverton** [comment]
This term was added to OBI in commit b76068195d619f0da32d653389c2bc0b70c1adf2 on 2017-07-24.
