### ISSUE TITLE
NTR: BruUV-seq

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#827]
editor preferred term: bromouride labeling and sequencing after UV exposure
alternate terms: BruUV-seq
textual definition: An RNA-seq assay to identify transcription start sites and active enhancer elements through isolation of bromouridine (Bru) labelled RNAs after UV light exposure introduces transcription-blocking lesions.
definition source for the textual definition: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4675984/
logical definition: RNA-seq assay --> BruUV-seq

**Comment by cstoeckert** [comment]
Added to OBI.
https://github.com/obi-ontology/obi/commit/f8c8ed9e4544c45c7f7b0b6c3a7edc7942ed9a03
