### ISSUE TITLE
NTR: Genotyping by HiC

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#828]
editor preferred term: genotype phasing by HiC
textual definition: An assay in which carbon-copy chromosome conformation is used to detect polymorphism in DNA samples
definition source for the textual definition: https://www.ncbi.nlm.nih.gov/pubmed/19815776 (for HiC, but there is no publication yet on using this assay for genotyping)
logical definition: genotyping assay --> genotype phasing by HiC, carbon-copy chromosome conformation capture assay followed by sequencing assay --> genotype phasing by HiC

(updated term name reflects a recent change by the lab)

**Comment by jahilton** [comment]
Here is another appropriate reference: https://www.nature.com/nbt/journal/v31/n12/full/nbt.2728.html

**Comment by rctauber** [comment]
Hi @jahilton - we recently added the term 'HiC assay' as OBI:0002440, with definition:
"A chromosome conformation capture assay that detects genome-wide chromosomal interactions. High-throughput techniques are used to sequence the ligated fragments after cross-linking and cutting with restriction enzymes."

I would guess this isn't specific enough for your use case, though, correct?

**Comment by jahilton** [comment]
Correct. We are looking for a child term to 'HiC assay' to specify using the technique for the purpose of genotyping.

**Comment by rctauber** [comment]
Term added as OBI:0002459 ('genotype phasing by Hi-C assay') in 984887b
