### ISSUE TITLE
NTR: Mint-ChIP

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#829]
editor preferred term: multiplexed, indexed T7 ChIP-seq
alternate terms: Mint-ChIP, Mint-ChIP-seq
textual definition: A ChIP-seq assay which leverages T7 promoter amplification to allow low sample input and chromatin barcoding and pool-and-split multiplexing for high-throughput, quantitative profiling of chromatin states.
definition source for the textual definition: http://www.cell.com/molecular-cell/abstract/S1097-2765(15)00863-1
logical definition: ChIP-seq assay --> Mint-ChIP

**Comment by cstoeckert** [comment]
Added to OBI
https://github.com/obi-ontology/obi/commit/e7da227ffde7ce37d542c8db51e1e04bb50bff7c

**Comment by jamesaoverton** [comment]
This term was added to the OWL file with ID OBI_0002145, but that ID was previously assigned to 'antigen specific antibodies assay'. I'm changing the ID for 'multiplexed, indexed T7 ChIP-seq' to OBI_0002160.
