### ISSUE TITLE
NTR: nCounter Mouse miRNA Expression arrays

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#831]
editor preferred term: nCounter Mouse V1.5 miRNA Expression array
textual definition: An array which is manufacutred by NanoString Technologies. Built upon color-coded molecular barcodes technology, the array profiles mouse miRNA with increased specificity and sensitivty than microarrays.
definition source for the textual definition: https://www.nanostring.com/products/mirna-assays/mirna-panels, https://www.nanostring.com/application/files/3114/8964/6980/PDS_Mouse_v1_5_miRNA_update.pdf
logical definition: assay array --> nCounter Mouse V1.5 miRNA Expression array

The lab has also requested OBI terms for two previous versions of the same array, but the company no longer has documentation available for those.

editor preferred term: nCounter Mouse V1.2 miRNA Expression array
logical definition: assay array --> nCounter Mouse V1.5 miRNA Expression array
Usage: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0100951

editor preferred term: nCounter Mouse V1.3 miRNA Expression array
logical definition: assay array --> nCounter Mouse V1.5 miRNA Expression array
Usage: http://iovs.arvojournals.org/article.aspx?articleID=2319723

Please advise if we should contact Nanostring about documentation or if the references given are sufficient enough.

**Comment by DanBerrios** [comment]
I don't know that "array" is the correct term to use for this class of assay.  "Microarrays" are almost always 2-dimensional.  Yes, there are 1-dimensional "arrays" in mathematics, but most call those "vectors," and in the company docs they don't refer to this as a kind of an array, they only use the terms "assay" and "panel."

**Comment by cstoeckert** [comment]
@DanBerrios assay array covers more than microarrays and we do already have 'nCounter Human V2 miRNA Expression array' in OBI. 
@jahilton Given the definition of 'nCounter Human V2 miRNA Expression array' we need additional info to differentiate the different versions in the definition. An alternative way to go is to just define a 'nCounter Mouse miRNA Expression array' which is independent of version. We can define as having a 'version number' (http://purl.obolibrary.org/obo/IAO_0000129) that can be used to specify the different versions.

**Comment by jahilton** [comment]
I have heard back from the manufacturer...

> There aren’t any content changes between the different versions of the Mouse miRNA panels (all of the targets stay the same).
> Only version 1.5 contains ligation controls- the other versions do not.  Also between 1.3 and 1.5 the barcodes for the positive controls changed, so if you scan with the incorrect RLF file they will appear scrambled.

So the inclusion of the ligation controls could distinguish v1.5 from the other two, but unfortunately, it seems there isn't a clear distinction between v1.2 and v1.3.
If 'version number' were used, what would the hierarchy look like? Would each version have a unique OBI term?

**Comment by turbomam** [comment]
Time gap between when data is delivered.  Vendor may have updated documentation since then.

remove V2 from existing human array, add corresponding mouse unversioned array

**Comment by turbomam** [comment]
def source URL doesn't resolve

**Comment by jahilton** [comment]
This may be the 'best' (most stable) link for mouse & human
https://www.nanostring.com/products/mirna-assays/mirna-panels

**Comment by DanBerrios** [comment]
Just following up on my comment...does the manufacturer ever refer to these as "arrays"? I couldn't find it on their website..., if so.  They call them panels.  Or assays.  I just didn't want us to create confusion by calling them arrays (people might think we are referring to microarrays).

**Comment by jahilton** [comment]
The usage of 'array' began before my time at ENCODE, and I am guilty of propagating it.
I think either the manufacturer previously called them 'arrays', or, more likely, 'array' was used by the data producer that first submitted data from these, and we considered it common usage.
I would not oppose changing it to match the current manufacturer's term.

**Comment by turbomam** [comment]
@jahilton I'm closing this now because I think we addressed all of the concerns in this issue. Let me know if you disagree.
