### ISSUE TITLE
NTR: Illumina Genome Analyzer (general/parent term)

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#832]
In order to register a term that includes all of the Illumina Genome Analyzer versions, we first propose that OBI:0002128 be renamed to Illumina Genome Analyzer I. Then a new term as follows...

editor preferred term: Illumina Genome Analyzer
textual definition: One of the DNA sequencer models developed by Illumina (Solexa) surrounding the use of clonal arrays and massively parallel sequencing of short reads using solid phase sequencing by reversible terminators (subsequently referred to as sequencing by synthesis technology, or SBS).
definition source for the textual definition: https://www.illumina.com/technology/next-generation-sequencing/solexa-technology.html
logical definition: DNA sequencer --> Illumina Genome Analyzer --> Illumina Genome Analyzer I, Illumina Genome Analyzer 

Please advise if you have a more preferred way to insert the new umbrella term.

**Comment by DanBerrios** [comment]
I think the term Genome Analyzer is too commercially-oriented (like "Kleenex").  No one refers to any DNA sequencing instruments as "genome analyzers" conceptually.

**Comment by cstoeckert** [comment]
I can see the case for relabeling as there is a Illumina Genome Analyzer II (http://purl.obolibrary.org/obo/OBI_0000703). However, it is unclear given that there is only an Illumina Genome Analyzer I and II that an ontology term is needed as a general term. We haven't done that for the HiSeqs.

**Comment by DanBerrios** [comment]
I see now..so the intent of these classes is in fact to capture (perhaps small) differences in models for these DNA Sequencers... and not just differences in manufacturers.  So Genome Analyzer I,II may be appropriate.

**Comment by turbomam** [comment]
Existing terms:

 http://purl.obolibrary.org/obo/OBI_0000703 (OBI):
    Illumina Genome Analyzer II in Ontobee: OBI

http://purl.obolibrary.org/obo/OBI_0002128 (OBI):
    Illumina Genome Analyzer in Ontobee: OBI
definition includes characteristics that are specific to GA I

DNA sequencer
  Term IRI: http://purl.obolibrary.org/obo/OBI_0400103

Just rename OBI_0002128  to "Illumina Genome Analyzer I"? and add Genome Analyzer II ?

We'll decide on the 14th

**Comment by jahilton** [comment]
To our best recollection, we requested the parent 'Genome Analyzer' term between 'DNA sequencer' and the children GA terms to allow for ease of grouping the child terms with each other, but separate from the other sequencers.
We had a hierarchy similar to the AB SOLiD system (OBI_0000696) & child terms (OBI_0002007, OBI_0002024) in mind with this structure.

**Comment by turbomam** [comment]
Added 'Illumina Genome Analyzer I' alternative term for http://purl.obolibrary.org/obo/OBI_0002128
Otherwise, made no changes to hierarchy
