### ISSUE TITLE
NTR: quality measurement assays and associated value specifications

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#834]
Based on the discussions from the June 12, 2017 OBI call I propose the following which are needed by OBIB for term requests from the NCI Biorepositories and Biospecimen Research Branch. 

temperature measurement assay:  An assay to determine the temperature of an evaluant.
has_specified_output some (measurement datum and has some temperature value specification).

temperature value specification: A value specification that specifies the temperature of some thing.
specifies value of some temperature and has measurement unit label only temperature unit

volume measurement assay:  An assay to determine the volume of an evaluant.
has_specified_output some (measurement datum and has some volume value specification).

volume value specification: A value specification that specifies the volume of some thing.
specifies value of some temperature and has measurement unit label only volume unit

**Comment by bpeters42** [comment]
Slight editing of the logical definition, which didn't spell out the properties fully. 
temperature measurement assay = assay and has_specified output some measurement datum and 'has value specification' some 'temperature value specification'

Good to add.

**Comment by cstoeckert** [comment]
volume value specification and temperature value specification are scalar value specifications so should be  either asserted as such or an equivalence axiom added to scalar value specification so that it can be inferred.

**Comment by jamesaoverton** [comment]
The volume and temperature value specification stuff should go in a new issue. Closing this again.
