### ISSUE TITLE
Definition of 'training objective' has a grammatical error and incorrect genus

### ISSUE THREAD

**Issue by aellenhicks** [obi-ontology/obi#836]
'An training' should be changed to 'a training'

**Comment by aellenhicks** [comment]
The genus of the definition is the same as the term being defined. This could be fixed by changing 'training objective' to 'objective specification'.

**Comment by cstoeckert** [comment]
I plan to do some work on OBI soon and can make those changes. Thanks, Chris.

**Comment by cstoeckert** [comment]
Fixed and committed.
