### ISSUE TITLE
check logical definition of investigation agent role

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#838]
Just discussed with @zhengj2007 and @cstoeckert 

[Investigation Agent Role is defined as](http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0000202)

`role and (inheres in some bearer of some concretizes some objective_achieved_by some part of some investigation)`

This seems to say that an Investigation Agent Role role would inhere in a person, who bears some quality that concertizes an objective.

**Comment by jamesaoverton** [comment]
This is a bit confusing, but I think it is a correct application of BFO theory for generically and specifically dependent continuants.
