### ISSUE TITLE
NTR: oligo-dT primed Total RNA

### ISSUE THREAD

**Issue by carrieadavis** [obi-ontology/obi#847]
Hello,

I'd like to request a New Term: "oligo-dT primed Total RNA".

* Editor preferred term: "oligo-dT primed Total RNA".
* Alternative terms: oligo-dT primed cDNA -or- cDNA arising from oligo-dT primed reverse transcription.
* Textual Definition:  Describes the cDNA products that arise from reverse transcription using oligo-dT priming.
* Definition Source: Not sure what you need here?
* Logical definition (parent term): RNA and/or cDNA
* Example of usage:  We have sequenced the products (or cDNAs) that resulted from oligo-dT priming of Total RNa.
* Term editor: Carrie A Davis

**Comment by turbomam** [comment]
I dredged this up from the past. I'm glad to create it now if you still want it.

**Comment by bonitalam** [comment]
This is not high priority for ENCODE.
