### ISSUE TITLE
NTR: cDNA Sequencing Assay

### ISSUE THREAD

**Issue by carrieadavis** [obi-ontology/obi#848]
NTR: "cDNA Sequencing"

* Editor preferred term: "cDNA Sequencing"
* Alternative terms: copy DNA sequencing
* Textual definition: Sequencing (either Sanger or High-throughpu - like PacBio or Oxford Nanopore) of a full, partial or tag- fragmented cDNA molecule.
* Definition source for the textual definition: Common parlance
* Logical definition (or parent term): 
* Example of usage: "The data contained herein is derived from cDNA sequencing of oligo-dT primed cDNAs"
* Term editor: Carrie A Davis

**Comment by turbomam** [comment]
Hi, Carrie.  I'd like to start helping with your term requests.  To start...

Could this be defined as a "Seq assay which takes cDNA as the input"... but ins't that the case for RNAseq?  In what case would somebody use this term in a materials and methods section?

**Comment by bonitalam** [comment]
@turbomam we have no need for this term request anymore. You are right that cDNA sequencing is basically RNAseq. Thank you for pointing out this open issue to us, but please feel free to close it.

**Comment by turbomam** [comment]
Thanks @bonitalam
