### ISSUE TITLE
NTR: icSHAPE Assay

### ISSUE THREAD

**Issue by carrieadavis** [obi-ontology/obi#852]
Project: ENCODE

So - we are working with a new High Throughput Sequencing Assay: icSHAPE, that captures RNA secondary structure.

NTR: "icSHAPE"

Editor preferred term: "icSHAPE"

Alternative terms: SHAPE-Seq, NET-Seq

Textual definition: icSHAPE provides accurate predictions of RNA-protein interactions and m6A modification in vivo by combining SHAPE-Seq with click chemistry for enhanced isolation. , Secondary RNA structures are modified by the addition of a custom 2-methylnicotinic acid imidazolide (NAI) probe, termed NAI-N3. The modifed RNA is marked selectively with dibenzocyclooxtyne (DIBO)-biotin through copper-free click chemistry, enabling purification by streptavidin pull-down. Briefly, NAI-N3 is added to RNA in vivo to mark it selectively for DIBO-biotin tagging. The cells are lysed, the RNA is poly(A)-selected, tagged with DIBO-biotin, and fragmented. The RNA strands are 3'-end-repaired with T4 PNK and ligated to 3' adapters. After size-selection, the RNA strands are reverse-transcribed, and both the RNA and first-strand cDNA are captured on streptavidin beads. Another cDNA size-selection step is carried out before circularization and PCR amplification. The samples are ready for NGS.

Definition source for the textual definition: https://www.illumina.com/science/sequencing-method-explorer/kits-and-arrays/icshape.html

Logical definition (or parent term):

Example of usage: The icSHAPE library was sequenced on the Illumina platform

Term editor: Carrie A Davis

**Comment by turbomam** [comment]
I'm reviewing your old requests and am glad to create a few this week if you can help prioritize.

**Comment by bonitalam** [comment]
We would like to prioritize this request along with the ATAC-seq assays.

**Comment by turbomam** [comment]
May have been added to OBI but with a label other than icSHAPE
