### ISSUE TITLE
Distinguish definitions for "proteomic profiling design" and "proteomic profiling by array design"

### ISSUE THREAD

**Issue by DanBerrios** [obi-ontology/obi#854]
Recommend altering the definition for "proteomic profiling by array design" from:

A study design in which proteins in a sample are detected, quantified or otherwise analysed, e.g. antibody profiling using an array based technology

to:

A study design in which proteins in a sample are detected, quantified or otherwise analysed, through an array-based technology.

to make it more specific.

**Comment by zhengj2007** [comment]
The proposed definition looks good to me.

**Comment by zhengj2007** [comment]
Discussed on OBI call 2017-11-27. We will make the changes in OBI.

**Comment by zhengj2007** [comment]
change made according to @DanBerrios 's suggestion. See commit https://github.com/obi-ontology/obi/commit/c83e1633904ab50d111346c2f0524e89369712fb
