### ISSUE TITLE
Update OBI:0002112

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#859]
When requesting a term for 'small RNA-seq', we cited a product that unfortunately, specified a size range that does not reflect the common usage of this assay name.
One of the earliest publications notes a size of <200 nt (http://science.sciencemag.org/content/316/5830/1484.full). Could you please update the definition to the broader size range?

We would also like to request an alternate term of 'short RNA-seq'
reference: http://genome.cshlp.org/content/21/2/182.full (this also references <200 nt)

**Comment by turbomam** [comment]
Edited locally, haven't pull-requested yet.
