### ISSUE TITLE
polyA+ & polyA- RNA-seq distinctions

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#863]
Hello,
The ENCODE project is exploring how to distinguish various RNA-seq assays, including those that involve steps in the protocol to enrich, or deplete, polyAdenylation. Would these be appropriate terms?

editor preferred term: polyA-selected RNA sequencing assay
alternate terms: polyA RNA-seq, polyA mRNA RNA-seq, mRNA-seq
textual definition: An RNA-seq assay to study transcriptomes through the enrichment of polyadenylated transcripts or removal of ribosomal RNA prior to high-throughput sequencing.
definition source for the textual definition: https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-15-419
logical definition: RNA-seq assay --> polyA RNA-seq

editor preferred term: polyA-depleted RNA sequencing assay
alternate terms: polyA-depleted RNA-seq
textual definition: An RNA-seq assay to study non-polyadenylated transcripts, such as, but not exclusive to unspliced and circular isoforms, through the depletion of polyadenylated transcripts prior to high-throughput sequencing.
definition source for the textual definition: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0030733, http://www.tandfonline.com/doi/full/10.1080/15476286.2015.1110676
logical definition: RNA-seq assay --> polyA-depleted RNA-seq

Thanks!

**Comment by turbomam** [comment]
Hi, Jason.  This is a good request.  I'd like to discuss it during the OBI phone call at noon EDT on this Monday, April 30th.  I assume the group will approve it, but I'll be suggesting that we follow some OBI templates and define these assays in terms of what their specified input is.  That may require creating a few additional terms (which may or may not interest you.)

Would you be willing to join the call to make sure your needs and perspective are understood?

see http://obi-ontology.org/#contact-us

**Comment by jahilton** [comment]
Yes, I think the ENCODE DCC will have some representation on next week's call.
Thank you.

**Comment by turbomam** [comment]
I just noticed that you have several additional term requests, all from mid to late 2017.  I'll try to orient myself regard the others, in case you or a colleague want to go over them, too.

**Comment by turbomam** [comment]
OBI has related terms using at least two notations: " polyA..." and "poly(A)..."

Should we make these consistent?

**Comment by turbomam** [comment]
For the assays that take RNA enriched for poly adenylation, we could say that the specified input is Class: 'polyA RNA extract', http://purl.obolibrary.org/obo/OBI_0000869

**Comment by turbomam** [comment]
selected: OBI_0002571
depleted: OBI_0002572

**Comment by turbomam** [comment]
New issue?  Single cell RNAseq as a new term?  Includes special preparative steps and special analytical steps.

General issue... how far to go with pre-composition?

**Comment by DanBerrios** [comment]
Discussed on call 11/04/19...Mark will follow up on status of original request.

**Comment by bonitalam** [comment]
Commenting on this issue so I can follow any updates.

**Comment by turbomam** [comment]
I'll take care of this on Wednesday

**Comment by jamesaoverton** [comment]
@bonitalam The easiest way to get updates on a specific issue is to click the "Subscribe" button on the right under "Notifications". To get updates on all issues for a repository, use the "Watch" button at the top right.

**Comment by turbomam** [comment]
@jahilton , @bonitalam ...

Do these two terms meet the needs of the original request?

- [polyA-selected RNA sequencing assay](http://purl.obolibrary.org/obo/OBI_0002571)
- [polyA-depleted RNA sequencing assay](http://purl.obolibrary.org/obo/OBI_0002572)

 If so, I propose that I 

- add either 'has specified input' or 'has part' axioms 
- change [poly(A)-site sequencing assay](http://purl.obolibrary.org/obo/OBI_0002045) to use the polyA- notation
- close this issue

We could also normalize our use of `select*` and `extract*`.  See  [polyA RNA extract](http://purl.obolibrary.org/obo/OBI_0000869) and [polyA RNA extraction](http://purl.obolibrary.org/obo/OBI_0000848) 

Finally... see also #1082

**Comment by bonitalam** [comment]
@turbomam Yes, those two terms meet the needs of our original request. Thank you!

**Comment by ddooley** [comment]
Mark will roll ahead with "polyA-" prefix uniformly,   Mark will add specified input axiom via robot template.

**Comment by turbomam** [comment]
[polyA-site sequencing assay](http://purl.obolibrary.org/obo/OBI_0002045) now uses polyA syntax but keeps poly(A) as an alternative term.

### in assays.tsv:
- adding [polyA RNA extract](http://purl.obolibrary.org/obo/OBI_0000869) as input for  [polyA-selected RNA sequencing assay](http://purl.obolibrary.org/obo/OBI_0002571)
- adding [polyA depleted RNA extract](http://purl.obolibrary.org/obo/OBI_0002573) as input for [polyA-depleted RNA sequencing assay](http://purl.obolibrary.org/obo/OBI_0002572)
