### ISSUE TITLE
NTRs: ATAC-seq assays

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#864]
editor preferred term: single-nuclei ATAC-seq
alternate terms: snATAC-seq
textual definition: Analysis of the transposase-accessible-chromatin in single nuclei isolated from frozen tissue samples through a protocol designed to maximally preserve nuclei integrity during sample processing and optimize transposase-mediated fragmentation of chromatin in individual nuclei. snATAC-seq can be used to dissect heterogeneity and delineate gene regulatory sequences in complex tissues, and uncover both the cell types and the regulatory elements in each cell type without prior knowledge.
definition source for the textual definition: http://www.biorxiv.org/content/early/2017/07/06/159137
logical definition: ATAC-seq --> snATAC-seq

editor preferred term: single-cell ATAC-seq
alternate terms: scATAC-seq
textual definition: A robust method for mapping the accessible genome of individual cells by assay for transposase-accessible chromatin using sequencing (ATAC-seq) integrated into a programmable microfluidics platform in order to provide insights into cell-to-cell variation in accessibility profiles.
definition source for the textual definition: http://www.nature.com/nature/journal/v523/n7561/full/nature14590.html
logical definition: ATAC-seq --> scATAC-seq

**Comment by gabdank** [comment]
I was wondering if there was made in progress with this new term request?
We would like to update the term request for the snATAC-seq

editor preferred term: single-nucleus ATAC-seq
alternate terms: snATAC-seq
textual definition: A combinatorial barcoding-assisted single-cell assay for transposase-accessible chromatin that is optimized for use on flash-frozen primary tissue samples. snATAC-seq can be used to dissect cellular heterogeneity and delineate cell-type-specific gene regulatory sequences in snap-frozen primary tissues.
definition source for the textual definition: https://www.nature.com/articles/s41593-018-0079-3
logical definition: ATAC-seq --> snATAC-seq

**Comment by mkuhring** [comment]
Pushing #864 and #995. Single cell technology should really be part of OBI, probably by yesterday.
What is keeping these terms from being implemented for two years now? These term submissions look complete to me. Definition sources can be also used as examples.

**Comment by turbomam** [comment]
Some of these requests have admittedly slipped through the cracks. I can do a few this week, but will need to prioritize relative to request from @carrieadavis

**Comment by bonitalam** [comment]
Hi @turbomam, on behalf of ENCODE - I believe the ATAC-seq (ATAC-seq and snATAC-seq) requests have higher priority.

**Comment by turbomam** [comment]
Addressed with terms like

https://www.ebi.ac.uk/ols4/ontologies/obi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0002762
