### ISSUE TITLE
Eligibility criteria for consideration into OBI

### ISSUE THREAD

**Issue by hjellis** [obi-ontology/obi#865]
https://docs.google.com/spreadsheets/d/1OxHwvOijXrtJiCu3fK45sTWNnBcbRqgSqUZpuY_klpU/edit#gid=1233805461

note that column A differentiates between OBI and OBIB
@mbrochhausen

**Comment by cstoeckert** [comment]
Discussed on Sept. 18, 2017 call. If no objections will add in 2 weeks.

**Comment by jamesaoverton** [comment]
Terms added in commit 6e36faf693712520bb887060527185d54a1f0e54
