### ISSUE TITLE
NTR: medical history related terms

### ISSUE THREAD

**Issue by cstoeckert** [obi-ontology/obi#866]
The Ontology for Biobanking (OBIB) has requests from the NCI BBRB for terms related to medical and clinical history. They are listed here using a ROBOT style template:
https://docs.google.com/spreadsheets/d/1h-YGctsON5EMO_2qMMIi-CJGKNRZgpGicv6l-bqPTmQ/edit?usp=sharing

We would like to add them to OBI if deemed suitable and then import them into OBIB.
Thanks, Chris

**Comment by cstoeckert** [comment]
Discussed on Oct. 2, 2017 call. Deemed in OBI scope if meant to be used for research (investogations). Use cases are to find specimens obtained from people with certain characteristics or to discover associations.  If these are to be annotated then worth making a class otherwise can either use string literals or combine existing classes. Remove terms requiring parent from ontologies not imported by OBI. Two week comment period.

**Comment by jamesaoverton** [comment]
Terms added in commit 6e36faf693712520bb887060527185d54a1f0e54
