### ISSUE TITLE
NTR: New terms for the Ontology for RNA Sequencing (ORNASEQ)

### ISSUE THREAD

**Issue by safisher** [obi-ontology/obi#871]
As part of our efforts to create the Ontology for RNA Sequencing (ORNASEQ), we request various terms be considered for addition to OBI. These new terms would ultimately be imported into ORNASEQ. The proposed terms are listed in the following spreadsheet.
   https://docs.google.com/spreadsheets/d/1Rc0CLr4XBFo2zWeUIiG--MN4hg6SleqJyfyFt_mL5x0/edit?usp=sharing

The homepage for ORNASEQ is here: http://kim.bio.upenn.edu/software/ornaseq.shtml

The current draft of ORNASEQ can be downloaded in owl format from here: http://kim.bio.upenn.edu/ornaseq/2017/10/ornaseq.owl

If helpful, I'm happy to create a separate issue for each of the 30 terms.

**Comment by siiraa** [comment]
Would love to be part of this discussion as an observer too :)

Thank you!

**Comment by cstoeckert** [comment]
I've reviewed the labels, definitions, and parents and given feedback to Stephen. These have led to an update of the google sheet with the terms and are ready for approval by OBI. - Chris S.

**Comment by safisher** [comment]
Dan thank you for the extensive review. I added columns to the end of the spreadsheet with your comments and my responses. I also updated the spreadsheet values, as per my noted responses. If you'd prefer for me to respond to your 14 points in comments here then please let me know. I'm also happy to give you or whomever else write access to the Google spreadsheet. I'm not sure how you prefer to handle discussions of this sort.

Re. #12 I removed "replicate specimen" from the table.

**Comment by cstoeckert** [comment]
Based on Stephen's response to Dan it looks like there are about 6 or so still to discuss. I suggest scheduling an OBI call to finish these. How about Feb. 12 or March 5? Thanks, Chris

**Comment by DanBerrios** [comment]
Sounds good, @cstoeckert   There were some questions I had in my feedback.  We can discuss on 2/12

**Comment by safisher** [comment]
The Google document has been updated with the changes discussed during the meeting. I added a column that denotes the changes.

**Comment by safisher** [comment]
Discussions between Dan, Chris and Stephen led to the creation of a "date process started" term. This is a child of "data item". 

Specific process date terms will be moved into the application ontology (i.e. "date of specimen amplification" and "date of specimen library preparation") and defined as children of "date process started". 

The Google doc has been updated accordingly.

**Comment by safisher** [comment]
I just updated the Google doc for "SIRV RNA spike-in" parent and description, to be consistent with "ERCC RNA spike-in".

**Comment by DanBerrios** [comment]
seq file type (parent of requested term BCL format) is marked as obselete in EFO ontology...

**Comment by DanBerrios** [comment]
Commit and pushed to branch DanBerrios
