### ISSUE TITLE
NTR: direct RNA sequencing assay

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#874]
editor preferred term: direct RNA sequencing assay
alternate terms: direct RNA-seq, DRS
textual definition: An assay in which to study transcription through direct single molecule RNA sequencing without prior conversion of RNA to cDNA.
definition source for the textual definition: https://www.nature.com/articles/nature08390
logical definition: RNA-seq assay [OBI:0001271] --> direct RNA sequencing assay

**Comment by DanBerrios** [comment]
Minor edits:
editor preferred term: direct RNA sequencing assay
alternate terms: direct RNA-seq, DRS
textual definition: An assay to study transcription through direct RNA sequence determination, without prior conversion of RNA molecules to cDNA.
definition source for the textual definition: https://www.nature.com/articles/nature08390
logical definition: RNA-seq assay [OBI:0001271] --> direct RNA sequencing assay

**Comment by jahilton** [comment]
Looks great.
Thank you.

**Comment by bonitalam** [comment]
Have there been any updates on the addition of this term?

**Comment by johnwjudkins** [comment]
Discussed 2019-10-28. Dan will add this term.

**Comment by DanBerrios** [comment]
Pull request generated.

**Comment by DanBerrios** [comment]
https://github.com/obi-ontology/obi/pull/1070
