### ISSUE TITLE
NTR: Chromosome conformation capture-on-chip

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#875]
editor preferred term: Chromosome conformation capture-on-chip
alternate terms: 4C, 4C-seq
textual definition: An assay which uses cross-linking of proteins to proteins and to DNA followed by two rounds of digestion and ligation, and then inverse PCR, in order to enable for unbiased genome-wide screens for DNA contacts made by single genomic sites of interest.
definition source for the textual definition: http://www.sciencedirect.com/science/article/pii/B9780123919380000045

Currently, 5C is listed under 'sequencing assay'. In this case, 4C should also be under 'sequencing assay'. However, maybe it's more appropriate to add a 'chromosome conformation capture assay' term under 'sequencing assay' and put both 5C and 4C within this class?

**Comment by rctauber** [comment]
Is “circularized chromosome conformation capture” (also 4C) another exact synonym for this term? ECO is requesting this term and it would be good to know if they are exactly the same techniques, or just related. From what I can find, it seems like they’re the same.

**Comment by jahilton** [comment]
Yes, it appears that they are indeed the same.
Explicitly stated here: https://epigeneticsandchromatin.biomedcentral.com/articles/10.1186/1756-8935-7-25 (Abbreviations section)

**Comment by rctauber** [comment]
Term added as OBI:0002458 ('chromosome conformation capture-on-chip assay') in 984887b
