### ISSUE TITLE
NTR: Precision nuclear run-on and sequencing assay

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#876]
editor preferred term: Precision nuclear run-on and sequencing assay
alternate terms: PRO-seq
textual definition: An assay to map the genome-wide distribution of transcriptionally-engaged Pol II at base-pair resolution by using biotin-labeled ribonucleotide triphosphate analogs (biotin-NTP) for nuclear run-on reactions, allowing the efficient affinity purification of nascent RNAs for high throughput sequencing from their 3’ ends.
definition source for the textual definition: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3974810/
logical definition: RNA-seq assay [OBI:0001271] --> Precision nuclear run-on and sequencing assay

**Comment by rctauber** [comment]
I have also been seeing it called “precision nuclear run-on sequencing assay” (without the ‘and’), though I can’t tell which one is more common. One should be added as another alt term though.

For definition:
- should start with “An RNA-seq assay that...”
- perhaps add something about the RT and PCR steps to then sequence the cDNA (from reference https://www.illumina.com/science/sequencing-method-explorer/kits-and-arrays/pro-seq.html)

**Comment by zhengj2007** [comment]
Discussed on OBI 2017-11-27. @rctauber will add the term in the assay template.

RT and PCR steps can be added as has_part process in the template.

**Comment by rctauber** [comment]
Resolved by 984887b
