### ISSUE TITLE
NTR: isoform sequencing

### ISSUE THREAD

**Issue by jahilton** [obi-ontology/obi#878]
editor preferred term: isoform sequencing
alternate terms: ISO-seq
textual definition: A method for sequencing isoforms by enriching a cDNA library for full-length reads spanning entire transcript isoforms.
definition source for the textual definition: http://www.pacb.com/blog/intro-to-iso-seq-method-full-leng/
logical definition: RNA-seq assay --> isoform sequencing

**Comment by DanBerrios** [comment]
ISO-seq is a trademarked term.  Are we including trademarked terms in OBI?  Otherwise, these fields look good to me.  Add:

Example of usage: Novel transcript forms were assessed by isoform sequencing.

**Comment by bpeters42** [comment]
As alternative labels, i would include them. We have for e.g. Biacore
assays in the past.

**Comment by DanBerrios** [comment]
OK, I guess my concern is showing favoritism or endorsement, by including TM terms.  Working in government, we are always thinking about that.

**Comment by DanBerrios** [comment]
I believe we discussed on the call that including trademark terms is fine.

**Comment by turbomam** [comment]
Mark will add ASAP

**Comment by jamesaoverton** [comment]
Term added in #933
