### ISSUE TITLE
term request: health status inclusion criterion

### ISSUE THREAD

**Issue by mbrochhausen** [obi-ontology/obi#880]
label: health status inclusion criterion
definition: "An inclusion criterion that defines and states one or more clinically significant bodily components, dispositions, and/or bodily processes of an entity that are inferred from relevant clinical findings or self-reported, which, if met, makes the entity suitable for a given task or participation in a given process.”
examples of usage: ‘diagnosed with Type 2 diabetes mellitus’, ‘E11.4’, ’not finding of hypertension' 
ontology term requester: MIABIS2.0

**Comment by DanBerrios** [comment]
Discussed on OBI Dev call on 2/12/18 and approved.

**Comment by mbrochhausen** [comment]
resolved:
https://github.com/obi-ontology/obi/commit/2a84d760e1351707b248fb20465cb4031ad693d4
