### ISSUE TITLE
term request: clinically relevant life style inclusion criterion

### ISSUE THREAD

**Issue by mbrochhausen** [obi-ontology/obi#881]
label: clinically relevant life style inclusion criterion
definition:"An inclusion criterion that defines and states one or more clinically relevant planned processes that a human being actively participates in , which, if met, makes the human being suitable for a given task or participation in a given process.”
examples of usage: 'smoking behavior’
ontology term requester: MIABIS2.0

**Comment by DanBerrios** [comment]
Discussed on OBI Dev call...2/12/18, recommend "lifestyle" instead of "life style".

**Comment by mbrochhausen** [comment]
resolved:
https://github.com/obi-ontology/obi/commit/f2ef1d389d698fe5157b8f4b6b91941d3898e3eb
