### ISSUE TITLE
Adjust definition of 'hydroxyl-radical footprinting assay'

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#885]
[OBI:0002442 hydroxyl-radical footprinting assay](http://purl.obolibrary.org/obo/OBI_0002442) was recently added by @zhengj2007 and defined as:

> A footprinting assay that etermines protein-binding sites
on DNA by identifying bound fragments that are protected from hydroxyl
radicals which cleave DNA by abstracting a hydrogen atom from C4 of
the sugar in the minor groove.

For the IEDB we have examples of hydroxyl-radical footprinting that are not specific to DNA. We propose the following definition:

> A footprinting assay that uses the reaction of hydroxyl radicals with
side-chain sites in molecules (proteins, DNA, etc)  with the resultant
mass shift demonstrating the site of modification, used to  to asses
the accessibility of that site.

And definition source: PMID:21770468

We would also change the logical definition of the input.

@zhengj2007 Is this acceptable?

cc: @bpeters42

**Comment by jamesaoverton** [comment]
CC @rvita

**Comment by jamesaoverton** [comment]
The alternative is to create a parent for this term which is not specific to DNA.

We'd like to get this fixed APAP. I dropped the ball, and now it's a rush.

**Comment by zhengj2007** [comment]
@jamesaoverton @rvita 

The updated definition and related logical axiom changes sounds good to me. Please go ahead.
