### ISSUE TITLE
Term request: clinically relevant exposure inclusion criterion

### ISSUE THREAD

**Issue by mbrochhausen** [obi-ontology/obi#887]
o    label: clinically relevant exposure inclusion criteriondefinition:"An inclusion criterion that defines and states one or more clinically relevant histories of exposure of an entity, which, if met, makes the entity suitable for a given task or participation in a given process.”
o    examples of usage: 'exposure to cigarette smoke’, ‘exposure to lead through drinking water'
o    ontology term requester: MIABIS2.0

**Comment by Public-Health-Bioinformatics** [comment]
needs the term label! ;)

**Comment by mbrochhausen** [comment]
Thanks! I just added that information

**Comment by DanBerrios** [comment]
Discussed on OBI Dev call 2/12/18 and approved.

**Comment by mbrochhausen** [comment]
resolved:
https://github.com/obi-ontology/obi/commit/23a7dfd815829c87991c5cd36fea3ccebb73dfce
