### ISSUE TITLE
hasDateTime

### ISSUE THREAD

**Issue by Aqua1ung** [obi-ontology/obi#889]
As discussed in one of the OBI meetings from a few weeks ago, I am proposing adding at least one datatype property (hasDateTime) to OBI, property whose aim is to point to **the temporal end of a process**--or, equivalently, the time instant of the end process **boundary**. (Unfortunately OWL 2.x did away with xsd:time and xsd:date, hence all there is left to work with is xsd:dateTime, which is most likely overkill for most of our everyday purposes.)

I propose that the domain of this property be "process" (obo:BFO_0000015), and its range xsd:dateTime, as it looks to me plausible that whoever might be interested in the "time/date of a process" is actually interested in the time/date the process **ended**. (Whoever asks when the histopathology happened is more likely to ask when it ended, not when it started. Surely enough, should there be calls for telling these temporal points apart, it may make sense to add two datatype properties (hasStartDateTime and has(End)DateTime, say) instead of just hasDateTime, though for now methinks hasDateTime should do the trick.)

Finally, should there be calls to model such time instants as **entities** as opposed to a **datatypes** (and I am guessing that there will be), all the entity "apparatus" can be _added later on_, hence the hasDateTime property will very likely emerge as a **defined property** (a "shortcut," if you will), instead of a primitive. For now, I think pointing to a dateTime literal via a primitive datatype property should be enough for most of our purposes. Furthermore, as opposed to the case of ordinary measurement assays (such as measurements of length, chemical composition etc.), I do not really foresee the same sort of debates and uncertainty regarding the instant of **time** some process ended/started that could justify the addition of an approximation mechanism: While we may have alternative ways to measure length (say), it is quite unlikely that reporting the timing of the end (or start) of an assay would stir heated debates as to when **exactly** the assay ended (or started).

**Comment by Public-Health-Bioinformatics** [comment]
Just a note that an ontology used in processing systems that want to log events/processes will want both hasStartDateTime and hasEndDateTime (or hasDuration) for performance monitoring & logging purposes.

**Comment by Aqua1ung** [comment]
Superseded by issues #898 and #899. Closing.
