### ISSUE TITLE
Where is the obo file

### ISSUE THREAD

**Issue by oganm** [obi-ontology/obi#891]
I used to be able to access the obo file for obi from http://purl.obolibrary.org/obo/obi/obi.obo, it seems to be gone. Is it still accessible?

**Comment by jamesaoverton** [comment]
OBI has always been developed in OWL format, and only OWL format will give you all the logical content in OBI. However the OBO conversion used to work and be done automatically by the Berkeley group. ROBOT should also be able to convert OBI to OBO format, but I'm having some trouble with that, related to https://github.com/ontodev/robot/issues/64.

I'll try to get this sorted out.

**Comment by bobular** [comment]
I naively tried using Protege to make an OBO version - it failed with many errors similar to this:

```
ERROR OWLAPIOwl2Obo    MASKING ERROR «the axiom is not translated : OBI_0000705 SubClassOf (BFO_0000055 some 
(REO_0000171 and (RO_0000052 some BFO_0000040))) and (OBI_0000293 some BFO_0000040)
```

My ultimate aim is to load OBI into Chado - I would normally take this route from an OBO file...

`cat OBI.obo | go2fmt.pl -p obo_text -w xml - | go-apply-xslt oboxml_to_chadoxml - > OBI.chado.xml`

Any suggestions gratefully received.

**Comment by jamesaoverton** [comment]
OBI was not designed with OBO format in mind, so these masking errors have to be ignored.

I'm not sure what Protégé does, but the new [1.1.0 release of ROBOT](https://github.com/ontodev/robot/releases/tag/v1.1.0) has a `--check false` option that will ignore these errors and complete the conversion. This should work:

    robot convert --input obi.owl --output obi.obo --check false

**Comment by jamesaoverton** [comment]
For a while now we've been generating a new `obi.obo` with each release: http://purl.obolibrary.org/obo/obi.obo
