### ISSUE TITLE
NTR: assay attempt

### ISSUE THREAD

**Issue by Aqua1ung** [obi-ontology/obi#911]
**Editor preferred term:** assay attempt
**Textual definition:** Planned process intended to constitute an assay. All assays are assay attempts, though the reverse is false: there are, in other words, failed assay attempts.
**Definition source:** EuPath team
**Proposed parent:** planned process; The "assay" class should be a subclass of "assay attempt"
**Example of usage:** 
**Submitted by:** EuPath team

**Comment by zhengj2007** [comment]
Failed assay is not in OBI scope. It is indicated in the OBI paper.

**Comment by Aqua1ung** [comment]
Gully thinks it may not be necessary.

**Comment by Public-Health-Bioinformatics** [comment]
Re. @zhengj2007 OBI paper desire to avoid the description of failed controls (broken or dirty machine, bad chemistry supplies, wrong input taken, etc.) in experiment execution:
> "For example, if a PCR-SSCP assay fails to detect a sequence variation, it is in scope for OBI. However, if controls performed as part of the assay fail then it is not in scope. We are representing only experiments which have succeeded by their own criteria, to avoid unnecessary complexity in all definitions."

The telecon discussion example focused on the **failure of input material** to be adequate for an assay to perform its measurement function.  I also feel a reticence to have a term 'failed assay' (implied as an assay attempt outcome) when the assay did its job, and its just the nature of the input or output that is in focus.

If the input material wasn't appropriate for the assay, that's an example of a "failed control" above.  (Too little or too much analyte or analyte indicator to categorize or scale), or having some other confounding component like contamination.)

If we have an assay being judged a "failure" by some other validation (process) then we're in a comparative debate.

Does this case pertain only to assays that have an "inconclusive" output data state? E.g. that "inconclusive" cancer stage appraisal which lives outside the other (ordinal) ranks. 

I was considering, paraphrased: 

    'inconclusive assay' 
        subClassOf assay and 'has inconclusive output' some 'specified output'
    'has inconclusive output'
        subPropertyOf of 'has specified output'

Specified output could have a value specification if it wasn't inconclusive.

**Comment by cstoeckert** [comment]
Not clear that this is still needed.
