### ISSUE TITLE
process is BFO_0000007 or BFO_0000015 ?

### ISSUE THREAD

**Issue by cfrancois7** [obi-ontology/obi#917]
I noted the `process` type is defined as `BFO_0000007` in OBI but `BFO_0000015` in BFO. In fact, `BFO_0000007` doesn't exist anymore in the BFO 2.0.
Is it not a problem to keep the two types with the same label ? It quite disturbing when we import the BFO as the same time as OBI.

Best regards,

**Comment by rctauber** [comment]
Could you please provide the file and/or version number you are using? If you're not using the most recent release of OBI, this may be the cause. We can't reproduce the issue you are having here - it seems that `process` is in OBI as `BFO_0000015`.

Thank you!

**Comment by cfrancois7** [comment]
I found the problem. It wasn't the problem of OBI but the problem of the STATO ontology.
I supposed too quickly that OBI was the problem because of the annotation `import from` `obi.owl`.

The problem is the STATO ontology that reuses some old OBI types.
