### ISSUE TITLE
Term request: defined population inclusion criteria

### ISSUE THREAD

**Issue by mbrochhausen** [obi-ontology/obi#920]
o label: defined population inclusion criteria
definition:"An inclusion criterion that is based on fitting within the defined characteristics of a population based study design.”
o ontology term requester: MIABIS2.0

**Comment by cstoeckert** [comment]
We would also include these annotations:
example of usage:  inclusion based on age, sex, and living region (rural area or specified city).
definition source: MIABIS2.0

**Comment by turbomam** [comment]
criterion
