### ISSUE TITLE
GO: molecular_function is imported under BFO:function

### ISSUE THREAD

**Issue by zhengj2007** [obi-ontology/obi#921]
GO: molecular_function is imported under BFO:function in OBI.
See:
http://www.ontobee.org/ontology/OBI?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0003674

GO defined it as a process. So, we need to correct it in OBI. 

For clarifying it, Chris M has proposed to modify its textual definition as:
A molecular process that can be carried out by the action of a single macromolecular machine, usually via direct physical interactions with other molecular entities. Function in this sense denotes an action, or
activity, that a gene product (or a complex) performs. These actions are described from two distinct but
related perspectives: (1) biochemical activity, and (2) role as a component in a larger system/process.

**Comment by agbeltran** [comment]
Thanks @zhengj2007 for posting this issue. This was reported in STATO (https://github.com/ISA-tools/stato/issues/66) and I am linking the issue here so that we fix the OBI import when it is fixed in OBI.

**Comment by cmungall** [comment]
This is currently causing massive train wrecks of unsatisfiable classes in lots of ontologies attempting to import OBI for planned process right now. What is the best way of getting this though? Should I make a PR?

**Comment by pbuttigieg** [comment]
>This is currently causing massive train wrecks of unsatisfiable classes in lots of ontologies attempting to import OBI for planned process right now. What is the best way of getting this though? Should I make a PR?

Yes, this is currently blocking an ENVO release, can we help push this through?

**Comment by turbomam** [comment]
BFO:  function inheres in a device & realized in a process?
GO: molecular function = a process in which the function is realized, therefore a subClassOf process? (Mark's shorthand)

**Comment by turbomam** [comment]
import GO molecular function under process in OBI; change labels to include the word "process", or possibly prefix GO's native labels with "GO: "?

Discuss with OBO foundry operations committee?

James identified some other cleanup required in terms of usage

**Comment by jamesaoverton** [comment]
Steps:

- move 'molecular_function' under 'process' in OBI
- for OBI we want to use 'GO:molecular_function' as the label
- we need to update a number of OBI logical definitions, e.g. from 'inheres in' to 'has participant'

I will work on this and prepare a new OBI release, aiming to release in about a week.

**Comment by jamesaoverton** [comment]
Also: We will update the textual definition of 'molecular_process' in OBI.

**Comment by jamesaoverton** [comment]
I'm working on this now, but I've run into a problem that I'd like some help with.

OBI has a 'single-nucleotide-resolution nucleic acid structure mapping assay using enzymatic probing' (http://purl.obolibrary.org/obo/OBI_0001014) assay with this subClassOf axiom:

    realizes some ('catalytic activity' and ('inheres in' some protein))

The axiom makes sense when 'catalytic activity' was under 'function', but now we're putting it under 'process' so we need another formulation. Should it be something like this?

    has_specified_input some (protein and ('participates in' some 'catalytic activity'))

Maybe the protein also has a reagent role?

This assay also has eight children that follow the same pattern with specific proteins:

- http://purl.obolibrary.org/obo/OBI_0001016 DNASE 1 structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001035 Nuclease S1 structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001019 RNA ADA I RNA structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001005 RNASE CL3 structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001030 RNASE T1 structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001021 RNASE T2 structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001024 RNASE U2 structure mapping assay
- http://purl.obolibrary.org/obo/OBI_0001012 RNASE V1 structure mapping assay

@proccaserra added these assays. @bpeters42 @cstoeckert or anybody else? We're trying to push the change quickly.

**Comment by proccaserra** [comment]
@jamesaoverton that works for me. Let me check if the classification is preserved. best

**Comment by jamesaoverton** [comment]
Thanks!

Next problem: OBI 'enzyme' http://purl.obolibrary.org/obo/OBI_0000427 is defined as **equivalent to**:

    'material entity'
    and ('ribonucleic acid' or 'protein complex' or protein or ('has part' some 'ribonucleic acid') or ('has part' some 'protein complex') or ('has part' some protein))
    and ('has function' some 'catalytic activity')

If I change`has function` to `participates in` this axiom might no longer be true, since there might be non-enzymes that participate in catalytic activity. **Are there such non-enzymes?** If so, we can make the substitutions and weaken the axiom to **subclass of**.

**Comment by cstoeckert** [comment]
Substrates/ targets of enzymes (which can be non-enzymes) also participate in the ‘catalytic activity’ process.

**Comment by bpeters42** [comment]
Has function some(realized in only catalytic activity)

**Comment by jamesaoverton** [comment]
I created a new PR with a summary of the changes: https://github.com/obi-ontology/obi/pull/936

Anyone who is interested: please take a look ASAP.

I plan to merge that PR and make a new OBI release candidate tomorrow morning (Eastern time).

**Comment by jamesaoverton** [comment]
@proccaserra I checked the inferred hierarchy, and OBI:0001014 still has the same children as before the change.

**Comment by rctauber** [comment]
@jamesaoverton I just checked `obi-edit.owl` in your PR. Looks good to me! Our most recent release caused some issues with AmiGO, and I think this will resolve them.

**Comment by jamesaoverton** [comment]
Just a heads up for those following this issue: I just released a new version of OBI that includes this change.
