### ISSUE TITLE
amend patch clamp terms for Brenda Farrell

### ISSUE THREAD

**Issue by rvita** [obi-ontology/obi#924]
1) edit definition of 'voltage clamp assay' OBI_0002182 to be A cellular electrophysiology assay where the membrane potential of a cell is controlled. This is accomplished through a feedback mechanism where any change in membrane potential is countered by permitting electrical current to flow into or out of the cell. change output to has_specified_output some measurement datum and is about some material entity
2) edit definition of 'patch clamp device' OBI_0001080 to be A device used in electrophysiology that is designed to measure: small (pA) currents that originate from a membrane or measure the potential (mV)  across the membrane. In addition to the electronics it requires a headstage that is designed to communicate with, and secure the patch pipette electrode that forms a high resistance seal with the membrane.

**Comment by rvita** [comment]
As discussed on OBI conference call 4/23/2018 with bfarrell@bcm.edu

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2020-01-13: We added some requested terms, and Brenda Farrell published the relevant paper, so we think this issue can be closed.
