### ISSUE TITLE
add new term 'patch-clamp voltage clamp assay'

### ISSUE THREAD

**Issue by rvita** [obi-ontology/obi#925]
term requested by Brenda Farrell: 'patch-clamp voltage clamp assay'
definition: A voltage-clamp technique which allows for the study of the electrical properties (e.g., capacitance ) of cell membranes especially the plasma membrane of cells.   In this  electrophysiology assay a patch pipette is sealed to the surface of a membrane to monitor electrical current originating at the membrane.   One key distinction of this technique is the electrical resistance of the seal between the cell membrane and the pipette is of the order 1-100 gigaohms, permitting  robust measurements  of small currents (magnitude: picoAmpere) over the area of the cell membrane probed. This area is determined by several different standard configurations. A second key distinction is the pipette is used to transfer both the electrical stimulus to the membrane, and is also used to record the generated currents at the membrane. 
alternative term: voltage clamp electrophysiological recording
parent class: voltage clamp assay
device: patch clamp device, patch pipette
post OBI conference call 4/23/2018 for bfarrell@bcm.edu

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2020-01-13: We don't think this is needed any more, so we're closing the issue.
