### ISSUE TITLE
term request 'whole-cell patch-clamp voltage clamp assay'

### ISSUE THREAD

**Issue by rvita** [obi-ontology/obi#926]
term request by Brenda Farrell 'whole-cell patch-clamp voltage clamp assay'
definition: A patch-clamp configuration where the patch pipette electrode is left in place on the cell membrane until a gigaohm seal is formed between the membrane and the pipette. After which the membrane patch is perforated either chemically, or by application of pressure or by use of an electric field all applied through the pipette. These perforations provide for an electrical connection from the interior of the pipette to the intracellular space of the cell. Measurements made with this voltage clamp technique involve recording currents associated with the entire plasma membrane of a cell or the entire membrane of an organelle. 
alternative term: whole-cell patch-clamp voltage clamp recording
parent class: patch-clamp voltage clamp assay
post OBI conference call 4/23/2018 for bfarrell@bcm.edu

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2020-01-13: We don't think this is needed any more, so we're closing the issue.
