### ISSUE TITLE
term request 'pipette pressure clamp'

### ISSUE THREAD

**Issue by rvita** [obi-ontology/obi#928]
new term request by Brenda Farrell for 'pipette pressure clamp' 
definition: A device that measures and clamps pressure to a desired level
parent class: device
post OBI conference call 4/23/2018 for bfarrell@bcm.edu

**Comment by jamesaoverton** [comment]
Discussed on the OBI developer call 2020-01-13: We don't think this is needed any more, so we're closing the issue.
