### ISSUE TITLE
Equivalence axiom for gene knockdown assay is too inclusive

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#931]
http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0001672

```
EquivalentTo
((assay and (has_specified_input some cultured cell population) and (has_specified_output some (data item and (is about some molecular_function))))) and (achieves_planned_objective some assay objective)
```

This is not correct, the elements of the equivalent expression do not mention anything about knocking down genes.

**Comment by turbomam** [comment]
changed axiom from equivalence to subclass.  need to commit.

create a gene knockdown process and specify it's output?

what about stable vs. transient?

in vivo vs. cell lines?
