### ISSUE TITLE
Correct cDNA Library concept

### ISSUE THREAD

**Issue by DanBerrios** [obi-ontology/obi#938]
cDNA Library has the axioms: 

subclass of
'material entity'
'has grain' some 'recombinant vector'
is_specified_output_of some 'recombinant vector cloning'

These are true for clonally-derived cDNA libraries, but not generally true for other kinds (e.g., for cDNA libraries developed by enzymatic reverse transcriptase in vitro for NGS).  There's confusion here in the use of cDNA library to actually mean clonal libraries (see alternate definition).  I think there should be a distinction made -- with 'clonal cDNA library remaining with the axioms above, and new 'cDNA library' only having the axiom a subclass of 'processed material'.  It's also a collection of 'deoxyribonucleic acids", whereas the clonal library PRS is mentioning in his alternative definition is a collection of E. Coli (or other) cells.

@jamesaoverton 
@proccaserra

**Comment by bpeters42** [comment]
BP: Agreed that this is an issue, and should be fixed (nothing in the definition is about cDNA, and the assumptions that this has to be from recombinant vector cloning is at least debatable). 

Should clear this up along with other materials generated in sequencing applications.

**Comment by jamesaoverton** [comment]
Adding 'cDNA library' as OBI:0002754
