### ISSUE TITLE
Review 'assay antigen role'

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#952]
http://purl.obolibrary.org/obo/OBI_1110120

The textual definition is poor. Should it be placed under 'antigen role'?

**Comment by bpeters42** [comment]
antigen role sucks as well. Looks like we need to re-define these terms. 

antigen role: A role of a material entity that is being recognized in whole or in part by receptors of the immune system such as antibodies or T cell receptors. 

assay antigen role: An antigen role that is realized as part of an assay, where immune recognition of the material with the assay antigen role is being detected as part of the assay. 

immunogen role: A role of a material entity that is realized when the material elicits an immune response targeting itself in whole or in part,

**Comment by cmungall** [comment]
Note the text def of 'antigen' references the assay: "is a material entity that has the antigen role"

But the logical def mentions the assay role: 'has role' some 'assay antigen role'

My recommendations would be:

 - adopt the 'antigen role' text definition proposed by Bjoern ASAP (seems good to me, but it can always be tweaked later)
 - change the logical def of antigen, and keep the text def (ie antigens should exist independent of assays or even humans)
 - obsolete assay antigen role, or make it parasitic on antigen role

Longer term (but should not be a blocker for immediate incremental action):

(1) beware of a subtle coreference antipattern if this text def is expanded to OWL "A role of a material entity that is being recognized in whole or in part by receptors of the immune system such as antibodies or T cell receptors.". I will expand on later.

(2) consider coordinating with GO

this term was added by Alex:

```
id: GO:0050851
name: antigen receptor-mediated signaling pathway
namespace: biological_process
def: "A series of molecular signals initiated by the cross-linking of an antigen receptor on a B or T cell." [GOC:add]
synonym: "antigen receptor-mediated signalling pathway" EXACT []
is_a: GO:0002429 ! immune response-activating cell surface receptor signaling pathway
```

should these have a logical definition that depends on 'antigen role' (living outside OBI?).

see also:

```
id: GO:0003823
name: antigen binding
namespace: molecular_function
def: "Interacting selectively and non-covalently with an antigen, any substance which is capable of inducing a specific immune response and of reacting with the products of that response, the specific antibody or specifically sensitized T-lymphocytes, or both. Binding may counteract the biological activity of the antigen." [GOC:jl, ISBN:0198506732, ISBN:0721662544]
subset: goslim_chembl
subset: goslim_pir
synonym: "antibody" RELATED []
synonym: "B cell receptor activity" RELATED []
synonym: "immunoglobulin" RELATED []
synonym: "opsonin activity" RELATED []
is_a: GO:0005488 ! binding
```

(yes, this is really problematic for multiple reasons)

If the GO definitions can be improved, perhaps the existential direction should be role->process, i.e. define the role in terms of the process?

i.e. a role that is realized by the initial binding in an receptor-mediated signaling pathway that elicits immune response

(first pass; the main idea is to state clearly what the realization of the role is)
