### ISSUE TITLE
broken see also link

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#960]
I can fix this in obi_edit.owl.  How should that be timed relative to the release based on https://github.com/obi-ontology/obi/raw/rc-2018-08-27/obi.owl

There's an obo:IAO_0000116 (editor note) annotation axiom on obo:BFO_0000001 (entity) that says rdfs:seeAlso <http://www.referent-tracking.com/_RTU/papers/CeustersICbookRevised.pdf>.  That link is broken.  Use http://www.referent-tracking.com/RTU/files/CeustersICbookRevised/1.0/CeustersICbookRevised.pdf

**Comment by zhengj2007** [comment]
@turbomam Could you please make an issue tracker on BFO? https://github.com/BFO-ontology/BFO/wiki

**Comment by turbomam** [comment]
@zhengj2007  see https://github.com/BFO-ontology/BFO/issues/223

**Comment by turbomam** [comment]
closing this OBI issue, since a corresponding issue about BFO:0000001 was raised in the BFO GitHub issue tracker
