### ISSUE TITLE
update description annotation

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#964]
> The Ontology for Biomedical Investigations (OBI) is build in a collaborative, international effort and will serve as a resource for annotating biomedical investigations, including the study design, protocols and instrumentation used, the data generated and the types of analysis performed on the data. This ontology arose from the Functional Genomics Investigation Ontology (FuGO) and will contain both terms that are common to all biomedical investigations, including functional genomics investigations and those that are more domain specific.

build -> built

it looks like this has not been updated since the inception of OBI. I favor more concise description fields that describe the contents of the ontology to a prospective user. No need to mention FuGO anymore. Change future tense "will" to what it does

What about

"An ontology for representing biomedical investigations, including the study design, protocols and instrumentation used, the data generated and the types of analysis performed on the data."

**Comment by jamesaoverton** [comment]
I'm happy with the shorter description that @cmungall proposes.

**Comment by bpeters42** [comment]
Sorry, I thought I had already replied. Completely agree on the spirit of the comment, but if we edit it, we should get it right. 

An ontology for representing biomedical investigations, including study designs, assays, instrumentation and reagents used, as well as the data generated and the types of analysis performed on the data to reach conclusions.

**Comment by bpeters42** [comment]
Fine with Chris S. revised version. We should hold off from trying to mention all aspects of OBI though, and whoever wants to add more will have to also propose a cut :)  Let's discuss in the next meeting and implement?

**Comment by jamesaoverton** [comment]
Discussed on 2018-09-24 call. We'll implement @cstoeckert's version.

**Comment by simonjupp** [comment]
Typo in description has also been reported here EBISPOT/OLS#223

**Comment by zhengj2007** [comment]
@zhengj2007 will check whether we need to update the description on OBO Foundry website or obi OWL file and update to Chris suggested version. Also we need to add publication on OBI OBO Foundry website.
