### ISSUE TITLE
NTR: second-harmonic imaging microscopy

### ISSUE THREAD

**Issue by TrisSN** [obi-ontology/obi#965]
NTR: second-harmonic imaging microscopy
definition: Second-harmonic imaging microscopy (SHIM) is based on a nonlinear optical effect known as second-harmonic generation (SHG). SHIM has been established as a viable microscope imaging contrast mechanism for visualization of cell and tissue structure and function.[1] A second-harmonic microscope obtains contrasts from variations in a specimen’s ability to generate second-harmonic light from the incident light while a conventional optical microscope obtains its contrast by detecting variations in optical density, path length, or refractive index of the specimen. [Wikipedia: https://en.wikipedia.org/wiki/Second-harmonic_imaging_microscopy]
descendant_of: light microscopy (CHMO:0000102).

**Comment by bpeters42** [comment]
This looks good, the only major update is to use 'light microscopy' as the parent

Definition: A light microscopy assay that uses a nonlinear optical effect known as second-harmonic generation (SHG) for visualization of a specimen. It obtains contrasts from variations in a specimen’s ability to generate second-harmonic light from the incident light while a conventional optical microscope obtains its contrast by detecting variations in optical density, path length, or refractive index of the specimen. 

Definition source: [Wikipedia: https://en.wikipedia.org/wiki/Second-harmonic_imaging_microscopy]. 

This is being added to assays as we speak
