### ISSUE TITLE
Specimen collection processes with subprocesses

### ISSUE THREAD

**Issue by cuboideum** [obi-ontology/obi#970]
## Use Case

[We](https://github.com/RDFBones) are implementing the OBI in a software supporting biological anthropologists with the documentation of their osteological studies on human skeletons from archaeological or forensic backgrounds. In a typical scenario, there are a number of skeletons (e.g. fatalities from a plane crash, genocide victims buried in a pit, burials in a cemetery) that are to be investigated but which are preserved to varying degrees. Depending on the investigation to be carried out, skeletons might be excluded because they are incomplete or the material is in bad shape. As all skeletons are of interest, these decisions need to be documented, even if material is rejected. Varying numbers of assessments might be necessary to determine if a skeleton is suitable for a certain type of investigation or not.

I understand the assessment of material completeness and preservation to be part of the specimen collection process (obo:OBI_0000659). If the preservation is sufficient, the material constitutes a specimen in the investigation, otherwise not . In a discussion of another aspect of the use case (#968), @bpeters42 [clarified](https://github.com/obi-ontology/obi/issues/968#issuecomment-425128317) the OBI understanding of specimen collection processes:

> we would consider the specimen collection process to be limited to procurement of a specimen, and say assigning it an identifier. The only output in the definition is the specimen itself. If there is a part to the process that generates information about the speciment (here: completeness or could also be weight of the specimen etc.), we would consider that a type of 'assay'. So there would be a 'specimen completeness assessment process' (which could be part of the specimen collection process), where the specimen is the input, and the categorical measurement 'Completeness of glabella 01' is the output.

The following graph illustrates a possible rendering of the example discussed in #968 with the assessment of a glabella region as a subprocess of the specimen collection process. Mind that this issue is just about modelling complex specimen collection processes while other uncertainties about the use case are discussed in the original issue.

![specimencollectionsubprocess_mismatch](https://user-images.githubusercontent.com/8103073/48253605-f91afe80-e407-11e8-9c9c-675adeb6b880.png)

If material is accepted for an investigation, a specimen is registered like so:

![specimencollectionsubprocess_match](https://user-images.githubusercontent.com/8103073/48253626-033cfd00-e408-11e8-9e3e-c4f22821e484.png)

## Questions

1. Is this an admissible way of describing specimen collection as a process composed of several assessment processes?
2. Can the class obo:OBI_0000070 ('assay') be used to describe these subprocesses?

We would very much appreciate feedback on this issue.

**Comment by jamesaoverton** [comment]
We plan to discuss this and #968 on next week's call (Nov 19).

**Comment by cuboideum** [comment]
This issue was discussed during the 19 November OBI call. The outcome, to my understanding, was that specimen collection can be modelled in many ways and that the proposed way (i.e. having assays as parts of specimen collection) is among them.

@bpeters42, Can we close the issue?

**Comment by bpeters42** [comment]
Yes, that is correct. Closing it now.
