### ISSUE TITLE
Rename 'ID' column to 'Ontology ID' in all templates

### ISSUE THREAD

**Issue by jamesaoverton** [obi-ontology/obi#978]
Excel does not like files starting with 'ID'. It guesses that they belong to an obscure format and throws a warning or an error. We should just change them all.

**Comment by rctauber** [comment]
The biobank specimens template already has this as 'OBI ID'. Do you want the others to match that, or should I change that to 'Ontology ID' as well?

**Comment by jamesaoverton** [comment]
I think we should use 'Ontology ID' for all the OBI templates, and encourage that for all ROBOT templates.

**Comment by zhengj2007** [comment]
Double check and close the issue if it has been done.

**Comment by rctauber** [comment]
This was resolved by #980
