### ISSUE TITLE
Why does OBI use owl:real as the Range for 'has specified numeric value'?

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#983]
Why does OBI use `owl:real` as the Range for `has specified numeric value`?

Other datatype properties use xsd types for their Ranges, like `has measurement value` => `xsd:double`

Why do I care?  Graphdb, the triplestore product being used for the TURBO project, doesn't seem to understand that `owl:real` is indicative of numbers.  For example, sorting a column of `owl:real` values results in word order sorting, not numerical order sorting.

Here's a list of the types that can be used in OWL ontologies, potenitally along with other =useful background.  See "Table 3. Reserved Vocabulary of OWL 2 with Special Treatment"

https://www.w3.org/TR/owl2-syntax/#Datatype_Maps

**Comment by jamesaoverton** [comment]
The ranges on these datatype properties were never carefully thought out. We don't want to cause implementation problems. We can consider dropping them.

@obi-ontology/obi-developers Do the range restrictions on our datatype properties make a difference for your implementations? (They are for Mark.)

**Comment by ddooley** [comment]
Although owl:real is the most abstract of all number types and therefore makes sense as the most general constraint, I agree that pragmatically it is best to leave the constraint out if it impinges on triple store sorting behaviour.

**Comment by turbomam** [comment]
I enjoyed re-reading this discussion but don't have a personal investment in this issue any more. It can be closed as far as I am concerned.
