### ISSUE TITLE
Which xsd types and triple patterns to use for dates of birth?

### ISSUE THREAD

**Issue by turbomam** [obi-ontology/obi#984]
This issue has two parts:

**One:**  the following literal types are suggested (required?) in OWL ontologies:  `xsd:dateTime` or `xsd:dateTimeStamp`.  

http://www.datypic.com/sc/xsd11/t-xsd_dateTimeStamp.html says  

> Its only difference from dateTime is that the time zone expression is required at the end of the value.

The TURBO team has been using `xsd:date` to capture dates of birth, as we generally don't know the time at which Penn Medicine patients were born.  Is that "bad" only in a theoretical sense (departure from guidelines), or could it cause any technical problems in an OWL triplestore?

----

**Two:** what pattern of classes and predicates should be used to link a person to their data of birth?  

Is a date of birth a `time measurement datum` (A scalar measurement datum that is the result of measuring a temporal interval).  What is the interval?  From 00:00:00, 01 January, year 1 AD to the time/date of birth?

If so, should we use 

TMD1 a `time measurement datum`
TMD1 `has value specification` VS1
VS1 `has specified value` `1969-03-29` (with _some_ xsd type tag)

If so, what is the datum about?  The process boundary that started the neonate stage that some person participates in?  We have been short-cutting this by saying 

HS1 a `homo sapiens`
HS1 `born at` DOB1
TMD1 `is about` DOB1

Where
`born at` subProtertyOf `'participates in' o  inverse (starts)`
`born at` Domain `Homo sapiens`
`born at` Range `start of neonate stage`

This gives the benefit that HS1 can only have one DOB1 as a matter of ground truth, but there could be multiple TMDx instances about it, which could be sorted out by some rules engine.

**Comment by jamesaoverton** [comment]
Discussed on the 2018-11-12 call. We'd be happy to see a proposal on the best way to move OBI forward on this front.

**Comment by turbomam** [comment]
I enjoyed re-reading this discussion but don't have a personal investment in this issue any more. It can be closed as far as I am concerned.
