### ISSUE TITLE
'some' vs 'only' restrictions

### ISSUE THREAD

**Issue by beckyjackson** [obi-ontology/obi#987]
'mass value specification' -> `'specifies value of' some mass`

Could this be written as `'specifies value of' only mass`? Other 'scalar value specification' subclasses could follow this pattern, as well. It would be interesting to see if we can apply this pattern to other value specification classes.

**Comment by ddooley** [comment]
+1 for this.

**Comment by turbomam** [comment]
I'll count the usages of the following and report in the first meeting of 2019.  I'll also change at least a few of the axioms and see what happens to 

- the reasoning time
- inferences made over instances of the modified class(es)

```
?x rdfs:subClassOf ?r .
?r ?p ?o .
```
Where `?p` is either `owl:someValuesOf` vs. `owl:allValuesFrom`

**Comment by turbomam** [comment]
Today I loaded https://raw.githubusercontent.com/obi-ontology/obi/v2018-08-27/obi.owl into a GraphDB repository with no additional reasoning in the triplestore.

## Q:  how many only (`owl:allValuesFrom`) vs some (`owl:someValuesFrom`) axioms are there in OBI?  Also break out by subclasses vs. equivalent classes.

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?p1 ?p2 (count(distinct ?s) as ?count)
where {
    values ?p1 {
        rdfs:subClassOf
        owl:equivalentClass
    }
    values ?p2 {
        owl:allValuesFrom
        owl:someValuesFrom
    }
    ?s ?p1 ?r .
    ?r ?p2 ?o .
    optional {
        ?s rdfs:label ?l
    }
}
group by   ?p1 ?p2
```

> Showing results from 1 to 3 of 3. Query took 0.1s, moments ago.

| p1                  | p2                 | count |
|---------------------|--------------------|------:|
| rdfs:subClassOf     | owl:allValuesFrom  | 53    |
| rdfs:subClassOf     | owl:someValuesFrom | 886   |
| owl:equivalentClass | owl:someValuesFrom | 65    |

or

|                   | owl:equivalentClass | rdfs:subClassOf | Totals |
|--------------------|--------------------:|----------------:|-------:|
| owl:allValuesFrom  |                     | 53              | 53     |
| owl:someValuesFrom | 65                  | 886             | 951    |
| Totals             | 65                  | 939             | 1,004  |

## Q2:  Make sure that all of those axioms have a URI-bearing class (not an anonymous/blank node).

Confirmed.

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
ask
where {
    values ?p1 {
        rdfs:subClassOf
        owl:equivalentClass
    }
    values ?p2 {
        owl:allValuesFrom
        owl:someValuesFrom
    }
    ?s ?p1 ?r .
    ?r ?p2 ?o .
    optional {
        ?s rdfs:label ?l
    }
    filter(isblank(?s))
}
```

## Q3:  what ontologies are the sources of the subject terms in `only` axioms?

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?source (count(distinct ?s) as ?count)
where {
    values ?p {
        owl:allValuesFrom
    }
    ?s rdfs:subClassOf ?r .
    ?r ?p ?o .
    bind(strafter(strbefore(str(?s), "_"), "obo/") as ?source)
}
group by ?source 
```

**Comment by cmungall** [comment]
I urge caution when using universal restrictions. In my experience most people don't understand them and use them incorrectly. In addition you will fundamentally limit the scalability of OBI, all large ontologies like GO, UBERON, CL, primarily use EL++ (with other axioms modularized - see "EL-shunt" pattern).

**Comment by turbomam** [comment]
prioritizing pragmatics, avoiding over-axiomitization
