### ISSUE TITLE
categorical measurement datum referring to existing qualities

### ISSUE THREAD

**Issue by ddooley** [obi-ontology/obi#989]
One unresolved issue is how to set up categorical measurement datums that refer to existing quality and other (e.g. NCBITaxon) class entities for their permitted terms. I propose that we allow categorical value specifications to use 'specifies value of' to point to the categorical root term that underlying selections can be drawn from.  Instances of a given value specification can then point to an underlying term that way too:

![data_john_sex](https://user-images.githubusercontent.com/4000582/49318923-59eda200-f4af-11e8-996b-e04305203a9b.png)

This leaves somewhat redundant and unnecessary the 'has specified value' data property for this kind of categorical value specification.

This continues on a few past discussions including https://github.com/obi-ontology/obi/issues/760 .

**Comment by jamesaoverton** [comment]
We discussed this on 2018-12-10. Damion will update the wiki with documentation about this.
