### ISSUE TITLE
Request to add terms to study design

### ISSUE THREAD

**Issue by chetanamacherla** [obi-ontology/obi#991]
Hi,

I was wondering if you could add "metabolite profiling design assay" and "Lipid profiling design" as child to the "study design".

**Comment by jamesaoverton** [comment]
The centre of OBI is its assays. We have 'metabolite profiling assay' (OBI:0000366) but no 'lipid profiling' assays. Do you need a 'lipid profiling assay' term?

We don't have a child of 'study design' for every assay -- that would result in a huge number of study designs. If the assay term is sufficient, then I would focus on that. If you really need a study design term, please give us more information on your use case. Is there an existing OBI study design term that's close (or analogous) to what you need?

**Comment by mgiglio99** [comment]
Hello, we (myself and @nsuvarnaiari) were seeking a lipid profiling term in OBI and came across this issue.

We would like to formally request the term:  'lipid profiling assay' 
Parent: 'metabolite profiling assay' OBI:0000366
Definition:  "A metabolite profiling assay that detects and identifies lipids resulting from biochemical and cellular metabolism."
This definition was modeled after the definition for 'metabolite profiling assay' which has source "OBI"
Alternative term: 'lipidomic assay'

Also, on a related note, we'd like to request the addition of an alternative term for 'metabolite profiling assay' OBI:0000366 to be 'metabolomic assay'

Thanks,
Michelle and Suvvi

**Comment by mgiglio99** [comment]
Consensus is to make lipid profiling a child of analyte assay.
Consider having a parent profiling assay class.

**Comment by jamesaoverton** [comment]
'lipid profiling assay' http://purl.obolibrary.org/obo/OBI_0002761
