### ISSUE TITLE
single cell RNA sequencing assay 

### ISSUE THREAD

**Issue by masciam** [obi-ontology/obi#995]
I will need to have 'single cell RNA sequencing assay' term and I think should be child of RNA sequencing assay.
Proposed Definition: is an RNA sequencing assay that has specify input RNA extract form only single cell.
Thanks
AM

**Comment by bpeters42** [comment]
In general this is good, but I would suggest to focus on the output. With barcoding techniques, one can argue that many single cell RNA sequencing assays have as an input a large number of cells. It is just that the output can distinguish them. 

Definition: An RNA sequencing assay that outputs data about RNA contained in individual cells.
Parent: 'RNA sequencing assay'

**Comment by mkuhring** [comment]
Pushing #995 and #864. Single cell technology should really be part of OBI, probably by yesterday.
@masciam: Could you formalize your request more according to the [guidelines](http://obi-ontology.org/page/OBI_term_guidelines). I guess that improves the chance for implementation.

**Comment by DanBerrios** [comment]
Consider using single cell specimen as input to single-cell RNA Seq.

**Comment by DanBerrios** [comment]
PR https://github.com/obi-ontology/obi/pull/1100 merged into master on 12/23/19
