### ISSUE TITLE
NTR: enrichment culture medium

### ISSUE THREAD

**Issue by cmungall** [obi-ontology/obi#997]
* Label: enrichment culture medium
 * SubClassOf: http://purl.obolibrary.org/obo/OBI_0000079 culture medium
 * Def: A culture medium that is designed to favor the growth of a particular microorganism over others, enriching a sample for the microorganism of interest. [https://en.wikipedia.org/wiki/Enrichment_culture]
 * Example: selenite broth is an enrichment culture medium used to selectively isolate Salmonella species.

**Comment by jamesaoverton** [comment]
Discussed on the 2019-03-04. This term is good. The only change we'd like is to generalize the definition to match the parent and say 'microorganism or cells'.

Proposed synonym: isolation medium

**Comment by wwhsiao** [comment]
Looks reasonable to me.

**Comment by ddooley** [comment]
Attached is the rdf/xml owl format class for this term that could be pasted into obi-edit.owl directly. It assumes the next high OBI id, OBI_1110301.  Or I do a pull-request on the whole .owl file?

P.s. do I use "alternative term" to define a synonym in OBI? There's no "has synonym" annotation property.

[enrichment culture medium.txt](https://github.com/obi-ontology/obi/files/3081967/enrichment.culture.medium.txt)

**Comment by cmungall** [comment]
I'm not sure how OBI does it, but others use id-ranges files (since there could be PRs from different people in parallel).

Do you want to stick my orcid in there https://orcid.org/0000-0002-6601-2165 thx!

**Comment by ddooley** [comment]
Done ORCID for term editor.  OBI doesn't have a ranges file explicitly right now; possibly that is viable if we also assign a range for robot template use too?

[enrichment culture medium.txt](https://github.com/obi-ontology/obi/files/3082129/enrichment.culture.medium.txt)

**Comment by ddooley** [comment]
Added to pull request
